### ISSUE TITLE
TypeError: Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#1014]
Rax 1.0.2
rax-text 0.6.5

[无法使用](https://github.com/alibaba/rax/issues/1015)
![image](https://user-images.githubusercontent.com/17898715/55312965-4839fc80-5499-11e9-9b1c-2979b0a5c1f2.png)

**Comment by wssgcg1213** [comment]
rax-text has it's 1.0 version published, close this issue.
