### ISSUE TITLE
rax-xxx@1.0 更新

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#1015]
rax-text、rax-view、rax-image、rax-icon、rax-button、rax-touchable、rax-video 希望能和1.0的rax框架匹配
---
>* [![image](https://img.shields.io/npm/v/rax-text.svg?label=rax-proptypes) ![image](https://img.shields.io/npm/v/rax-proptypes/beta.svg?label=rax-proptypes)](https://www.npmjs.com/package/rax-proptypes)
>* [![image](https://img.shields.io/npm/v/rax-text.svg?label=rax-text) ![image](https://img.shields.io/npm/v/rax-text/beta.svg?label=rax-text)](https://www.npmjs.com/package/rax-text)
>* [![image](https://img.shields.io/npm/v/rax-textinput.svg?label=rax-textinput) ![image](https://img.shields.io/npm/v/rax-textinput/beta.svg?label=rax-textinput)](https://www.npmjs.com/package/rax-textinput)
>* [![image](https://img.shields.io/npm/v/rax-video.svg?label=rax-video) ![image](https://img.shields.io/npm/v/rax-video/beta.svg?label=rax-video)](https://www.npmjs.com/package/rax-video)
>* [![image](https://img.shields.io/npm/v/rax-link.svg?label=rax-link) ![image](https://img.shields.io/npm/v/rax-link/beta.svg?label=rax-link)](https://www.npmjs.com/package/rax-link)
>* [![image](https://img.shields.io/npm/v/rax-view.svg?label=rax-view) ![image](https://img.shields.io/npm/v/rax-view/beta.svg?label=rax-view)](https://www.npmjs.com/package/rax-view)
>* [![image](https://img.shields.io/npm/v/rax-slider.svg?label=rax-slider) ![image](https://img.shields.io/npm/v/rax-slider/beta.svg?label=rax-slider)](https://www.npmjs.com/package/rax-slider)
>* [![image](https://img.shields.io/npm/v/rax-image.svg?label=rax-image) ![image](https://img.shields.io/npm/v/rax-image/beta.svg?label=rax-image)](https://www.npmjs.com/package/rax-image)
>* [![image](https://img.shields.io/npm/v/rax-video.svg?label=rax-video) ![image](https://img.shields.io/npm/v/rax-video/beta.svg?label=rax-video)](https://www.npmjs.com/package/rax-video)
>* [![image](https://img.shields.io/npm/v/rax-icon.svg?label=rax-icon) ![image](https://img.shields.io/npm/v/rax-icon/beta.svg?label=rax-icon)](https://www.npmjs.com/package/rax-icon)
>* [![image](https://img.shields.io/npm/v/rax-button.svg?label=rax-button) ![image](https://img.shields.io/npm/v/rax-button/beta.svg?label=rax-button)](https://www.npmjs.com/package/rax-button)
>* [![image](https://img.shields.io/npm/v/rax-touchable.svg?label=rax-touchable) ![image](https://img.shields.io/npm/v/rax-touchable/beta.svg?label=rax-touchable)](https://www.npmjs.com/package/rax-touchable)
>* [![image](https://img.shields.io/npm/v/rax-scrollview.svg?label=rax-scrollview) ![image](https://img.shields.io/npm/v/rax-scrollview/beta.svg?label=rax-scrollview)](https://www.npmjs.com/package/rax-scrollview)
>* [![image](https://img.shields.io/npm/v/rax-recyclerview.svg?label=rax-recyclerview) ![image](https://img.shields.io/npm/v/rax-recyclerview/beta.svg?label=rax-recyclerview)](https://www.npmjs.com/package/rax-recyclerview)

**Comment by yuchonghua** [comment]
Rax 1.0.2
rax-text 0.6.5

[无法使用](https://github.com/alibaba/rax/issues/1014)
![image](https://user-images.githubusercontent.com/17898715/55312965-4839fc80-5499-11e9-9b1c-2979b0a5c1f2.png)

**Comment by yuanyan** [comment]
rax-xxx 组件还在升级中

**Comment by yuchonghua** [comment]
好的，非常感谢和期待

**Comment by yuchonghua** [comment]
https://github.com/alibaba/rax/issues/977#issuecomment-478808210

**Comment by yuchonghua** [comment]
发现一个新问题哦😯，[#889的服务器渲染客户端激活问题、版本兼容问题](https://github.com/alibaba/rax/issues/889)，目前是使用[rax-server-renderer#0.6.5](https://www.npmjs.com/package/rax-server-renderer) 还是[driver-server#1.0.0](https://www.npmjs.com/package/driver-server)，这个问题什么时候可以[兼容](https://github.com/alibaba/rax/issues/1025)呢？非常期待啦

问题是否会随 [rax-xxx@1.0](https://github.com/alibaba/rax/issues/977#issuecomment-478808210)系列的发布而解决呢？如果能这次一起解决该多好啊，非常看好rax1.0

如果 @imsobear 的 [pr#92](https://github.com/alibaba/rax/pull/92)、[pr#75](https://github.com/alibaba/rax/pull/75) 、[pr#12](https://github.com/alibaba/rax/pull/12) 和 @cssivision 的 [pr#](https://github.com/alibaba/rax/pull/93)能够解决[ssr问题](https://github.com/alibaba/rax/issues/1025)该多好啊

/ping @yuanyan @yacheng

**Comment by zengfanyao** [comment]
rax-xxx@1.0 这个版本什么时候有 ，很期待

**Comment by HadiChen** [comment]
期待组件包1.0的更新

**Comment by xiongHenry** [comment]
期待 rax-xxx@1.0

**Comment by AllenZho** [comment]
rax-xxx@1.0什么时候来，很期待

**Comment by yeziZ** [comment]
很期待rax-xxx@1.0，感谢

**Comment by Depravitys** [comment]
期待rax-xxx@1.0的更新，非常感谢🙏

**Comment by carmon0227** [comment]
期待rax-xxx@1.0，感谢

**Comment by SIUISUNE** [comment]
观望1.0

**Comment by yuchonghua** [comment]
非常期待[rax-xxx@1.0](https://github.com/alibaba/rax/issues/977#issuecomment-478808210)系列的发布哦
/ping @yuanyan @yacheng

**Comment by yacheng** [comment]
进展同步：rax-text、rax-textinput、rax-video、rax-link、rax-view、rax-image、rax-slider 已更新 1.0.0 版本，其余部分组件如 scrollview、recyclerview 等可以先试用 beta 版本

**Comment by yuchonghua** [comment]
非常感谢，非常期待和等待rax-xxx@1.0的进一步更新

---

>* rax-icon: [![image](https://img.shields.io/npm/v/rax-icon.svg)](https://www.npmjs.com/package/rax-icon)
>* rax-button: [![image](https://img.shields.io/npm/v/rax-button.svg)](https://www.npmjs.com/package/rax-button)
>* rax-touchable: [![image](https://img.shields.io/npm/v/rax-touchable.svg)](https://www.npmjs.com/package/rax-touchable)

---

/ping @yacheng

**Comment by wssgcg1213** [comment]
> @yuanyan 非常感谢，非常期待和等待rax-xxx@1.0的进一步更新，目前仅剩两个了，这两个会更新为1.0+吗
> 
> > * [![image](https://camo.githubusercontent.com/0bd6583cfeaeebbe5ab3aa568d3e5262fb025848/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f7261782d627574746f6e2e7376673f6c6162656c3d7261782d627574746f6e) ![image](https://camo.githubusercontent.com/d72f7ea04849116a98ce4d06ed3ebfade5524561/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f7261782d627574746f6e2f626574612e7376673f6c6162656c3d7261782d627574746f6e)](https://www.npmjs.com/package/rax-button)
> > * [![image](https://camo.githubusercontent.com/1ffc5a3ab2ce4fd5a47eb577195e05c58d338421/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f7261782d746f75636861626c652e7376673f6c6162656c3d7261782d746f75636861626c65) ![image](https://camo.githubusercontent.com/a7135b6d69388eb165b56417ccf6cce792922d1e/68747470733a2f2f696d672e736869656c64732e696f2f6e706d2f762f7261782d746f75636861626c652f626574612e7376673f6c6162656c3d7261782d746f75636861626c65)](https://www.npmjs.com/package/rax-touchable)

rax-button, rax-touchable 这两个包会在 1.0 的升级后停留在 0.x 的版本上, 原因是我们认为这两个原先的设计在目前看来有些冗余, 最初应该是对齐了 RN 的组件，但是像 button 更像是一个偏业务的 UI 组件, touchable 的能力在 View 上就可以实现 (从前端角度, touchable 更像一个能力抽象组件, 而不是基础组件)

另外目前组件和 API 相关的仓库我们单独迁移到了  github.com/raxjs 这个 group 下.
