### ISSUE TITLE
rax init weex 项目，npm run start 后，终端没有二维码

### ISSUE THREAD

**Issue by MoonandMind** [alibaba/rax#1018]
- Question
 
rax init hello-rax，npm run start 后，终端没有二维码

![image](https://user-images.githubusercontent.com/5037839/55378781-09fe1500-554d-11e9-85a6-0de4618789b8.png)

浏览器显示

![image](https://user-images.githubusercontent.com/5037839/55378818-3154e200-554d-11e9-85f4-8ef9f340b3dd.png)

- Describe
 系统：win7
 浏览器：chrome   73.0.3683.75
 node：v8.11.2
 npm：6.9.0
 rax-cli： 1.2.0

**Comment by yuanyan** [comment]
需手动拼 url 地址，最新版本的 cli 已不再支持输出二维码

**Comment by MoonandMind** [comment]
@yuanyan 感谢回复。
