### ISSUE TITLE
postMessage中window对象可能存在循环引用

### ISSUE THREAD

**Issue by echosoar** [alibaba/rax#1021]
Question:
postMessage中抛出的window对象可能存在循环引用，导致 BroadcastChannel 中 JSON.stringify 循环引用问题

https://github.com/alibaba/rax/blob/74ebaa6aac06585fc8865f2cf624fde04fd9231f/packages/weex-rax-framework-api/src/index.js#L214-L219

**Comment by yacheng** [comment]
该问题在接下来 Rax 1.0 的 weex framework 中重新设计
