### ISSUE TITLE
期待一个现在rax1.0-ssr服务器渲染`demo`, `rax-server-renderer` or `driver-server`

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#1025]
# 一、rax1.0服务器渲染
 现在使用[rax-server-renderer#1.0.0](https://www.npmjs.com/package/rax-server-renderer) 还是[driver-server#1.0.0](https://www.npmjs.com/package/driver-server) ，[两者区别](https://github.com/alibaba/rax/issues/1031)在哪里呢

# 二、rax1.0什么时候支持服务器渲染后[客户端激活](https://github.com/alibaba/rax/issues/889)
 >* A.目前 rax 的 render 是不会去移除原有节点下已有的内容，导致出现了两个的问题
>* B.服务器渲染的客户端激活[Fix ssr checksum->pull#92](https://github.com/alibaba/rax/pull/92)，大概什么时候可以实现，还是非常期待 @imsobear 的 pr
>* https://github.com/alibaba/rax#server-side-rendering-and-hydration 这个时候已经无法配合 rax#1.0 使用

# 三、服务器渲染的相对大小问题如何解决

**Comment by yuchonghua** [comment]
期待 https://github.com/alibaba/rax/issues/1015 能解决

**Comment by chenjun1011** [comment]
问题1，可以用  rax-server-renderer  1.0.0 版本,  问题 2、3  可以描述的更具体点吗  现在不是很看的明白

**Comment by yuchonghua** [comment]
@chenjun1011 非常感谢您的回复，我现在整理一下

**Comment by yuchonghua** [comment]
我先使用1.0版本的再次测试 问题三： https://github.com/alibaba/rax/issues/889 是否还出现后，我将做一个demo

**Comment by yuchonghua** [comment]
问题二： 
期待rax、 rax-server-renderer  能有类似 react-dom 的 renderToString 与 renderToStaticMarkup 的方法
并且解决渲染渲染两次的问题[服务器的渲染内容在客户端没有被清理掉]

参考 
>* https://www.jianshu.com/p/5fa6d6c63d96
>* https://github.com/alibaba/rax/issues/889#issuecomment-459310524
>* https://github.com/alibaba/rax/pull/92

**Comment by yuanyan** [comment]
rax 1.0 已经不会渲染 2 次

**Comment by yuchonghua** [comment]
好的，非常感谢
/ping @yuanyan
