### ISSUE TITLE
想深入理解 driver之间的区别:driver-dom、driver-worker、driver-webgl、driver-server、driver-weex

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#1030]
### 一、方便介绍一下以下五个`driver`之间的区别吗？
>* [driver-server](https://www.npmjs.com/package/driver-server), 这个和[rax-server-renderer#1.0.0](https://github.com/alibaba/rax/issues/10310)区别是？？？
>* [driver-dom](https://www.npmjs.com/package/driver-dom) , 用于`浏览器`，
>* [driver-weex](https://www.npmjs.com/package/driver-weex), 用于[`weex`](https://weex.apache.org/)
>* [driver-worker](https://www.npmjs.com/package/driver-worker)，这个用于浏览器的`worker`？有文档+demo吗
>* [driver-webgl](https://www.npmjs.com/package/driver-webgl)，期待一个demo

**Comment by yuanyan** [comment]
driver-worker与webgl都是实验性阶段当前不推荐

**Comment by yuchonghua** [comment]
好的，driver-worker 是一个什么样的概念呢？还是不太懂，方便说一下吗？
/ping @yuanyan

**Comment by yuchonghua** [comment]
我先把问题关闭了，如果能有个文档该多好，非常感谢你的回复，如果可以还是期待一个使用文档
