### ISSUE TITLE
rax-server-renderer#1.0.0 和 driver-server#1.0.0 区别

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#1031]
想深入了解一下
[rax-server-renderer#0.6.5](https://www.npmjs.com/package/rax-server-renderer) 和 [driver-server#1.0.0](https://www.npmjs.com/package/driver-server) 

>* 这两者的区别是什么呢？
>* 他们的使用场景分别是什么呢？
>* 想进一步了解[driver之间的区别](https://github.com/alibaba/rax/issues/1030)

**Comment by yuanyan** [comment]
dirver-server 主要用与 testing，这个包名字后续可能会修改

**Comment by yuchonghua** [comment]
好的，明白了，开始有点误解了，原来是一个自动化测试使用的
