### ISSUE TITLE
Text组件 numberOfLines 会相互影响

### ISSUE THREAD

**Issue by sjwl123** [alibaba/rax#1041]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug
2. Describe your issue:
当添加多个text组件时：
      第一个text设置numberOfLines为1，后面的都设置为0都正常
      第一个text设置numberOfLines为1，后面的有一个设置为1就全部都变成只能显示1行
      第一个text设置numberOfLines为0，后面的有一个设置为1后，在设置为1的后面的全部都变成只能显示1行

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codepen.io/sjwl123/pen/axqmbG) on CodePen
.

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/58399915-3e450c00-808c-11e9-9877-2beae38457b3.png)

**Comment by wssgcg1213** [comment]
cc @yacheng

**Comment by yacheng** [comment]
组件最新版本已经修复，避免修改引用对象 https://github.com/raxjs/rax-components/blob/master/packages/rax-text/src/index.tsx
