### ISSUE TITLE
[rax-scrollview] 问题标题

### ISSUE THREAD

**Issue by kevinxie120** [alibaba/rax#1047]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by kevinxie120** [comment]
how to make pageEnable by Raw-ScrollView？

**Comment by amdgigabyte** [comment]
> how to make `pageEnable` by Raw-ScrollView？

can u explain what the `pageEnable` functionality is？

**Comment by wssgcg1213** [comment]
Timeout for issue, reopen it if you still need it.
