### ISSUE TITLE
rax 1.x的flexbox兼容性

### ISSUE THREAD

**Issue by leedut** [alibaba/rax#1049]
看到了driver-dom的最新改动，在这次[commit](https://github.com/alibaba/rax/commit/57842f8cbf632d83b401bb431973597ebc710510#diff-3d77ea7401ce23049d960f38b91a3b95)里移除了flexbox的兼容性写法的注入。

想请教一下，这次的改动表示后续兼容性不考虑了android 4.3及以下的机型了么？还是有别处的实现呢？

**Comment by wssgcg1213** [comment]
driver-dom 会更专注于 DOM API 的适配, 兼容性会通过工程手段解决

**Comment by wssgcg1213** [comment]
driver-universal 补充了 flexbox 的兼容性写法, 可以关注这个 PR https://github.com/alibaba/rax/pull/1092
