### ISSUE TITLE
animBuoyStyle设置宽高不起作用[rax-tabheader] 问题标题

### ISSUE THREAD

**Issue by feikaixin** [alibaba/rax#1076]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by yacheng** [comment]
0.x 版本的 rax-tabheader 不支持宽高的定义，只支持颜色修改。1.0 的 tabheader 组件将会重新进行设计
