### ISSUE TITLE
[rax-grid] invalid conditions for `justifyContent` on <Row />

### ISSUE THREAD

**Issue by Songkeys** [alibaba/rax#1106]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - **Bug**

2. Describe your issue:

  - What is the current behavior?
  **`<Grid style={{ justifyContent: 'space-between' }}>` not working.**
  - Which versions of Rax, and which browser / OS are affected by this issue?
  **`rax 0.x.x`, `rax-grid 0.6.5` (latest)**
  - Did this work in previous versions of Rax?
  **Apparently no.**

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen.

This script won't be working:

```jsx
        <Row style={{ justifyContent: 'space-between' }}>
          <Col style={{ maxWidth: 10 }} />
          <Col style={{ maxWidth: 10 }} />
        </Row>
```
However, adding `gridType="space-between"` to `<Row>` would work.

**The reason is there is no default value for `gridType`, but it gets to override the styles if the `justifyContent` is not `space-between` ....**

![image](https://user-images.githubusercontent.com/22665058/59839151-cdd79500-9382-11e9-8d99-f084219d3507.png)

Please fix this as follows:

```jsx
    if (gridType == 'flex-start') {
      styles.initial.display = 'block';
    } else if (gridType !== undefined) {
      moreStyle.justifyContent = gridType;
    }
```

**Or please suggest the `gridType` clearly in the doc.**

Thanks.

**Comment by yacheng** [comment]
This component is not recommended. Use view
