### ISSUE TITLE
Rax语法支持JSX，但是所有的React API都被Rax替代，这样一些开源的React的库文件在Rax基本运行不起来，是否有这样的问题呢？比如我想引用一个React下比较成熟的框架到Rax中来，会报一些API错误

### ISSUE THREAD

**Issue by yolynn-bird** [alibaba/rax#111]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by yuanyan** [comment]
技术上可以通过打包工具来定义rax包的别名，言下之意就是 `require("react")` 的代码会重定向到 `require("rax")`, 我们正在做这方面的工作
