### ISSUE TITLE
使用官网提供的脚手架命令构建的项目起动不了

### ISSUE THREAD

**Issue by xingcun** [alibaba/rax#1118]
## Help us to manage our issues by answering the following:

# 使用官网提供的脚手架命令构建的项目起动不了
### npm start

启动出错
![43375562e245510ae8d974800a642a3](https://user-images.githubusercontent.com/14237778/60225634-2f838c00-98ba-11e9-9f05-449b5f1b2f5c.png)

**Comment by chenjun1011** [comment]
你好，感谢反馈

可以通过修改 package.json 中的 scripts 配置，来解决这个问题

将下面的写法

```
rax-scripts start --type 'component'
```

修改为

```
rax-scripts start --type=component
```
原因是，上面的这种方式，在 windows 下会存在兼容性问题

稍后，我们会升级下默认的脚手架，修复这个问题。
