### ISSUE TITLE
在weex中有this.$getConfig()获得系统的配置，比如env、bundleUrl，在rax中如何获取？

### ISSUE THREAD

**Issue by Mryong** [alibaba/rax#112]
在weex中有this.$getConfig()获得系统的配置，比如env、bundleUrl，在rax中如何获取？

**Comment by boiawang** [comment]
通过 `window. navigator` 可以取到 `env`，`window.location` 可以取到 `bundleUrl `

**Comment by Mryong** [comment]
@boiawang 
iOS中Weex报错，找不到window对象，难道我要把Weex升级下？
<Weex>[error]WXMonitor.m:190, [undefined:122:51] ReferenceError: Can't find variable: window

**Comment by boiawang** [comment]
@Mryong 需要升级 weex 到 0.9.4+
