### ISSUE TITLE
handle svg in DriverDOM

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#1129]
Rax 里面对 svg 的处理好像有问题，这里的 xlinkHref 在 React 里面是 xlink:href， 而到 Rax 里面就变成了 xlinkHref，结果导致 SVG 图标显示不了 ：

![image](https://user-images.githubusercontent.com/3922719/60937005-9e70d400-a301-11e9-9954-9cc3bf8f9573.png)

**Comment by yuanyan** [comment]
写 jsx 的时候不是 xlink:href 吗？
