### ISSUE TITLE
flex布局中flex属性无效

### ISSUE THREAD

**Issue by Mryong** [alibaba/rax#113]
FlexTestPage.js文件如下：
import {createElement, Component, render} from 'rax';
import styles from './FlexTestPage.css';

class FlexTestPage extends Component {
    render() {
        return (
            &lt;div&gt;
                &lt;div style={styles.div1}>&lt;/div&gt;
                &lt;div style={styles.div2}>&lt;/div&gt;
            &lt;/div&gt;
        );

    }
}
render(&lt;FlexTestPage/&gt;);

FlexTestPage.css文件如下：
.div1{
    background-color: red;
    flex: 1;

}
.div2{
    background-color: yellow;
    flex: 2;
}

期望值是屏幕上下应该按照1：2的比例划分，而实际没有任何效果。

**Comment by yuanyan** [comment]
如果是在h5下，需要使用 rax-components 中提供的元件 `<View>` 代替 `div`, 没有效果是在哪个端？

**Comment by Mryong** [comment]
@yuanyan 在iOS端无效果，h5端未测试。

**Comment by yuanyan** [comment]
@Mryong 

最外层容器必须要有下面基本的布局设置：
```
.container {
  display: flex;
  flex: 1;
  flex-direction: row;
}

<div class="conainter">
<div style={styles.div1}></div>
<div style={styles.div2}></div>
</div>

```
