### ISSUE TITLE
在Rax工程里用React方式实现了一个Slider组件，在浏览器正常运行，而Weex playground无法运行，不知道哪位大神可以看下原因？https://github.com/yolynn-bird/nextday-rax

### ISSUE THREAD

**Issue by yolynn-bird** [alibaba/rax#115]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by yuanyan** [comment]
如果要实现跨容器组件，依赖的能力也必须是可跨容器的，我看了下 Slider 组件的实现是完全基于 web 下的能力，但这些能力 weex 并不支持，所以 weex playground 无法跑。
