### ISSUE TITLE
weex0.80不支持fetch方法，rax对于h5端又不支持var stream = require('@weex-module/stream')方式，有没有什么一致的解决方法。

### ISSUE THREAD

**Issue by Mryong** [alibaba/rax#117]
在rax中用
var stream = require('@weex-module/stream');
    stream.fetch({
        method: 'GET',
        type: 'json',
        url: url
    }, function (res) {
    }, null);
对于h5会报Uncaught TypeError: stream.fetch is not a function 错误，
但是如直接用全局函数fetch api，iOS端又会报
2017-02-13 12:33:52.248 RedStarMain[1460:143957] [fg255,0,0; <Weex>[error]WXMonitor.m:190, [undefined:243:11] ReferenceError: Can't find variable: fetch
doGET
componentDidMount 错误，
有没有什么一致的解决方法，在vue-weex中第一种方法在h5和iOS端是通用的，但是rax却不行。

**Comment by yuanyan** [comment]
weex-rax-framework 有在全局提供 fetch 方法，具体列表可以参考：https://github.com/alibaba/rax/tree/master/packages/weex-rax-framework
