### ISSUE TITLE
setNativeProps can't update event binding

### ISSUE THREAD

**Issue by lufengd3** [alibaba/rax#122]
1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
     - use setNativeProps set event binding multi times, event handler not update correctly
          - web: emit all event binding
          - weex: emit first event binding
  - What is the expected behavior?
     - update event binding as other props
  - Which versions of Rax, and which browser / OS are affected by this issue?
     - Rax 0.1.7
     - All platform
  - Did this work in previous versions of Rax?
     No

3.  [Demo](https://codepen.io/keith3/pen/EZGGyp/)

**Comment by yuanyan** [comment]
@lufengd3 Weex current only support one events on one node.
