### ISSUE TITLE
h5 下动态插入div,渲染组件到该节点，只要带上 ref 就会报错

### ISSUE THREAD

**Issue by leanhunter** [alibaba/rax#127]
1. How would you tag this issue?

  - Question
  
2. Describe your issue:

js
````js
//MyComponent

...
render(){
    return <View ref="test"></View>
}
...
//使用
    var container = document.createElement('div');
    container.setAttribute("id", 'container');
    document.body.appendChild(container);
    render(<MyComponent/>,findDOMNode(document.getElementById('container'))
````

 ref="test" 加上就直接报错

attach: function attach(ownerComponent, ref, component) {
    if (!ownerComponent) {
      throw new Error('You might be adding a ref to a component that was not created inside a component\'s ' + '`render` method, or you have multiple copies of Rax loaded.');
    }

**Comment by yuanyan** [comment]
打包了多个Rax库会报这个错误

**Comment by leanhunter** [comment]
确认了，没有打包多个bundle

**Comment by yuanyan** [comment]
@leanhunter 能提供可复现的代码嘛？可以考虑使用这个模版 http://codepen.io/taobaofed/pen/oByQGb
