### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by aadd1989** [alibaba/rax#1272]
src/ssr/getDevConfig.js: config.output.path = undefined

![image](https://user-images.githubusercontent.com/10625335/63246162-9a3abd80-c294-11e9-976f-12c208d1d94c.png)

**Comment by Orange-C** [comment]
Please provide the steps to reproduce and if possible a minimal demo of the problem.

**Comment by aadd1989** [comment]
rax-cli: 2.1.0

**Comment by aadd1989** [comment]
版本 ：
rax-cli: 2.1.0
rax: 1.0.8
直接初始化项目 ， 然后启动就会出现错误， 初始化，选项如下
build targets: web、weex、miniapp
SSR：使用SSR

**Comment by Orange-C** [comment]
fixed in #1275
