### ISSUE TITLE
windows start error with Module not found: Error: Can't resolve 'E:projectabcsrcapp.js' in 'E:\project\abc\src'

### ISSUE THREAD

**Issue by cgf150** [alibaba/rax#1315]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
  - when run `npm run start` terminal emits an error '1. Module not found: Error: Can't resolve 'E:projectabcsrcapp.js' in 'E:\project\abc\src'';
  - What is the expected behavior?
 - it should be ok
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - rax-cli: 2.1.0  rax: 1.0.8  windows 10

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by wssgcg1213** [comment]
@Orange-C @DoranYun 确认下问题是否存在，尽早关闭 issue.

**Comment by evilbs** [comment]
搞个 rax

**Comment by Orange-C** [comment]
can‘t reproduce the problem
