### ISSUE TITLE
[rax-recyclerview] 问题标题

### ISSUE THREAD

**Issue by ChuanChuanSu** [alibaba/rax#1328]
安卓端页面刚加载没有发生滚动事件时，调用RecyclerView.scrollTo无效，等到第一次下滑屏幕时才会延迟出现滚动效果。
IOS端没有此现象。

**Comment by wssgcg1213** [comment]
关于客户端 Weex 的问题可以到提到这边, 会有专人跟进: 

https://github.com/apache/incubator-weex/issues

**Comment by ChuanChuanSu** [comment]
调用的是rax组件。。
