### ISSUE TITLE
Spell error 

### ISSUE THREAD

**Issue by eacdy** [alibaba/rax#1334]
In 
<https://rax.js.org/docs/en-guide/getting-start> and <https://rax.js.org/docs/guide/getting-start>

```shell
? Do you want to enable these features?
❯◉ server sider rendering (ssr)
```
I think it means `server sides rendering`.

**Comment by andycall** [comment]
It looks very simple, why not use this opportunity to become an rax contributor?

**Comment by eacdy** [comment]
@andycall Cause I did never find which repo the description in the document above belongs to.

**Comment by andycall** [comment]
cli tools are located in https://github.com/raxjs/rax-scripts

**Comment by Orange-C** [comment]
fixed
