### ISSUE TITLE
postMessage的安全问题

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/rax#1364]
你好：
该文件有两处使用postMessage的安全问题，当您使用postMessage将数据发送到其他窗口时，始终要指定精确的目标origin，而不是*。恶意网站可以拦截postMessage发送的信息。
https://github.com/alibaba/rax/blob/946d1dbcdb0c1eeda502e14b4eb8836e4f0cd79c/website/playground/player.html#L30

https://github.com/alibaba/rax/blob/946d1dbcdb0c1eeda502e14b4eb8836e4f0cd79c/website/playground/player.html#L48

**Comment by wssgcg1213** [comment]
Thanks for warning, it's not used anymore, we'll remove these files.
