### ISSUE TITLE
[Hooks] Uncaught TypeError: current is not a function

### ISSUE THREAD

**Issue by andycall** [alibaba/rax#1389]
1. How would you tag this issue?
  - Bug

2. Describe your issue:
```javascript
import { createElement, useEffect, useState } from 'rax';

export default () => {
    const [visible, setVisible] = useState(false);

    useEffect(async () => {
        let a = await new Promise((resolve) => {
            setTimeout(() => {
                resolve(11);
            });
        });
        console.log(a);
    });

    let element = (
        <div>
            <button onClick={() => setVisible(true)}>update</button>
        </div>
    );

    return element;
}
```
If I click the update button, Rax will throw the error below:
![image](https://user-images.githubusercontent.com/4409743/65595713-eb427d80-dfc7-11e9-81ae-1bcec9d79ca0.png)
![image](https://user-images.githubusercontent.com/4409743/65595744-fac1c680-dfc7-11e9-99ed-12b87b38028f.png)

**Comment by yongningfu** [comment]
Effect里面写async函数本身就不符合规范

**Comment by yongningfu** [comment]
返回值固定有问题

**Comment by andycall** [comment]
在调用之前判断一下是否会返回Promise, 以便给予用户一些更好的提示?

**Comment by yongningfu** [comment]
判断是否是function 更加合理一点？

**Comment by evilbs** [comment]
`useEffect(async () => { 
  ...
});
`
在 react 的 useEffect 使用 async 函数，也是会报如下错误的。
<img width="1151" alt="efs" src="https://user-images.githubusercontent.com/3305041/67617688-385c7e00-f818-11e9-8131-c44b6b40a7ed.png">

**Comment by evilbs** [comment]
可以像 react 一样给出如下友好的提示，这个问题在开发期报出来。 

![qzh](https://user-images.githubusercontent.com/3305041/67617766-30510e00-f819-11e9-8009-a693b19e9683.jpg)

**Comment by evilbs** [comment]
> 判断是否是function 更加合理一点？

不太建议这样做容错，感觉有点像是允许开发者不遵循规则。

**Comment by evilbs** [comment]
` else if (typeof _destroy.then === 'function') {
              addendum = '\n\nIt looks like you wrote useEffect(async () => ...) or returned a Promise. ' + 'Instead, write the async function inside your effect ' + 'and call it immediately:\n\n' + 'useEffect(() => {\n' + '  async function fetchData() {\n' + '    // You can await here\n' + '    const response = await MyAPI.getData(someId);\n' + '    // ...\n' + '  }\n' + '  fetchData();\n' + "}, [someId]); // Or [] if effect doesn't need props or state\n\n" + 'Learn more about data fetching with Hooks: https://fb.me/react-hooks-data-fetching';
            }`

**Comment by yuanyan** [comment]
设计上是应该考虑支持 async，没支持之前可以在开发时提醒

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by evilbs** [comment]
> 设计上是应该考虑支持 async，没支持之前可以在开发时提醒
> 
> Sent with [GitHawk](http://githawk.com)

那我先来一个 PR，^__^

**Comment by evilbs** [comment]
> 设计上是应该考虑支持 async，没支持之前可以在开发时提醒
> 
> Sent with [GitHawk](http://githawk.com)

`useEffect function must return a cleanup function or nothing. Promises and useEffect(async () => ...) are not supported
`

react 里核心代码都是同步并要保证纯，我想是不是这一点上他们没有考虑在 useEffect 返回的值为一个 promise，不然整个链条上的方法改动大并引入了副作用和原有设计？

```javascript
function commitHookEffectList(unmountTag, mountTag, finishedWork) { 
        ...
        if (destroy !== undefined) {
          destroy();
        }
       ...
}
```

**Comment by evilbs** [comment]
是否要讨论一下在 useEffect 里支持 promise? 

@yuanyan @andycall

**Comment by yuanyan** [comment]
如果已经有方案可以直接在这里先抛出来？

**Comment by evilbs** [comment]
> 如果已经有方案可以直接在这里先抛出来？

我再思考一下，目前要执行完这个 effect 才能得到 cleanup 函数！
或者通过 webpackPlugin，使用 babel 写个 ast 解析，把 cleanup 函数从 async 中的 effect 里扣出来？

**Comment by wssgcg1213** [comment]
@evilbs 个人觉得通过 ast 把方案复杂化了, 需要耦合一个构建时插件, 这会导致 rax 无法单独使用, 可以再考虑下; 

不妨看看社区上的方案, 将 useEffect + async function 单独封装一个三方的 hooks, 而 rax 内部支持的 useEffect 可以明确入参的签名不支持 async fn.

ref: https://github.com/rauldeheer/use-async-effect

**Comment by wssgcg1213** [comment]
这个方案为了解决 cleanup 的问题, 多加了一个可选的参数, 作为三方的 API 设计貌似也并无不妥

**Comment by SoloJiang** [comment]
> @evilbs 个人觉得通过 ast 把方案复杂化了, 需要耦合一个构建时插件, 这会导致 rax 无法单独使用, 可以再考虑下;
> 
> 不妨看看社区上的方案, 将 useEffect + async function 单独封装一个三方的 hooks, 而 rax 内部支持的 useEffect 可以明确入参的签名不支持 async fn.
> 
> ref: https://github.com/rauldeheer/use-async-effect

+1

**Comment by SoloJiang** [comment]
`async effect` 作为三方 `hooks`，还可以有更多异步场景的扩展

**Comment by wssgcg1213** [comment]
@SoloJiang 我们的方案定了吗?

**Comment by evilbs** [comment]
> @evilbs 个人觉得通过 ast 把方案复杂化了, 需要耦合一个构建时插件, 这会导致 rax 无法单独使用, 可以再考虑下;
> 
> 不妨看看社区上的方案, 将 useEffect + async function 单独封装一个三方的 hooks, 而 rax 内部支持的 useEffect 可以明确入参的签名不支持 async fn.
> 
> ref: https://github.com/rauldeheer/use-async-effect

我考虑构建方案是让开发者无感知，你考虑的场景也确实存在，所以也同意你这种做法，目前是，
当 useEffect 使用 async 函数时，在 development 环境下是会提示开发者。

我们可以对 useEffect 做一个函数重载。
useEffect(didUpdate);
useEffect(didUpdate, destory);

**Comment by SoloJiang** [comment]
@evilbs 我们目前定的方案是提供两个三方 `hooks`，分别是 `useMountedState` 来获取组件渲染状态，以及 `useAsyncEffect`，来满足异步场景的 `effect`。

**Comment by evilbs** [comment]
> @evilbs 我们目前定的方案是提供两个三方 `hooks`，分别是 `useMountedState` 来获取组件渲染状态，以及 `useAsyncEffect`，来满足异步场景的 `effect`。

为什么要 useMountedState 这个方法，符合什么场景使用？

**Comment by SoloJiang** [comment]
> > @evilbs 我们目前定的方案是提供两个三方 `hooks`，分别是 `useMountedState` 来获取组件渲染状态，以及 `useAsyncEffect`，来满足异步场景的 `effect`。
> 
> 为什么要 useMountedState 这个方法，符合什么场景使用？

异步场景下，开发者需要知道组件此时是否被销毁掉

**Comment by wssgcg1213** [comment]
> > @evilbs 我们目前定的方案是提供两个三方 `hooks`，分别是 `useMountedState` 来获取组件渲染状态，以及 `useAsyncEffect`，来满足异步场景的 `effect`。
> 
> 为什么要 useMountedState 这个方法，符合什么场景使用？

引入异步后, 回调函数执行的时刻已经与渲染流程脱离了, 也就是说很有可能原先的节点已经销毁, 所以这里提供了一个获取状态的 hooks, 当然如果开发者认为不会产生副作用或者自己有控制, 也可以不用 `useMountedState`

**Comment by evilbs** [comment]
> > > @evilbs 我们目前定的方案是提供两个三方 `hooks`，分别是 `useMountedState` 来获取组件渲染状态，以及 `useAsyncEffect`，来满足异步场景的 `effect`。
> > 
> > 
> > 为什么要 useMountedState 这个方法，符合什么场景使用？
> 
> 引入异步后, 回调函数执行的时刻已经与渲染流程脱离了, 也就是说很有可能原先的节点已经销毁, 所以这里提供了一个获取状态的 hooks, 当然如果开发者认为不会产生副作用或者自己有控制, 也可以不用 `useMountedState`

感觉 useMountedState 这里其它情况也要考虑到，比如说：
1.  Refs 这类，如果在 cleanup 函数里面使用 Refs 引用，就用不了，因为 dom 没了？

**Comment by wssgcg1213** [comment]
useMountedState 以及更多的 API 参考这个仓库: https://github.com/raxjs/rax-hooks   
Issue 就关闭了
