### ISSUE TITLE
Cannot add property __validated, object is not extensible

### ISSUE THREAD

**Issue by xcodebuild** [alibaba/rax#1398]
![image](https://user-images.githubusercontent.com/5436704/65679289-5901ae80-e087-11e9-84a0-92b8605721e7.png)

![image](https://user-images.githubusercontent.com/5436704/65679336-733b8c80-e087-11e9-916d-c1c6f1dc0cbb.png)

`rax@1.0.12` 下出现，回退到 `rax@1.0.11` 正常

**Comment by xcodebuild** [comment]
删掉 `node_modules` 重新安装后无论哪个版本都无法复现了。。

**Comment by wssgcg1213** [comment]
我本地试了下也没有办法复现出来

**Comment by andycall** [comment]
看上去哪个地方的代码对JSX Element进行了Freeze， 检查一下整个项目中是否存在 Object.freeze(<div>freezed</div>) 这样对代码，我们检查了Rax 本身和 构建器，我们提供对工具包并不会进行这样对操作
