### ISSUE TITLE
[Feature] hooks的小程序的生命周期好像没有补齐？

### ISSUE THREAD

**Issue by rubyless** [alibaba/rax#1419]
hooks的小程序的生命周期好像没有补齐，比如, App的生命周期也有onShow和onHide，另外现在推荐用lifecycle的方式写小程序吗？还是hooks？

```javascript
const LAUNCH = 'launch';

export const cycles = {};

export function useAppEffect(cycle, callback) {
  switch (cycle) {
    case LAUNCH:
      cycles[cycle] = cycles[cycle] || [];
      cycles[cycle].push(callback);
      break;
  }
}

export function useAppLaunch(callback) {
  return useAppEffect(LAUNCH, callback);
}
```

https://github.com/alibaba/rax/blob/eb4971e4eee3fb06d782f869de5a8439e0583454/packages/jsx2mp-runtime/src/app.js

**Comment by SoloJiang** [comment]
是的，都可以基于 useAppEffect 进行扩展

**Comment by wssgcg1213** [comment]
目前除了 rax 自带的生命周期外, 小程序额外增加的 App 只有 launch 周期，Page 只有 show 和 hide. 其它的你可以提具体需求给我们跟进哈 @rubyless
