### ISSUE TITLE
[Question]create-rax模块的同步问题

### ISSUE THREAD

**Issue by fengxinming** [alibaba/rax#1427]
Please describe the problem you meet.

Create a new Rax project using `create-rax` 中的`create-rax`模块和`rax-cli`模块是否同步？更新时间不一致，是不是`create-rax`这个模块不维护了

**Comment by yuanyan** [comment]
create-rax 依赖的是 rax-cli，create-rax 只是为了 npm init 这个命令存在的包

**Comment by fengxinming** [comment]
@yuanyan rax-cli在packages目录下吗？

**Comment by wssgcg1213** [comment]
@fengxinming github.com/raxjs/rax-scripts

**Comment by fengxinming** [comment]
@wssgcg1213 多谢大佬，刚看完，主要是参考和对比一下，我之前自己写的cli下载模块的时候有警告，还没有进度
