### ISSUE TITLE
[BUG]ReferenceError: primordials is not defined 

### ISSUE THREAD

**Issue by aladdin-add** [alibaba/rax#1436]
**Describe the bug**
![image](https://user-images.githubusercontent.com/13050025/67174949-a1965880-f3f6-11e9-84cb-ab16478e865d.png)

**To Reproduce**
build.json
```js
{
  "plugins": [
    [
      "rax-plugin-component",
      {
        "targets": ["web", "weex"]
      }
    ]
  ]
}

```
```bash
rax-scripts start
```

**Expected behavior**

**Screenshots**

 (please complete the following information)
node: v12.12.0
npm:  6.12.0

**Additional context**

**Comment by Orange-C** [comment]
rax-plugin-component used gulp@3, and gulp@3 is not compitible with node12
