### ISSUE TITLE
[BUG]设置View样式的时候报错undefined

### ISSUE THREAD

**Issue by shannonliang** [alibaba/rax#1448]
**Describe the bug**
设置View样式的时候报错，<View style={[style1,style2]} />
style1 = {width:100,height:100}
style2 = undefined; //可能某些业务逻辑导致这样设置

**Screenshots**
![image](https://user-images.githubusercontent.com/13606897/67665426-aafa6480-f9a4-11e9-9bfc-a60cd1a1b958.png)

 (please complete the following information)
 - Browser chrome
 - Rax Version [1.0.13]

**Additional context**
在这里的styles的设置里，最好先过滤一下无效的style样式，在去赋值。截图中。

**Comment by wssgcg1213** [comment]
这里 driver 的设计是不对 propKey 做校验, 由 DOM 自行判断是否接受, 这跟 React 的设计有差异, 并不是遗漏未做校验

> PS: React 使用了一套白名单对属性进行过滤, 光这些白名单的体积就接近整个 rax 的体积了

**Comment by shannonliang** [comment]
这个for循环下面的 if(hasOwnproperty)是什么意思，循环的不就是属性么。直接改成if(node.style.hasOwnproperty(prop)) 不就ok吗？不用做白名单，过滤掉不合法的属性即可，过滤完成后也可以给出一个warning。
