### ISSUE TITLE
[Feature]Rax-redux 没有升级Rax版本，升级rax后，项目启动会有问题。需要同步。

### ISSUE THREAD

**Issue by shannonliang** [alibaba/rax#1451]
比如 Rax-redux没有使用最新的rax-proptypes 库，会报错的。

**Comment by evilbs** [comment]
我看下

**Comment by yuanyan** [comment]
rax-redux 有一个 1.0 的 beta 版本：https://github.com/alibaba/rax/pull/1439

**Comment by evilbs** [comment]
这个问题可以 close 了？
