### ISSUE TITLE
[Question]升级Rax版本为最新的1.0.13后，之前没写单位会自动按照750自适应，现在失效？

### ISSUE THREAD

**Issue by shannonliang** [alibaba/rax#1454]
![image](https://user-images.githubusercontent.com/13606897/67840281-75828200-fb30-11e9-819e-a86c62fe99b3.png)
官网的升级指南最后写的意思是 ？：（用的多端的Driver-universal）
1、没写单位会自动转换成750比例的 px ？
2、只有写了单位rpx，才会按照750rpx 去自适应？
之前版本0.6.7
最新版本1.0.13

如果需要些单位才能自适应，那升级的rax版本，是不是代价有点大了？

**Comment by yuanyan** [comment]
1. 1.0 的 universal driver 的确只推荐且只支持按 750 作为标准是写 rpx
2. 如果觉得代价大，可以定制 driver，也可以考虑写一个脚本批量改

**Comment by shannonliang** [comment]
嗯嗯，谢谢，我试试定制driver的setStyle   api。
