### ISSUE TITLE
[BUG] Waterfall组件文档中的示例在 Web 环境下渲染异常

### ISSUE THREAD

**Issue by linkgod** [alibaba/rax#1461]
**Describe the bug**

[Waterfall 组件](http://rax.alibaba-inc.com/docs/components/waterfall) 文档中的示例在 Web 环境下渲染异常

单个 Item 应该被高度撑开，个人排查原因是高度没有带单位，此处是否应该修改下文档？或者支持一下不带单位的写法？

```
const data = [
  { height: 550, item: {} },
  { height: 624, item: {} },
  { height: 708, item: {} },
  // ...
];
```

**Screenshots**
![30 11 221 29_9999_(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/1736020/68112381-2a031600-ff2c-11e9-9269-a1bb79130340.png)

**Comment by yuanyan** [comment]
没有支持不带单位，是 driver-dom 里的一个bug，修复版本已经在 PR  里

**Comment by linkgod** [comment]
谢谢

**Comment by linkgod** [comment]
![image](https://user-images.githubusercontent.com/1736020/68121877-e0bec080-ff43-11e9-8110-8442a7e4c876.png)

文档中有个小问题，这里的 gap 应该是 `10`，否则 `370 * 2 + 50  > 750` 了，无法显示在同一行

**Comment by fyangstudio** [comment]
文档已更新
