### ISSUE TITLE
yarn start 启动时报错

### ISSUE THREAD

**Issue by czf0321** [alibaba/rax#1474]
yarn run v1.17.3
$ rax-scripts start
[JSX+] Stynax enabled.
i ｢wds｣: Project is running at http://192.168.1.3:9999/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from D:\celesea\sys\rax-web
Compiling...
(node:18672) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Warning: Each child in a list should have a unique "key" prop. Check the render method of `Document`.
ax-websrcapp.json' in 'D:\celesea\sys\rax-web\src\pages\Home' 

ax-websrcdocumentindex.jsx' in 'D:\celesea\sys\rax-web\src\pages\Home' 

ax-websrcpagesHomeindex' in 'D:\celesea\sys\rax-web\src\pages\Home' 

Set environment `DEBUG=true` to see detail error stacks.

**Comment by yuanyan** [comment]
提供的信息看着不是全的？

**Comment by czf0321** [comment]
刚初始化的项目发自我的华为手机-------- 原始邮件 --------主题：Re: [alibaba/rax] yarn start 启动时报错 (#1474)发件人：元彦 收件人：alibaba/rax 抄送：czf0321 ,Author 提供的信息看着不是全的？

**Comment by czf0321** [comment]
刚创建的项目，结构如下
![image](https://user-images.githubusercontent.com/30063100/68351539-bb49d680-013e-11ea-974d-84c5e0019438.png)
![image](https://user-images.githubusercontent.com/30063100/68351563-d0bf0080-013e-11ea-879e-4d39c778d569.png)
![image](https://user-images.githubusercontent.com/30063100/68351620-f815cd80-013e-11ea-8452-e7d65c40b06b.png)
![image](https://user-images.githubusercontent.com/30063100/68351632-ffd57200-013e-11ea-91be-91eae951cb29.png)

**Comment by Orange-C** [comment]
build.json去掉rax-plugin-ssr还会报错吗

**Comment by czf0321** [comment]
> build.json去掉rax-plugin-ssr还会报错吗
去掉可以了
