### ISSUE TITLE
rax是否支持支付宝小程序，是否有完整的案例可以参考

### ISSUE THREAD

**Issue by likelight** [alibaba/rax#1517]
目前需要开发一个支付宝小程序，想知道是否支持用rax来进行开发；

**Comment by ChrisCindy** [comment]
> 目前需要开发一个支付宝小程序，想知道是否支持用rax来进行开发；

支持，已有业务正常上线。

**Comment by SoloJiang** [comment]
支持的，外网案例近期会开源，内网用户可以私聊 Rax 团队同学

**Comment by wssgcg1213** [comment]
文档可参考 https://rax.js.org/docs/guide/about-miniapp
