### ISSUE TITLE
Rax 构建问题

### ISSUE THREAD

**Issue by qiyuan2018** [alibaba/rax#1522]
构建好的 Rax Bundle始终没有// { "framework": "Rax" }这一行代码，如何初始化 Rax Weex Frameowrk？

**Comment by yuanyan** [comment]
请描述下问题的上下文？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qiyuan2018** [comment]
我执行npm run build 后生成的js文件我想在weex容器运行，但是发现生成的代码是精简代码，生成的js代码也没有// { "framework": "Rax" }这一行注释，我需要如何操作？我编辑的时候预览http://192.168.1.14:9999/weex/index.js?wh_weex=true这个是可以运行的，npm run build后找不到weex可以运行的文件，有详细的使用教程吗？

**Comment by wssgcg1213** [comment]
weex 的构建结果位于 `$projectDir/build/weex` 路径下

**Comment by wssgcg1213** [comment]
你可以把命令行输出的结果粘贴一下

**Comment by qiyuan2018** [comment]
好的，我刚刚重新创建了项目，再生成了一下就有了，应该是我创建选择的问题，谢谢了
