### ISSUE TITLE
weex容器标题

### ISSUE THREAD

**Issue by qiyuan2018** [alibaba/rax#1524]
weex容器下如何修改容器的标题呢？

**Comment by balloonzzq** [comment]
需要 native 扩展支持，可以参考 weex 官网[接口](https://weex.apache.org/zh/docs/api/ios-apis.html#native-%E5%AF%B9%E5%A4%96%E6%8E%A5%E5%8F%A3)文档。

**Comment by yacheng** [comment]
当前开源的 weex 版本中没有提供相关模块与 API

**Comment by qiyuan2018** [comment]
好的
