### ISSUE TITLE
[BUG]在安卓weex环境下嵌套的onAppear，里面的那个会重复调用

### ISSUE THREAD

**Issue by chenbokun** [alibaba/rax#1536]
**Describe the bug**
`<RecyclerView>
      <RecyclerView.Cell className="container" onAppear={this.onAppear}>
        <View className="text" onAppear={this.test}>
          <Text>Hello Rax</Text>
        </View>
      </RecyclerView.Cell>
      </RecyclerView>`
内部的test函数执行了两次

**To Reproduce**
使用安卓淘宝、飞猪进入jsplayground扫码
https://jsplayground.taobao.org/raxplayground/4fb779b4-fb9f-4be3-ac36-0754d9f84fe3

**Expected behavior**
嵌套的onAppear，让其只执行一次

 (please complete the following information)
 - Device: Android
 - OS: Android
 - Browser TB, LX
 - Rax Version 0.x.x

**Comment by wssgcg1213** [comment]
Bug for android weex only, need to transfer to @WeexTeam.   
已经转移
