### ISSUE TITLE
[BUG]rax-textinput 1.x 版本包含了0.x 版本的依赖

### ISSUE THREAD

**Issue by ibzjs** [alibaba/rax#1537]
**Describe the bug**
rax-textinput 1.x 版本包含了0.x 版本的依赖

![image](https://user-images.githubusercontent.com/15857358/69518552-d5831180-0f92-11ea-80e9-e7bfe58e9d1f.png)

**Comment by SoloJiang** [comment]
@recover758126 cc

**Comment by recover758126** [comment]
马上会去掉

**Comment by SoloJiang** [comment]
@ibzjs https://github.com/raxjs/rax-components/pull/27#pullrequestreview-322072041
升级一下版本到 1.1.2
