### ISSUE TITLE
[Feature] Rax 要求单实例, 对 npm link 一个本地组件调试体验不好

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#1564]
Rax 要求单实例, 对 npm link 一个本地组件调试体验不好, 因为本地组件会依赖另一个 rax, 希望在工程里处理掉这个问题, 避免多实例 rax 引入问题

- checker + warning
- 强制指向同一份 rax

**Comment by andycall** [comment]
我的做法是在项目里，去link rax工程内部的rax

**Comment by wssgcg1213** [comment]
> 我的做法是在项目里，去link rax工程内部的rax

没错, 这样可以解决问题, 不过组件依赖组件的时候或者不同组件依赖不同版本 rax 的时候会有问题  

我建议做成 dev 模式下警告 + 重定向以项目的 rax 为准; prod 模式 fatal error 中断构建
