### ISSUE TITLE
[Enhancement] rax-scripts speed up

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#1565]
RT

**Comment by wssgcg1213** [comment]
初始化项目 30s, 蒂夫那边有个项目超过 2 分钟, 先用缓存解决二次构建的速度.   

platform-loader 可以去判断组件库是否引用了 universal-env, 这样可以排除掉一批不需要 ast parse 的文件

**Comment by wssgcg1213** [comment]
我这边先尝试实现下, 理论上不影响 build-scripts 迁移的事情, 排期下周

**Comment by wssgcg1213** [comment]
睡觉的时候想了一下, dev 模式下 exclude node_modules 貌似对 env 的处理并不会带来副作用

**Comment by SoloJiang** [comment]
> 睡觉的时候想了一下, dev 模式下 exclude node_modules 貌似对 env 的处理并不会带来副作用

感觉和小程序目前的场景类似，需要三方库保证不会产生副作用吧？

**Comment by wssgcg1213** [comment]
> > 睡觉的时候想了一下, dev 模式下 exclude node_modules 貌似对 env 的处理并不会带来副作用
> 
> 感觉和小程序目前的场景类似，需要三方库保证不会产生副作用吧？

是的, 否则就会出现 dev 下和 build 后不一致问题

**Comment by aladdin-add** [comment]
我也遇到这个问题（我们的项目npm start 需要 ~1.5min ╮(╯_╰)╭

a few thoughts:
+ thread-loader
+ ts-loader -> @babel/preset-typescript
+ 忽略 node_modules (development mode)

**Comment by SoloJiang** [comment]
> 我也遇到这个问题（我们的项目npm start 需要 ~1.5min ╮(╯_╰)╭
> 
> a few thoughts:
> 
> * babel cache
> * thread-loader
> * ts-loader -> @babel/preset-typescript
> * 忽略 node_modules (development mode)

前三个感觉可以试试，最后一个，可能会导致上面讨论的问题

**Comment by SoloJiang** [comment]
> 我也遇到这个问题（我们的项目npm start 需要 ~1.5min ╮(╯_╰)╭
> 
> a few thoughts:
> 
> * babel cache
> * thread-loader
> * ts-loader -> @babel/preset-typescript
> * 忽略 node_modules (development mode)

前三个感觉可以试试，最后一个，可能会导致上面讨论的问题

**Comment by wssgcg1213** [comment]
测试了一下, platform-loader 里的 ast parse 只占了比较少的时间 (10s vs 11s), 但是如果 ignore node_modules 就可以加快很多 (6-7s)

**Comment by wssgcg1213** [comment]
试试 dev 模式下忽略 node_modules

**Comment by yacheng** [comment]
启动优化 https://github.com/raxjs/rax-scripts/pull/115

**Comment by yacheng** [comment]
希望构建时参数指定是否需要忽略 node_modules，保持线上结果与本地构建逻辑一致。
预计下周修复
