### ISSUE TITLE
[Question]rax-image 设置动态uri无效！

### ISSUE THREAD

**Issue by bluce** [alibaba/rax#1566]
Please describe the problem you meet.

`render() {
        const { data } = this.props.data;
        const image = data.image;

        return (
            <View>
                <Image
                    source = {{ uri:{image} }}
                ></Image>
                <Text>{data.tipText}</Text>
            </View>
        )
    }`

**Comment by wssgcg1213** [comment]
uri 应该是一个字符串, 不是对象

**Comment by bluce** [comment]
image是个https://gw.alicdn.com/tfs/TB1bBD0zCzqK1RjSZFpXXakSXXa-68-67.png

**Comment by wssgcg1213** [comment]
方便贴一下完整的代码?

**Comment by bluce** [comment]
```js

render() {
        const { data } = this.props.data;
        // const image = data.image;
        const image = "https://gw.alicdn.com/tfs/TB1bBD0zCzqK1RjSZFpXXakSXXa-68-67.png"

        return (
            <View>
                <Image
                    source = {{ uri : {image} }}
                ></Image>
                <Text>{data.tipText}</Text>
            </View>
        )
    }
```

**Comment by bluce** [comment]
@wssgcg1213 如果

uri: "https://gw.alicdn.com/tfs/TB1bBD0zCzqK1RjSZFpXXakSXXa-68-67.png"就可以显示
用uri:{image}就不可以显示

**Comment by bluce** [comment]
@wssgcg1213 已经解决了， uri:image，不需要大括号！
