### ISSUE TITLE
[BUG] duplicate logs in terminal

### ISSUE THREAD

**Issue by yuanyan** [alibaba/rax#1579]
![image](https://user-images.githubusercontent.com/677114/70124985-e2011b80-16b0-11ea-9cd3-144cbbc3b35f.png)

**Comment by Orange-C** [comment]
每次代码更新后都会再打一个log，不主动滚动的话屏幕中只会出现一个

**Comment by yuanyan** [comment]
期望是每次更新不需要重复打出相同的信息

**Comment by wssgcg1213** [comment]
@Orange-C 看起来是清屏有 bug      

现在的模式: 
打印监听信息  
-->  
代码更新  
--> 
软清屏  
-->   
打印编译中  
--> 
编译完成, 软清屏   
--> 
打印监听信息  
-----  

可以改成硬清屏或者想一下修改一下交互形式
