### ISSUE TITLE
[BUG]rax-image 组件build时报错

### ISSUE THREAD

**Issue by wanglijie** [alibaba/rax#1580]
**Describe the bug**
rax-image在build时会报ts类型检查错误，type里缺少resize定义

**To Reproduce**
1. Go to 'rax-components/packages/rax-image'
2. run 'npm run build'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/3660583/70139655-e7209380-16cd-11ea-9b67-62fbbbd80dbe.png)

![image](https://user-images.githubusercontent.com/3660583/70139650-e2f47600-16cd-11ea-854b-4e2938befe27.png)

 (please complete the following information)
 - 组件编译问题

**Additional context**

**Comment by yuanyan** [comment]
rax-image@2.0.1 fixed
