### ISSUE TITLE
[BUG]rax组件工程使用jsx+的x-class写法，编译出的weex版本样式没有内联

### ISSUE THREAD

**Issue by liangbijie** [alibaba/rax#1584]
**Describe the bug**
rax组件工程使用jsx+的x-class写法，编译出的weex版本样式没有内联 

**Screenshots**
![image](https://user-images.githubusercontent.com/12371461/70224681-a9cd0c00-1788-11ea-8009-ac83e10d9156.png)

@SoloJiang

**Comment by SoloJiang** [comment]
Mark.

**Comment by wssgcg1213** [comment]
非 JSX+ 单点问题, JSX+ 在语法定义上确实是这个行为，样式的问题下周会给一个结论

**Comment by wssgcg1213** [comment]
考虑在 babel-plugin-transform-jsx-stylesheet 中集成将 className 和 styles 对象映射为 style 属性的能力, 后续 @boiawang 会跟进这个问题

**Comment by boiawang** [comment]
@liangbijie 在看这个问题了，计划在1.8号前修复掉。

**Comment by boiawang** [comment]
@liangbijie 可以提供一个 demo 代码吗？我这边本地跑了看起来是 ok 的

**Comment by boiawang** [comment]
先 close 掉了，之后复现了再 open。
