### ISSUE TITLE
[BUG]rax-scroll组件默认设置了flex: 1的属性，不符合预期

### ISSUE THREAD

**Issue by liangbijie** [alibaba/rax#1585]
**Describe the bug**
rax-scroll组件默认设置了flex:1的属性，导致rax-scroll的设置高度没有效果
使用的时候，一般都在外需要包一层view，才能正常使用
**Expected behavior**
期望rax-scroll去除flex:1的属性

**Comment by wssgcg1213** [comment]
@yacheng

**Comment by yacheng** [comment]
当前组件使用 flex:1 是为了抹平不同端上的差异，通常使用滚动容器的场景是撑满屏幕的，此时需要外部设置 view 撑满高度。此行为非 bug，不推荐默认去掉
