### ISSUE TITLE
[BUG]jsx2mp-loader support for windows

### ISSUE THREAD

**Issue by simplewei** [alibaba/rax#1591]
**Describe the bug**

 jsx2mp-loader  throw errors in windows  when compiling miniapp .

https://github.com/alibaba/rax/blob/v1.1.0/packages/jsx2mp-loader/src/script-loader.js#L40

**Comment by simplewei** [comment]
![image](https://user-images.githubusercontent.com/7195304/70422792-481de200-1aa7-11ea-87fb-403c9b17fe47.png)

**Comment by SoloJiang** [comment]
This week will solve it. @ChrisCindy
