### ISSUE TITLE
[Question] 工程不支持 node 8?

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#1595]
![image](https://user-images.githubusercontent.com/3922719/70588175-d9f03100-1c06-11ea-8d53-536e261825ea.png)

我的node是8.11.3  这里有个依赖声明了>10.13.0 , 走初始化默认流程安装失败

**Comment by aladdin-add** [comment]
[](https://github.com/nodejs/Release/raw/master/schedule.svg?sanitize=true)
![image](https://user-images.githubusercontent.com/13050025/70677753-07061780-1ccb-11ea-9304-5721c580edb0.png)

node 8 很快就会EOF，推荐使用 node 10/12.
当然，你也可以用 `yarn install --ignore-engines`  来避免报错。

**Comment by wssgcg1213** [comment]
> ![image](https://user-images.githubusercontent.com/13050025/70677753-07061780-1ccb-11ea-9304-5721c580edb0.png)
> 
> node 8 很快就会EOL，推荐使用 node 10/12.
> 当然，你也可以用 `yarn install --ignore-engines` 来避免报错。

是的, 这是为什么这个 issue 是一个 `question` 的原因, 我们需要一个明确的**支持列表**, 不希望用户发出 `哦这个版本会报错, 于是我升级一个版本也许就好了` 这样的不明确的抱怨

**Comment by yacheng** [comment]
文档上增加对运行环境的说明 https://rax.js.org/docs/guide/app-engineer
