### ISSUE TITLE
Compatible with react native navigator

### ISSUE THREAD

**Issue by yuanyan** [alibaba/rax#161]
Support `rax-navigator` in rax.

Ref: https://facebook.github.io/react-native/docs/navigator.html

**Comment by jimmyrogue** [comment]
@yuanyan  
hi  我正在使用rax-redux
请问 ```rax-navigator```可以使用了吗？
不可以的话，我该怎样在link间传递redux的state？

**Comment by boiawang** [comment]
@jimmyrogue https://github.com/alibaba/rax/blob/master/packages/rax-navigation/README.md

**Comment by jimmyrogue** [comment]
@boiawang 谢谢
