### ISSUE TITLE
[BUG]异步页面组件，path参数取不到

### ISSUE THREAD

**Issue by satlxq** [alibaba/rax#1626]
**Describe the bug**
异步页面组件，path参数取不到

**To Reproduce**
app.json中路由配置
```json
{
      "path":"/channel/:id/",
      "source": "pages/Channel/index"
}
```

Channel/index.tsx组件中，id取不到
```javascript
function Channel(props) {
    console.log(props.id);
}
```

 - Device: MAC
 - Browser chrome
 - rax-app 0.2.5, rax-use-router 3.0.0

**Comment by fyangstudio** [comment]
感谢反馈，
问题正在修复： https://github.com/raxjs/rax-scripts/pull/94 

可以先使用 url query 代替
