### ISSUE TITLE
window创建项目失败[BUG]

### ISSUE THREAD

**Issue by Next0186** [alibaba/rax#1627]
**Describe the bug**
使用windows 初始化一个项目失败，下载完 npx，没下文了。

**Screenshots**
![image](https://user-images.githubusercontent.com/44919719/71336523-765cf080-2582-11ea-8d94-4ccc65ef9024.png)

**Comment by yacheng** [comment]
本地尝试一下 npm install rax-cli -g 是否能安装成功，rax init 命令是否可以正常执行。
如果可以正常使用看下是不是本机的安装权限问题

**Comment by Next0186** [comment]
> 本地尝试一下 npm install rax-cli -g 是否能安装成功，rax init 命令是否可以正常执行。
> 如果可以正常使用看下是不是本机的安装权限问题

**Comment by Next0186** [comment]
> 本地尝试一下 npm install rax-cli -g 是否能安装成功，rax init 命令是否可以正常执行。
> 如果可以正常使用看下是不是本机的安装权限问题

执行完 npm install rax-cli -g 后 rax init 命令可以使用，但是问题还是存在。
![image](https://user-images.githubusercontent.com/44919719/71349395-f054a000-25a9-11ea-8e4c-e49631e8b4fb.png)
