### ISSUE TITLE
[Feature] Support for Wechat Miniapp Cloud Functions

### ISSUE THREAD

**Issue by lucifer1004** [alibaba/rax#1634]
**Is your feature request related to a problem? Please describe.**
Currently, I can not find an official plugin to work with Wechat miniapp cloud functions. Manually written functions in `/build` will be overwritten.

**Describe the solution you'd like**
A build plugin like `build-plugin-rax-faas`, but aimed for Wechat miniapp cloud functions.

**Comment by SoloJiang** [comment]
你可以给我的邮箱发邮件，具体聊一下你的场景，我会给你及时的解决方案。我的邮箱是 feifeishen1996@gmail.com

**Comment by lucifer1004** [comment]
@SoloJiang 已经发了

**Comment by xmsz** [comment]
any solution？
