### ISSUE TITLE
[BUG] [wechat-miniprogram] rax-text render not sync with rax-view using same state

### ISSUE THREAD

**Issue by cuiyajie** [alibaba/rax#1642]
**Describe the bug**
I run the demo for wechat miniprogram and found that if I bind same state to rax-view and rax-text, the wechat devtools and real mobile show different value after the state is changed. It is strange that the value displayed in the wxml from devtools are same.

**To Reproduce**
1. Click on Logo Image

**Expected behavior**
the value of view and text are same

**Screenshots**

<img width="372" alt="WX20191225-140754@2x" src="https://user-images.githubusercontent.com/7336358/71434574-1ef48700-2720-11ea-8231-450352db88b5.png">

<img width="754" alt="WX20191225-140833@2x" src="https://user-images.githubusercontent.com/7336358/71434577-22880e00-2720-11ea-886f-9f9439a90c7b.png">

**Source code**
``` javascript
export default (props) => {
  const [ mode, setMode ] = useState('aspectFit')

  const MODE_LIST = ['aspectFit', 'scaleToFit', 'widthFix' ]

  const changeMode =  () => {
    setMode(MODE_LIST[Math.floor(Math.random() * MODE_LIST.length)])
  }

  return (
    <View>
      <Image
        style={styles.logo}
        mode={mode}
        onClick={changeMode}
        source={{
          uri: '//gw.alicdn.com/tfs/TB1MRC_cvb2gK0jSZK9XXaEgFXa-1701-1535.png',
        }}
      />
      <View>{ mode }</View>
      <Text onClick={changeMode} style={{ color: 'red' }}>{ mode }</Text>
      <Text style={{ color: 'yellow' }}>{ mode }</Text>
      <Text style={{ color: 'red' }}>{ mode }</Text>
    </View>
  );
};
```

**Comment by SoloJiang** [comment]
I will see it as soon as possible. Can you join our wechat group ?
<img src="https://img.alicdn.com/tfs/TB1FkIKrKH2gK0jSZJnXXaT1FXa-752-974.png" width="100"/>

**Comment by SoloJiang** [comment]
https://github.com/alibaba/rax/pull/1645
https://github.com/raxjs/rax-components/pull/81
