### ISSUE TITLE
[BUG]This experimental syntax requires enabling the parser plugin: 'nullishCoalescingOperator'

### ISSUE THREAD

**Issue by yinhangfeng** [alibaba/rax#1647]
plugin-proposal-nullish-coalescing-operator 插件没用使用么

![image](https://user-images.githubusercontent.com/2867940/71477461-3b2e1c00-2825-11ea-9431-f19538913987.png)

看了 node_modules 里的 rax-compile-config 确实引入了 plugin-proposal-nullish-coalescing-operator 插件，不知道为什么还是会报错

rax: 1.1.0
build-plugin-rax-app: 1.0.1

**Comment by yinhangfeng** [comment]
optional-chaining 也不支持

**Comment by fyangstudio** [comment]
能贴下你的 package.json 吗

**Comment by wssgcg1213** [comment]
目前没有使用这个插件，我们会考虑一下引入这个语法, 或者你也可以提一个 pr 参与进来~

**Comment by wssgcg1213** [comment]
Need to transfer this issue to https://github.com/raxjs/rax-scripts

**Comment by yinhangfeng** [comment]
> 目前没有使用这个插件，我们会考虑一下引入这个语法, 或者你也可以提一个 pr 参与进来~

已经提了 pr https://github.com/raxjs/rax-scripts/pull/116 有空合一下么

**Comment by yacheng** [comment]
看一下 pr 的评论
