### ISSUE TITLE
[Question] 如何引入普通 css 文件？

### ISSUE THREAD

**Issue by hanai** [alibaba/rax#1653]
例如 reset.css 这类，我直接 import 后 在页面上并没有找到

**Comment by boiawang** [comment]
直接 `import 'reset.css';` 不会引入 css，而是 css in js 的方式，如果你想引入 css，可以在 `build.json` 里将 inlineStyle 设为 false

**Comment by wssgcg1213** [comment]
reset.css 这类全局引入你可以直接在 document/index.js 里面增加一个 link 标签或者 style 标签来引入

**Comment by hanai** [comment]
> 直接 `import 'reset.css';` 不会引入 css，而是 css in js 的方式，如果你想引入 css，可以在 `build.json` 里将 inlineStyle 设为 false

看了下，想要的是这种效果，因为要引入的是依赖的 npm 包里的 css，但是这样配置的话相当于全局生效了吧？需要用到 inlineStyle 的地方受影响么？

**Comment by yacheng** [comment]
独立的  reset.css  资源可以通过 link 标签引入，与 inlineStyle 的方式不冲突

**Comment by chenjun1011** [comment]
> > 直接 `import 'reset.css';` 不会引入 css，而是 css in js 的方式，如果你想引入 css，可以在 `build.json` 里将 inlineStyle 设为 false
> 
> 看了下，想要的是这种效果，因为要引入的是依赖的 npm 包里的 css，但是这样配置的话相当于全局生效了吧？需要用到 inlineStyle 的地方受影响么？

如果设置了 inlineStyle 为 false，意味着 `import 'reset.css'` 这种写法，不会被默认转为 inlineStyle，但不影响其他的 inlineStyle 的写法，比如这类：

```jsx
const divStyle = {
  color: 'blue',
  backgroundImage: 'url(' + imgUrl + ')',
};

function HelloWorldComponent() {
  return <div style={divStyle}>Hello World!</div>;
}

```
