### ISSUE TITLE
[BUG]RecyclerView中，使用横向的ScrollView，ScrollView移出可视范围再移入时，ScrollView的offsetX值被重置了

### ISSUE THREAD

**Issue by ljybill** [alibaba/rax#1657]
**Describe the bug**
如题，RecyclerView中，使用横向的ScrollView，ScrollView移出可视范围再移入时，ScrollView的offsetX值被重置了

**To Reproduce**
1. 创建一个空页面
2. 外层使用RecyclerView包裹，子组件多写几个使容器能够滚动
3. RecyclerView的第一个子组件变成一个横向滚动的scrollView组件
4. 横向滚动的scrollView组件里面增加子组件，使其能够横向滚动
5. 进入页面，先横向滚动
6. 上下滑页面，让横向滚动移出视口
7. 再滑回，让scrollView进入视口
8. 观察ScrollView的offsetX

**Expected behavior**
能够保持原来状态

**Screenshots**
真机录屏
https://github.com/ljybill/rax-recycleview-error-demo/blob/master/preview/RPReplay_Final1577692711.MP4

 (please complete the following information)
 - Device: IOS
 - OS: IOS
 - Rax 1.1.0 和 0.6.7

**Additional context**
复现Demo： https://github.com/ljybill/rax-recycleview-error-demo

**Comment by yacheng** [comment]
看了下，问题是因为 Weex 容器下 list 滚动时会对节点进行回收，此时会清掉记录的状态。
如果业务上需要保留原有位置，可以在该组件 appear 时机通过 scrollvew 的 scrollTo 方法重制状态。

**Comment by ljybill** [comment]
> 看了下，问题是因为 Weex 容器下 list 滚动时会对节点进行回收，此时会清掉记录的状态。
> 如果业务上需要保留原有位置，可以在该组件 appear 时机通过 scrollvew 的 scrollTo 方法重制状态。

好，我们把这个cell的复用给关掉了
