### ISSUE TITLE
[BUG] JSX+下x-slot在web下报错

### ISSUE THREAD

**Issue by Saikiii** [alibaba/rax#1660]
**Describe the bug**
JSX+下x-slot在web下报错

**To Reproduce**
basic usage
slot: `<slot name="extra" />`
template: `<View x-slot:extra>hehehe</View>`

**Expected behavior**
render correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/33949766/71639116-4234ae80-2cab-11ea-8b05-4934820f6b98.png)
![image](https://user-images.githubusercontent.com/33949766/71639147-fc2c1a80-2cab-11ea-8366-cd5d8b1b1d3a.png)

 (please complete the following information)
 - Device: macbook
 - OS: OSX10.14.6 (18G87)
 - Browser: chrome
 - Rax Version: latest

**Additional context**
and could you please contribute a syntax highlighting vs extension for this usage to avoid errors.

**Comment by SoloJiang** [comment]
1月7日前解决

**Comment by wssgcg1213** [comment]
Will fix in this week

**Comment by wssgcg1213** [comment]
fixed in babel-runtime-jsx-plus@0.1.5
