### ISSUE TITLE
[BUG]刚装的rax，运行就报错了，什么情况，阿里对微信小程序的支持就这么随意的吗！！

### ISSUE THREAD

**Issue by FIWE2030** [alibaba/rax#1666]
根据官网文档，一步步运行的
![image](https://user-images.githubusercontent.com/21697518/71761116-6d650b00-2f02-11ea-8039-006341fc931a.png)

![image](https://user-images.githubusercontent.com/21697518/71761272-09dbdd00-2f04-11ea-8559-95219c2bf55a.png)

**Comment by FIWE2030** [comment]
![image](https://user-images.githubusercontent.com/21697518/71761298-29730580-2f04-11ea-9ca8-7bdaa19eb108.png)

**Comment by SoloJiang** [comment]
报错原因是对 windows 的支持不到位，下周三之前解决 windows 的适配问题

**Comment by SoloJiang** [comment]
文档地址 https://rax.js.org/docs/guide/about-miniapp

**Comment by ChrisCindy** [comment]
@FIWE2030 windows 系统目前已支持，可以尝试使用看看。对之前给您造成的不便深表抱歉，感谢您的使用。
