### ISSUE TITLE
[Feature]Support enzyme in rax

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/rax#1669]
**Is your feature request related to a problem? Please describe.**
> Enzyme is a JavaScript Testing utility for React that makes it easier to test your React Components' output. 
Enzyme's API is meant to be intuitive and flexible by mimicking jQuery's API for DOM manipulation and traversal.

**Describe the solution you'd like**
Preact provides [an adapter](https://github.com/preactjs/enzyme-adapter-preact-pure) to compatible with it.

**Comment by SoloJiang** [comment]
Will support it this week or next week.

**Comment by Bijiabo** [comment]
Support now?

**Comment by SoloJiang** [comment]
I was too busy last month. I'll try it on the weekend

**Comment by Bijiabo** [comment]
@ChrisCindy have been supported?
