### ISSUE TITLE
[Feature]期望build-scripts组件工程构建出umd规范的文件

### ISSUE THREAD

**Issue by liangbijie** [alibaba/rax#1686]
**Is your feature request related to a problem? Please describe.**
通过build-scripts开发的rax组件，希望在线预览组件，而在线预览服务依赖于组件的umd规范包

**Describe the solution you'd like**
build-scripts组件工程支持构建出umd规范的文件

**Comment by andycall** [comment]
我们会在下周末之前搞定

**Comment by liangbijie** [comment]
补充一下：
通过build-scripts打包的rax组件，预期在类似jsplayground、jsfiddle、riddle这样的代码片段预览平台上使用，这些平台需要加载npm包的cdn地址，比如riddle平台是基于unpkg服务来加载的。
我尝试跑通此套方案，有一些需要工程层面需要解决的问题
1. build-scripts需要支持umd规范构建
2. build-scripts构建出的组件依赖的rax、rax-view等包依然是`require('rax')`的形式，导致加载不到依赖，需要把依赖打到构建包或者require包的umd文件地址
3. rax的依赖不能打到构建包，因为外部引入组件的时候还会引入rax
4. css文件需要内联
