### ISSUE TITLE
[Question]How to run production build? 

### ISSUE THREAD

**Issue by YUFENGWANG** [alibaba/rax#1709]
I'm targeting MPA ssr, but how to run production build? 

I have run `npm run build` and `NODE_ENV=production yarn start`, but still got 

![image](https://user-images.githubusercontent.com/12859005/72704062-93410f80-3b92-11ea-9c4a-26d4e27e8d62.png)

**Comment by chenjun1011** [comment]
`npm run build` is a production build, after run build ,you can use the output in your node server or publish it as a serverless function.

`yarn start`  is just a local server for development
