### ISSUE TITLE
Module not found: Error: Can't resolve 'D:workspaceweetestsrcpagesHomeindex.jsx' in 'D:\workspace\weex\test\src\pages\Home' 

### ISSUE THREAD

**Issue by Spring8848** [alibaba/rax#1717]
**Describe the bug**
I create a multi-page application using rax-cli command step by step.
the whole process is ok to init the new project.
but finally,when i run 'yarn start',the error shows below:
Module not found: Error: Can't resolve 'D:workspaceweexdianlaibaosrcpagesHomeindex.jsx' in 'D:\workspace\weex\dianlaibao\src\pages\Home' 

there's no problem to run a single-page application after creating it using 'rax init xx' command,but multi-page.

**To Reproduce**
1. rax init xx
2. choose App (Build universal application)
3. enter author name
4. choose Multi-page application
5.only choose weex as my project's target
6.disalbe any features
7.select Y to install dependences
8.cd my project folder,and run 'yarn start',finally errors occur
error message:
info WEBPACK     ERROR in ./src/pages/Home/index.jsx (./node_modules/build-plugin-rax-multi-pages/src/MulitPageLoader.js?type=weex!./src/pages/Home/index.jsx)

Module not found: Can't resolve 'D:workspaceweexdianlaibaosrcpagesHomeindex.jsx' in 'D:\workspace\weex\dianlaibao\src\pages\Home'    
1. Module not found: Error: Can't resolve 'D:workspaceweexdianlaibaosrcpagesHomeindex.jsx' in 'D:\workspace\weex\dianlaibao\src\pages\Home' 

 (please complete the following information)
 - OS:  win7
 - Rax: 1.1.1 
 - Rax-cli: 3.0.1

**Comment by Chechengyi** [comment]
I have encountered the same problem. Have you solved this problem？
