### ISSUE TITLE
how to set devServer config in rax？

### ISSUE THREAD

**Issue by wangchao9240** [alibaba/rax#1718]
how can I set devServer custom in rax just like webpack? I saw a same question in issues #479, but that solution page in this hub is not found. thank you..

**Comment by SoloJiang** [comment]
If you wanner set devServer custom in rax just like webpack, you can use custom build-scripts plugin through webpack chain. However, you can set some options related devServer config in build.json https://rax.js.org/docs/guide/rax-plugin-app

**Comment by wangchao9240** [comment]
thank you！
