### ISSUE TITLE
[Question]支付宝小程序构建目录是否可以自定义？

### ISSUE THREAD

**Issue by fengdi** [alibaba/rax#1723]
build-plugin-rax-app插件是否可以指定支付宝小程序构建到配置某个目录。

具体需求是这样的：

下面是支付宝小程序开发工具的标准工程目录（带云函数）：

小程序项目
├── .tea
├── client    //C端
│   ├── app.js
│   └── ...
├── server   //云函数端
│   └── hello  
└── mini.project.json

**这里希望的是每次构建更新`小程序项目/client`目录，而不是build-plugin-rax-app配置的以平台命名的`miniapp`目录**

ps：这里无论怎么改outputDir配置，都有miniapp目录

#1634 这位作者应该也是遇到了这个问题

**Comment by SoloJiang** [comment]
我们讨论一下

**Comment by fengdi** [comment]
找到一种方法，本地开发可行，目前还不确定正式上线是否可行：

配置mini.project.json，不过我没有找到这配置文档（哪位同学找到文档麻烦贴一下）

在配置文件中加入 ` "miniprogramRoot": "miniapp" `

配置放到miniapp上层目录，小程序指定项目到也到上一层目录

**Comment by ChrisCindy** [comment]
@fengdi mini.project.json 这样配置是可行的，支付宝官方文档还在整理没有放出，目前我们在某些场景下也是使用 mini.project.json 来配置目录的

**Comment by fengdi** [comment]
@ChrisCindy  @SoloJiang thx

**Comment by xmsz** [comment]
有具体的Code演示提供吗 现在也遇到这个问题 但是不知道怎么解决

**Comment by ChrisCindy** [comment]
目前不支持自定义代码产出目录，通过 上面讨论中配置 mini.project.json 的 miniprogramRoot 字段可以指定产出目录。可以尝试一下。

**Comment by xmsz** [comment]
> xmsz 自定义产出目录目前不支持。mini.project.json 的 miniprogramRoot 字段可以指定产出目录。可以尝试一下。

好吧~ 我现在也先手动处理一下
