### ISSUE TITLE
[Question]构建后模块引入路径变成双反斜杠，上传到服务器报错

### ISSUE THREAD

**Issue by fengdi** [alibaba/rax#1726]
`import { runApp, useAppLaunch } from 'rax-app';`

构建后代码为

`import { runApp, useAppLaunch } from ".\\npm\\jsx2mp-runtime";`

小程序开发工具能正常运行，但上传云构建出错：

..\..\npm\jsx2mp-runtime未找到，请检查文件路径及文件名大小写
Module+not+found:+Can't+resolve+'..\..\npm\jsx2mp-runtime'+in+'/home/admin/build/app.js'+

原因应该是路径问题 \\，线上环境没法识别

我尝试将构建后的代码全部改成/，文件不报错了，但npm大量模块全部需要更改，请问如何解决。

**Comment by ChrisCindy** [comment]
@fengdi 如钉钉群沟通，目前绕过方式为使用 Linux 或 macOS 系统进行编译。该问题预计下周修复
