### ISSUE TITLE
[BUG]微信小程序中使用setState会重新触发useEffect方法

### ISSUE THREAD

**Issue by zhugexiansheng** [alibaba/rax#1750]
**Describe the bug**
微信小程序中不管是使用componentDidMount或者usePromise等回调函数更新数据都会重复触发componentDidMount或者useEffect, usePromise的方法，在支付宝小程序中就不会

**Comment by SoloJiang** [comment]
已经验证问题，本周会修复这个问题

**Comment by SoloJiang** [comment]
#1751 已经修复，本周争取发布

**Comment by SoloJiang** [comment]
由于 break change 的缘故，构建器本周在进行重构，所以会在下周发布

**Comment by SoloJiang** [comment]
`build-plugin-rax-app` 升级到 `0.4.0` 即可

**Comment by Victorkangsh** [comment]
```js
  const [code, setCode] = useState(null);
  useEffect(() => {
    console.log(1);
    wx.login({
      success(res) {
        if (res.code) {
          console.log(res.code);
          setCode(res.code);
        } else {
          console.log('登录失败！' + res.errMsg);
        }
      },
    });
  }, []);
```

升级到4.0.0依然有这个问题，无限循环

**Comment by SoloJiang** [comment]
> ```js
>   const [code, setCode] = useState(null);
>   useEffect(() => {
>     console.log(1);
>     wx.login({
>       success(res) {
>         if (res.code) {
>           console.log(res.code);
>           setCode(res.code);
>         } else {
>           console.log('登录失败！' + res.errMsg);
>         }
>       },
>     });
>   }, []);
> ```
> 
> 升级到4.0.0依然有这个问题，无限循环

我复现看看

**Comment by SoloJiang** [comment]
确实有问题 我马上修复下
