### ISSUE TITLE
ts 文件互相引用时小程序编译会报错

### ISSUE THREAD

**Issue by kingback** [alibaba/rax#1763]
**Describe the bug**
ts 文件互相引用时小程序编译会报错

**To Reproduce**
<https://github.com/alibaba/rax/blob/master/packages/jsx2mp-loader/src/babel-plugin-rename-import.js#L38>

- a.ts
- b.ts

```a.ts
import b from './b';
```

`resolve(dirname(resourcePath), value)` 生成的路径为 `path/b`，没有带 `.ts` 后缀，导致 `require.resolve` 找不到报错

**Expected behavior**
支持 `ts` 这种引用类型

**Screenshots**

 (please complete the following information)
 - Device: [e.g. iPhone6, Mac]
 - Rax Version [e.g. 1.0.13]

**Additional context**

**Comment by ChrisCindy** [comment]
https://github.com/raxjs/rax-scripts/pull/242 这个 pr 将会解决该问题。
jsx2mp-loader@0.4.1 版本修复

**Comment by ChrisCindy** [comment]
jsx2mp-loader@0.4.2 版本已修复
