### ISSUE TITLE
[BUG]动态渲染组件时，ref执行时机不正确

### ISSUE THREAD

**Issue by carlisliu** [alibaba/rax#1764]
**Describe the bug**
当页面组件动态渲染时，某些特定情况下组件ref的执行时机不符合预期。

**To Reproduce**
使用如下代码：
```javascript
class Form extends Component {
  constructor(props) {
    super(props);

    this.state = {
      inputs: []
    };
  }

  render() {
    const inputs = this.state.inputs.map(k => {
      return <input ref={this.logRef.bind(this, `dynamic${k}`)} />;
    });
    return (
      <div>
        {inputs}
        <input ref={this.logRef.bind(this, "static")} />
        <button onClick={this.reRender}>re-render</button>
      </div>
    );
  }

  logRef(name, ref) {
    console.log(name, ref);
  }

  reRender = () => {
    let inputs = [];
    if (!this.state.inputs.length) {
      inputs.push(1);
    }
    this.setState({ inputs });
  };
}

```
1. 上面代码，页面加载完成时打印`static <input>`
2. 点击 're-render'按钮，打印    
`static null`    
`dynamic1 <input>`    
`static <input>`    
3. 再次点击 're-render'按钮，打印    
`dynamic1 null`    
`static <input>​`    
`static null`    
4. 如上结果，在最终render后，依照diff对比结果，先执行dynamic1的卸载，再执行static的挂载，最后再执行static的卸载

**Expected behavior**
第二次点击后，按照如下顺序执行：
`dynamic1 null`    
`static ​null`    
`static <input>`    

**Screenshots**
![image](https://user-images.githubusercontent.com/2157653/75435387-eaa27e80-598d-11ea-8d6e-7519df6aec08.png)

 - Device: [ Mac]
 - Browser [chrome]
 - Rax Version [1.1.1]

**Additional context**
对比React执行结果，React执行顺序是期望的顺序。
React执行结果：
![image](https://user-images.githubusercontent.com/2157653/75435707-67355d00-598e-11ea-8d26-8e323660a3a3.png)

react和rax demo代码repository：
[https://github.com/carlisliu/rax-ref-demo](https://github.com/carlisliu/rax-ref-demo)
[https://github.com/carlisliu/react-ref-demo](https://github.com/carlisliu/react-ref-demo)

这种情况会导致对一些React组件库移植的兼容性问题，如antd的Form组件。

**Comment by chenjun1011** [comment]
触发这个问题原因是：Rax 对 Fragment 处理机制的差异，不会将空的 Fragment（对应上面的 inputs） 创建进入 VDOM， 导致更新时的错位。

可以在 inputs 为 空的场景下，返回 null 来绕开这个问题。

---

问题触发过程，大致可以描述为：

* 初始 VDOM 为  [static input、 button]

* 第一次点击按钮后，更新为  [dynamic input、static input,  button] ，初始 VDOM 中的  static input 更新为 dynamic input ，然后重新创建了 static input  和  button

* 第二次点击按钮后，更新为  [static input、 button]  上一次产物中的 dynamic input 被更新为了 static input , 然后删除了原有产物中的 static input ，所以出现了先创建  static input 再销毁的场景
