### ISSUE TITLE
[BUG]Web 中 tabbar 的样式在 `inlineStyle: false` 的情况下是坏掉的

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/rax#1767]
见图：
![image](https://user-images.githubusercontent.com/14757289/75842427-31b7c600-5e0b-11ea-86d0-8115e84b0f36.png)

**Comment by SoloJiang** [comment]
确定是 `inlineStyle` 机制问题，封网结束之后解决

**Comment by boiawang** [comment]
### 背景

之前的机制：

1. inlineStyle: true 的时候，使用 stylesheet-loader
2. inlineStyle: false 的时候，使用 css-loader

这样的话，在 inlineStyle: false 的情况下，用户写了内联的方式是不会生效的，所以策略需要改下：

1. inlineStyle: true 的时候，使用 stylesheet-loader
2. inlineStyle: false 的时候，使用混合模式

@yacheng 一起看看

**Comment by yacheng** [comment]
action:
* stylesheet-loader 支持 `import styles from './index.css'; ` 逻辑的判断 @boiawang 
* 构建逻辑中将行内与非行内样式构建逻辑合为一套，都经过 stylesheet-loader 和  css-loader 的处理 @yacheng

**Comment by boiawang** [comment]
@yacheng 31号前看看能不能在 inlineStyle: false 的模式加下 stylesheet-loader

**Comment by yinhangfeng** [comment]
Navigation 组件也有问题

**Comment by chenjun1011** [comment]
这个问题的原因是， tabbar 组件使用这种方式来赋值样式：

```jsx
import styles from './index.css';

export default function TabBar(props) {
  return (
    <View style={styles.tabbar} ></View>
  );
}
```
上面提到的 `inlineStyle: false 的时候，使用混合模式` 不可行，是因为同一个 `index.css` 如果经过 stylesheet-loader, 已被转换为一个 js 文件，无法再走 `MiniCssExtractPlugin` 

解决这个问题，建议组件如果要考虑兼容 inlineStyle 为 true 和 false 两种场景，需要通过 className 来赋值样式。

参考：

https://github.com/raxjs/rax-components/blob/master/packages/rax-text/src/index.tsx#L52

**Comment by boiawang** [comment]
引入 stylesheet-loader 这种方案尝试了会有问题，后面直接把 pwa 组件提出来放到 rax-components 下

**Comment by boiawang** [comment]
https://github.com/raxjs/rax-components/issues/194 已有 issue，先关闭了

**Comment by fyangstudio** [comment]
#1880
