### ISSUE TITLE
rax-pictrue支持小程序环境的图片压缩

### ISSUE THREAD

**Issue by liangbijie** [alibaba/rax#1772]
背景：
1. 目前构建的小程序包经常因为图片资源过大，被禁止发布
2. 对于用户来说，压缩图片，有助于用户体验提升和节省流量

诉求：
希望rax-picture支持小程序环境的图片压缩，从基础组件层面解决这个问题，提升开发者的开发体验

**Comment by boiawang** [comment]
看了小程序文档，webp 是没有兼容性问题的，所以用户可以自己拼链接，跟目前 weex 的做法类似。

![D043872B-D0A2-4902-BFBC-887A94023DE4](https://user-images.githubusercontent.com/6340730/76083275-308fc000-5fe8-11ea-86f7-ae3d86851fda.png)

如果后续碰到兼容性问题，可以再起一个 issue 看下
