### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MagicLinuxRing** [alibaba/rax#1779]
脚手架创建错误问题，我选的weex工程，结果默认给我创建了web项目

**Comment by SoloJiang** [comment]
确认选择的是 weex 工程吗？是否有复现的操作路径

**Comment by yacheng** [comment]
可以对比一下创建过程中的选项，下面是一个创建 weex 项目的例子

npm init rax

? What's your project type? App (Build universal application)
? What's author's name? rax
? What's your application type? Single-page application (SPA)
? What type of language do you want to use? JavaScript
? Choose targets your project want to run? Weex

**Comment by MagicLinuxRing** [comment]
> 可以对比一下创建过程中的选项，下面是一个创建 weex 项目的例子
> npm init rax
> ? What's your project type? App (Build universal application)
> ? What's author's name? rax
> ? What's your application type? Single-page application (SPA)
> ? What type of language do you want to use? JavaScript
> ? Choose targets your project want to run? Weex

亚城，就是最后一步，我选任何项目都是现实我选择weex

**Comment by MagicLinuxRing** [comment]
> 可以对比一下创建过程中的选项，下面是一个创建 weex 项目的例子
> npm init rax
> ? What's your project type? App (Build universal application)
> ? What's author's name? rax
> ? What's your application type? Single-page application (SPA)
> ? What type of language do you want to use? JavaScript
> ? Choose targets your project want to run? Weex

就是最后一步，我选什么都是web

**Comment by MagicLinuxRing** [comment]
我用的是windows是不是有影响
