### ISSUE TITLE
[BUG] Rax 小程序运行时方案 rax-picture 走到 Web 逻辑

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/rax#1783]
![image](https://user-images.githubusercontent.com/14757289/76597800-49462b80-653c-11ea-93ba-e1fde1fb1ae7.png)

**Comment by SoloJiang** [comment]
Will fix next week

**Comment by wssgcg1213** [comment]
@SoloJiang solved?

**Comment by SoloJiang** [comment]
@ChrisCindy
