### ISSUE TITLE
web页面下tabBar中配置的icon图片找不到

### ISSUE THREAD

**Issue by lang-strive** [alibaba/rax#1813]
app.json下tabBar中配置的icon路径：
<img width="508" alt="截屏2020-03-30上午10 57 54" src="https://user-images.githubusercontent.com/31495553/77870967-620d4b80-7275-11ea-8e3a-01aaf7f11915.png">

浏览：
<img width="981" alt="截屏2020-03-30上午10 43 47" src="https://user-images.githubusercontent.com/31495553/77870400-e5c63880-7273-11ea-9328-f83b9c8350a2.png">

还有两个issue
1. 打包后index.js路径有问题
2.build.json中配置 inlineStyle 行内样式为false失效 ，样式失效

**Comment by SoloJiang** [comment]
图片资源放在 src/public下，tabbar 在 inlineStyle: false 下失效的问题可以看https://github.com/alibaba/rax/issues/1767

**Comment by waylon-gmail** [comment]
解决了吗？
图片放在 src/public 下不行， inlineStyle: true也不行
