### ISSUE TITLE
[BUG]Create a project failed

### ISSUE THREAD

**Issue by yuankai12** [alibaba/rax#1824]
**Describe the bug**
Create a project failed with an error "Install for [ 'create-rax@latest' ] failed with code 1"

**To Reproduce**
npm init rax projectName

**Screenshots**
![image](https://user-images.githubusercontent.com/45032697/78465321-bbb6bf80-7726-11ea-884b-0373430a5066.png)

**Comment by SoloJiang** [comment]
可以看一下本地 npm 的版本是不是在 5.2 以上

**Comment by yuankai12** [comment]
找到问题原因了  没把npm全局安装目录配置到系统变量里面去
