### ISSUE TITLE
[BUG] [TS types] Rax 缺少 ForwardRefExoticComponent，RefAttributes，HTMLAttributes 类型

### ISSUE THREAD

**Issue by andycall** [alibaba/rax#1835]
**Describe the bug**

Rax-view 依赖的一些在 rax 中不存在的 ts 类型

![image](https://user-images.githubusercontent.com/4409743/78971420-1ba1d180-7b3e-11ea-9809-38352d072ba3.png)

https://github.com/raxjs/rax-components/blob/a28e86b232ab47804c9464af01838f97fc110bbe/packages/rax-view/src/index.tsx#L1

**Comment by SoloJiang** [comment]
用了 @types/rax 就好了吧

**Comment by andycall** [comment]
诶，既然rax包下都有了index.d.ts，那为啥还需要安装个 @types/rax

**Comment by andycall** [comment]
而且就算本地安装了 @type/rax, ts还是会依据 rax 里面 pacakge.json 内部的定义来找到 rax 模块下的 index.d.ts ，而不是 @types/rax

**Comment by fyangstudio** [comment]
主仓库的 index.d.ts 得替换下 @yacheng

**Comment by xcodebuild** [comment]
```
npm install --save-dev @types/rax
rm node_modules/rax/index.d.ts
```

后能临时解决

**Comment by kobeng** [comment]
> ```
> npm install --save-dev @types/rax
> ```
> 
> 然后在 `tsconfig.json` 中添加
> 
> ```js
> "paths": {
>       "rax": [
>         "node_modules/@rax-types/rax"
>       ]
>  }
> ```
> 
> 能临时解决

![image](https://user-images.githubusercontent.com/3805839/120062899-f0a67400-c096-11eb-84e6-142cd9f43099.png)

安装你的做法 还是提示有问题  @xcodebuild
