### ISSUE TITLE
在weex中使用rax是否可以引用本地ttf字体图标

### ISSUE THREAD

**Issue by bishen** [alibaba/rax#186]
使用rax比使用we要舒服，但都有同一个问题，似乎不能引用本地资源。
我想使用字体图标
<Icon fontFamily="iconfont" source={{uri: 'https://at.alicdn.com/t/font_pkm0oq8is8fo5hfr.ttf', codePoint: '\uE60f'}}/>
这样，如果客户端无网络，图标就无法显示出来，现在是否有解决办法？
我尝试local://drawable/aaa这样算是可以使用本地图片了，但ttf不行。
还有在windows下 npm run build 不能编译，只能在linux下编译目前

**Comment by yardfarmer** [comment]
由于 android 和 ios 或缺本地资源的路径不同，且如果降级成 web 页面后访问资源的路径同样不同。另外就是怎么知道在 ```<Icon fontFamily="iconfont" source={{uri: path.ttf ```  path.ttf 对应的本地资源是什么，这个问题处理起来比较复杂。

**Comment by yuanyan** [comment]
@bishen 当前我们提供了 image-source-loader：https://github.com/alibaba/rax/tree/master/packages/image-source-loader 来方便本地图片文件的引用，通过扩展文件应该可以解决你的问题

**Comment by yuanyan** [comment]
@bishen “windows下 npm run build 不能编译” 有具体的抱错信息吗？

**Comment by yuanyan** [comment]
@wssgcg1213 image-source-loader 可以考虑变为 local-source-loader，适配本地字体文件的场景

**Comment by wssgcg1213** [comment]
@yuanyan 嗯，这块再看看还有没有其它本地资源的需求，一并加上

**Comment by bishen** [comment]
@yuanyan 使用 image-source-loader，我这里测试了图片https://gw.alicdn.com/tfs/TB1g6AvPVXXXXa7XpXXXXXXXXXX-215-215.png
在windows和linux下得到的是一样的base64码，在web和android上均无法正常显示
我将base64与http://imgbase64.duoshitong.com/对比，是不一样的。
require("image-source得到的base64如下
bW9kdWxlLmV4cG9ydHMgPSB7......KICAgIGhlaWdodDogMjE1CiAgfQ==

native中支持image组件的base64显示方式吗？

**Comment by wssgcg1213** [comment]
@bishen  我解码了你提供的字符串，前部分是 `module.exports = {` 。  
image-source-loader 的正确使用方式应该是  
![image](https://cloud.githubusercontent.com/assets/3922719/24327764/3232a922-120c-11e7-8b6d-be3f40d4a143.png)  

请确认是否使用方式有问题

**Comment by bishen** [comment]
@wssgcg1213 我原来的代码
  render() {
    const source = require("image-source!./a.png");
    console.log(source);
    return (
      <View style={styles.app}>
        <Image source={source}
后来改成你所写，base64正确，在web下img原本就支持这种方式。
测试在weex-android依然无法显示
我问的本地指android和ios.......

**Comment by wssgcg1213** [comment]
YES, 安卓和iOS 都是支持的  
这是在  
![image](https://cloud.githubusercontent.com/assets/3922719/24332717/425ae608-127e-11e7-89c0-e9a7d3455cc9.png)

![image](https://cloud.githubusercontent.com/assets/3922719/24332711/37ea6702-127e-11e7-8590-e2e018776983.png)  

iOS的话我在我自己手机上跑是没有问题的   

你可以提供一下你有问题的设备型号和调试方式吗 @bishen

**Comment by wssgcg1213** [comment]
![image](https://cloud.githubusercontent.com/assets/3922719/24332767/d523e3d6-127e-11e7-8d58-778dc6e4f0a8.png)
  
weex playground 好像有问题，你可以暂时用手机淘宝APP来调试~  这个问题我们尽快解决

**Comment by bishen** [comment]
呃，我的意思是把rax打包进weex的android或ios项目中的app里....

**Comment by yuanyan** [comment]
@bishen weex在android下的图片库应该默认没有支持base64
