### ISSUE TITLE
[Question]如何加入 postcss 插件

### ISSUE THREAD

**Issue by Mayandev** [alibaba/rax#1860]
Please describe the problem you meet.
[Question]如何加入 postcss 插件

**Comment by SoloJiang** [comment]
可以讲一下你的诉求，你可以通过 build scripts 插件来自定义 webpack 配置，但是对于 postcss 的配置可能会导致我们的一些默认配置被覆盖掉

**Comment by Mayandev** [comment]
> 可以讲一下你的诉求，你可以通过 build scripts 插件来自定义 webpack 配置，但是对于 postcss 的配置可能会导致我们的一些默认配置被覆盖掉

感谢回复！我希望通过插件的方式进行配置，使用 postcss 的 autoprefix 功能

```JavaScript
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.module
      .rule('postcss')
      .test(/\.css$/)
      .use('style-loader').loader('style-loader').end()
      .use('css-loader').loader('css-loader').end()
      .use('postcss-loader').loader('postcss-loader')
      .options({
        plugins: [require('autoprefixer')]
      })
  });
}
```

不知否提供一下配置样例

**Comment by Mayandev** [comment]
> 可以讲一下你的诉求，你可以通过 build scripts 插件来自定义 webpack 配置，但是对于 postcss 的配置可能会导致我们的一些默认配置被覆盖掉

可以讲一下你的诉求，你可以通过 build scripts 插件来自定义 webpack 配置，但是对于 postcss 的配置可能会导致我们的一些默认配置被覆盖掉

感谢回复！我希望通过插件的方式进行配置，使用 postcss 的 autoprefix 功能，我使用 webpack-chain 的方式配置会报错：

module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.module
      .rule('postcss')
      .test(/\.css$/)
      .use('style-loader').loader('style-loader').end()
      .use('css-loader').loader('css-loader').end()
      .use('postcss-loader').loader('postcss-loader')
      .options({
        plugins: [require('autoprefixer')]
      })
  });
}
不知否提供一下配置样例。

**Comment by Mayandev** [comment]
> 可以讲一下你的诉求，你可以通过 build scripts 插件来自定义 webpack 配置，但是对于 postcss 的配置可能会导致我们的一些默认配置被覆盖掉

感谢回复！我希望通过插件的方式进行配置，使用 postcss 的 autoprefix 功能，我使用 webpack-chain 的方式配置会报错：

```javascript
module.exports = ({ onGetWebpackConfig }) => {
onGetWebpackConfig((config) => {
config.module
.rule('postcss')
.test(/.css$/)
.use('style-loader').loader('style-loader').end()
.use('css-loader').loader('css-loader').end()
.use('postcss-loader').loader('postcss-loader')
.options({
plugins: [require('autoprefixer')]
})
});
}
```
不知否提供一下配置样例。

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/80608243-0fd46b80-8a69-11ea-910a-dfa559d66e17.png)
目前已有的默认配置是这样的，如果你一定要覆盖官方的配置，目前需要给 css 的配置最后再加上 `stylesheet-loader` 这个 loader，即：
```js
module.exports = ({ onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.module
      .rule('postcss')
      .test(/.css$/)
      .use('css')
      .loader(require.resolve('stylesheet-loader'))
      .options({
        transformDescendantCombinator: true,
      })
      .end()
      .use('style-loader')
      .loader('style-loader')
      .end()
      .use('css-loader')
      .loader('css-loader')
      .end()
      .use('postcss-loader')
      .loader('postcss-loader')
      .options({
        plugins: [require('autoprefixer')],
      })
      .end();
  });
};
```
