### ISSUE TITLE
页面报错Cannot read property '_mountID' of null[BUG]

### ISSUE THREAD

**Issue by doubleYoYo** [alibaba/rax#1861]
**Describe the bug**
页面偶尔会出现Cannot read property '_mountID' of null报错，不是100%复现，查看代码应该这里抛出的异常，在这里异常之后会导致页面的其他地方set变量无法重新render

![image](https://user-images.githubusercontent.com/13435939/80679968-836d8b80-8af0-11ea-9522-24284b551de8.png)

**Comment by yuanyan** [comment]
可以提供下复现代码

**Comment by yongningfu** [comment]
这个问题抽象来说就是，一个需要更新的组件被卸载了，在一些数据驱动的高阶组件中，可能会比较容易复现
