### ISSUE TITLE
rax-slider@0.2.7 dependence not declared

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#187]
bug：

`universal-panresponder` is required in  
`https://unpkg.com/rax-slider@0.2.7/src/slider.web.js`  
but NOT decleared in 
`http://unpkg.com/rax-slider@0.2.7/package.json`

which causes compilation failure.   

Do we need a tool to check every packages' dependencies before publishing to npm? @yacheng

**Comment by wssgcg1213** [comment]
tool like this:  
![image](https://cloud.githubusercontent.com/assets/3922719/24324057/334afef6-11ba-11e7-8039-b97e9c3770be.png)  
https://github.com/depcheck/depcheck

**Comment by yuanyan** [comment]
Has been checked with eslint import plugin: https://github.com/alibaba/rax/blob/master/.eslintrc.js#L166

**Comment by wssgcg1213** [comment]
👍🏻
