### ISSUE TITLE
[Question]: JSX+ slot scope 在 typescript 中存在不可绕过的编译问题

### ISSUE THREAD

**Issue by SoloJiang** [alibaba/rax#1877]
```tsx
<View x-slot:header="props"></View>
```
以上用法在 ts 项目中会存在无法绕过的编译错误。

**Comment by imsobear** [comment]
具体的编译错误是？

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/81939146-860bcd00-9628-11ea-84b3-30a2f4dfeba3.png)

**Comment by SoloJiang** [comment]
![image](https://user-images.githubusercontent.com/14757289/81939184-9459e900-9628-11ea-9eb0-95b538a5bcb1.png)

**Comment by xfantasy** [comment]
我也遇到了，实际代码是：
```
<NavigationBar title={"我的钱包"} optionTitle={'账单'}>
   <View x-slot:titleExtraAddons><Text>123</Text></View>
</NavigationBar>
```

编译时报错：
![image](https://user-images.githubusercontent.com/535222/88007902-9026dc00-cb41-11ea-825f-e275e6101a83.png)

**Comment by muzea** [comment]
TS 中已经有相关 PR 在做这个事情

[Support xml namespaces in JSX](https://github.com/microsoft/TypeScript/issues/11833)
[Support xml namespace prefix for JSX elements and attributes](https://github.com/microsoft/TypeScript/pull/37421)

**Comment by SoloJiang** [comment]
新版本 rax-app 已经升级到 TypeScript 4.x，支持了 JSX Plus 和 TypeScript 一起使用，针对 `x-for` 场景，需要做如下变更：

![image](https://user-images.githubusercontent.com/14757289/113677109-ca480600-96ef-11eb-82ad-0ecd8356b1ef.png)

**Comment by waylon-gmail** [comment]
![Screen Shot 2021-06-22 at 2 19 58 PM](https://user-images.githubusercontent.com/51048705/122873900-ef4e2b80-d364-11eb-9371-8d3afdddd156.png)
