### ISSUE TITLE
[BUG] PWA 产品页二维码不可用

### ISSUE THREAD

**Issue by zancheng** [alibaba/rax#1882]
**Describe the bug**
https://rax.js.org/pwa 页面优化的扫码体验链接不能打开

**To Reproduce**
1. 打开[https://rax.js.org/pwa](https://rax.js.org/pwa)
2. 扫描“页面优化”的二维码
3. 链接不能打开

 (please complete the following information)
 - Device: [iPhone6s]
 - OS: [iOS]

**Comment by fyangstudio** [comment]
感谢反馈，我们会重新发布页面
