### ISSUE TITLE
[BUG] vscode插件创建新项目没反应

### ISSUE THREAD

**Issue by mcc-stack** [alibaba/rax#1892]
Windows下,rax的vscode插件创建新项目没反应

**Comment by fyangstudio** [comment]
VSCode 中有错误提示吗？

**Comment by mcc-stack** [comment]
> VSCode 中有错误提示吗？

没,就一点反应都没有

**Comment by mcc-stack** [comment]
> VSCode 中有错误提示吗？

就是按照官网的教程,选择好配置最后一步点击创建工程之后,并没有创建

**Comment by mcc-stack** [comment]
> VSCode 中有错误提示吗？

![Uploading 83640233...]()
那个rax-tag-helper扩展出问题了，然后我创建的项目路径出了问题

**Comment by mcc-stack** [comment]
> VSCode 中有错误提示吗？

![C8W $)SNP{F~R(Z01% WG)1](https://user-images.githubusercontent.com/54461051/83641135-b1f2f080-a5df-11ea-8ac8-7908fd605591.png)
vscode-rax-tag-helper扩展激活失败，然后我创建的项目的路径出问题了

**Comment by fyangstudio** [comment]
windows 系统本地复现了类似的问题，uninstall Create Rax 再重新 install 下，可以正常创建项目。

**Comment by mcc-stack** [comment]
> windows 系统本地复现了类似的问题，uninstall Create Rax 再重新 install 下，可以正常创建项目。

试了,还是没用
