### ISSUE TITLE
[Feature]Whether to consider supporting React DevTools v4？

### ISSUE THREAD

**Issue by 7213** [alibaba/rax#1895]
**Is your feature request related to a problem? Please describe.**
Debugging of React Hook in v4 is fully supported

**Comment by SoloJiang** [comment]
We will consider the workload, and we might develop a new one for Rax.

**Comment by andycall** [comment]
React devtools v4 is currenting based on React's fiber API which is not supported by Rax.
so it's not possible to compact with React devtools v4 with Rax 1.x version.

Maybe we will support fiber API in the future.
