### ISSUE TITLE
[tool]基于 React 的组件可视化拖拽页面搭建代码生成工具与Rax很契合

### ISSUE THREAD

**Issue by anye931123** [alibaba/rax#1896]
基于 React 的组件可视化拖拽页面搭建代码生成工具,组件自由拖拽，dom实时追踪，组件无限制嵌套组合，不添加多余节点，所见即所得，可完美还原UI设计，多平台支持，代码生成，实时预览，核心功能已抽取为单独组件不依赖任何组件库，并支持任何组件库的拖拽搭建页面，项目开源，欢迎有兴趣的一起开发，与Rax非常契合。
https://github.com/anye931123/react-visual-editor

**Comment by andycall** [comment]
少侠我看你骨骼惊奇，是否有兴趣加入阿里巴巴淘系技术部，这边有非常多可视化搭建的可以做，想必能实现更高的人生价值。

感兴趣可以发简历至：chenghuai.dtc@alibaba-inc.com

**Comment by anye931123** [comment]
你们卡学历，算了，拉我加入组织吧，我开发个 rax-visual-editor
