### ISSUE TITLE
[BUG] Crash when hydrate to a element contains textNode

### ISSUE THREAD

**Issue by xcodebuild** [alibaba/rax#1899]
**To Reproduce**
https://codesandbox.io/s/fervent-night-u4eor?file=/src/index.js

**Expected behavior**
Render component

**Screenshots**
![image](https://user-images.githubusercontent.com/5436704/83125929-bb291c80-a10a-11ea-9bbd-f96a68b0182a.png)

Additional, remove the textNode `1234` then it works well

**Comment by chenjun1011** [comment]
fixed in https://github.com/alibaba/rax/pull/1888
