### ISSUE TITLE
[rax-slider] 组件web实现上 unmount 没有 clearInterval 导致报错

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#191]
https://github.com/alibaba/rax/blame/master/packages/rax-slider/src/slider.web.js#L50

版本 0.2.9

**Comment by yuanyan** [comment]
fixed in https://github.com/alibaba/rax/blob/master/packages/rax-slider/src/slider.web.js#L213

**Comment by wssgcg1213** [comment]
not published yet?
