### ISSUE TITLE
[BUG]Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by NealST** [alibaba/rax#1913]
rax-redux的PropTypes文件引用了rax，并使用了rax.PropTyles的属性，但是rax下面并没有这个属性，导致了undefine的报错。报错原因如下图所示：

![image](https://user-images.githubusercontent.com/17682407/84246019-8f5d5c00-ab38-11ea-8a06-f0b56c1353cb.png)

![image](https://user-images.githubusercontent.com/17682407/84246144-bb78dd00-ab38-11ea-962e-8ab907390866.png)

**Comment by SoloJiang** [comment]
确认一下 rax-redux 1.0.0-beta.0 一直没有发正式版，正式版里应该没有这个问题
