### ISSUE TITLE
Kraken比RN、Weex优势在哪里？

### ISSUE THREAD

**Issue by challengingcheng** [alibaba/rax#1920]
Kraken基于JS和Dart通信实现动态化，脚本和渲染运行在两个环境下。Kraken那么不就和RN、Weex一样了吗？ Flutter性能高不就是因为脚本和渲染在一个环境下，不用Bridge通信所以快的吗？

**Comment by wssgcg1213** [comment]
从渲染管线的角度看, Kraken 应该是和浏览器像, 而不是 RN/Weex  

自绘引擎首要解决的是双端不一致问题, 这在浏览器上对前端开发者是一贯的, 而 RN/Weex 不是  

Kraken 实现的是 W3C 标准的完全子集, 而不是类似 DOM API 集合. RN 是很难做到 Write Once, Run Everywhere 的; Weex 号称可以做到, 事实上对开发者的要求会比较高

通信的问题, 我没研究过 RN 的通信实现, Weex 的渲染指令是异步发送的, 而 Kraken 使用的 Dart FFI 是可以做到双向同步调用, 而且单次通信最小可以控制在 0.002ms 左右, 这对于 60fps(16.67ms) 的硬件流畅要求完全够用.

**Comment by chenzefeng09** [comment]
kraken会开源吗？如果DSL层想换成Vue，成本高吗？

**Comment by andycall** [comment]
未来会开源

**Comment by huoxiangdong** [comment]
会不会今年双11后开源呢

**Comment by luwuer** [comment]
> 从渲染管线的角度看, Kraken 应该是和浏览器像, 而不是 RN/Weex
> 
> 自绘引擎首要解决的是双端不一致问题, 这在浏览器上对前端开发者是一贯的, 而 RN/Weex 不是
> 
> Kraken 实现的是 W3C 标准的完全子集, 而不是类似 DOM API 集合. RN 是很难做到 Write Once, Run Everywhere 的; Weex 号称可以做到, 事实上对开发者的要求会比较高
> 
> 通信的问题, 我没研究过 RN 的通信实现, Weex 的渲染指令是异步发送的, 而 Kraken 使用的 Dart FFI 是可以做到双向同步调用, 而且单次通信最小可以控制在 0.002ms 左右, 这对于 60fps(16.67ms) 的硬件流畅要求完全够用.

0.002ms 这个数据是否准确，同事在4核11G的机器上测试过，FFI 只能达到 0.05ms，性能远低于 Native Extension

**Comment by andycall** [comment]
首次比较慢，后面就飞快了

**Comment by NicholasHwang** [comment]
> 从渲染管线的角度看, Kraken 应该是和浏览器像, 而不是 RN/Weex
> 
> 自绘引擎首要解决的是双端不一致问题, 这在浏览器上对前端开发者是一贯的, 而 RN/Weex 不是
> 
> Kraken 实现的是 W3C 标准的完全子集, 而不是类似 DOM API 集合. RN 是很难做到 Write Once, Run Everywhere 的; Weex 号称可以做到, 事实上对开发者的要求会比较高
> 
> 通信的问题, 我没研究过 RN 的通信实现, Weex 的渲染指令是异步发送的, 而 Kraken 使用的 Dart FFI 是可以做到双向同步调用, 而且单次通信最小可以控制在 0.002ms 左右, 这对于 60fps(16.67ms) 的硬件流畅要求完全够用.

请问下 Dart FFI是怎么做到双向同步调用

**Comment by andycall** [comment]
这是个专利，需要等开源之后才能公开

**Comment by challengingcheng** [comment]
> Dart FFI 是可以做到双向同步调用

RN和Weex用的渲染引擎不都是Yoga吗，渲染引擎不存在双端不一致的问题吧。

双向同步调用是蛮期待的。

**Comment by xmsz** [comment]
期待开源 现在公司做小程序端方案是 Vue + kbone（仅需模拟DOM API），但被局限在了web端没办法覆盖整个移动端应用。所以在找同样的解决方案

因为团队人员和公司规模原有，UI框架只能选择Vue

需求
- 希望是框架去适应现有代码，而不是完完全全依赖某个框架再去写，所以想要实现的就是无关上层UI框架来实现多端。

尝试
- Weex要求优点高
- Chameleon和其他的也是没办法兼容现有代码且不比Weex可靠，所以放弃
- Uni-APP这种东西完全不考虑...


所以期待开源，这样就可以尝试用去做vue的胶水层

**Comment by jerryniepan** [comment]
Kraken 支持热修复吗

**Comment by yuu2lee4** [comment]
什么时候开源

**Comment by fengnudexiaoniao** [comment]
> 从渲染管线的角度看, Kraken 应该是和浏览器像, 而不是 RN/Weex
> 
> 自绘引擎首要解决的是双端不一致问题, 这在浏览器上对前端开发者是一贯的, 而 RN/Weex 不是
> 
> Kraken 实现的是 W3C 标准的完全子集, 而不是类似 DOM API 集合. RN 是很难做到 Write Once, Run Everywhere 的; Weex 号称可以做到, 事实上对开发者的要求会比较高
> 
> 通信的问题, 我没研究过 RN 的通信实现, Weex 的渲染指令是异步发送的, 而 Kraken 使用的 Dart FFI 是可以做到双向同步调用, 而且单次通信最小可以控制在 0.002ms 左右, 这对于 60fps(16.67ms) 的硬件流畅要求完全够用.

不传输数据的话，调用成本确实很低，但耗时主要是在字符转byte上和json的编解码上，这块有什么好的建议不？

**Comment by andycall** [comment]
更新一下，Kraken 在 JS 与 Dart 之间的通信数据格式不是 json，而是一种二进制格式。Dart 的字符串和 JS 的字符串都是 UTF-16 编码，中间通信不需要进行转码操作, 因此要比过去直接传 json 字符串要快得多。

**Comment by andycall** [comment]
> 什么时候开源

计划是月底

**Comment by fengnudexiaoniao** [comment]
> 更新一下，Kraken 在 JS 与 Dart 之间的通信数据格式不是 json，而是一种二进制格式。Dart 的字符串和 JS 的字符串都是 UTF-16 编码，中间通信不需要进行转码操作, 因此要比过去直接传 json 字符串要快得多。

牛，那确实应该很高效，期待你们开源

**Comment by fengnudexiaoniao** [comment]
> 更新一下，Kraken 在 JS 与 Dart 之间的通信数据格式不是 json，而是一种二进制格式。Dart 的字符串和 JS 的字符串都是 UTF-16 编码，中间通信不需要进行转码操作, 因此要比过去直接传 json 字符串要快得多。

大佬再请教一下，dart再调jscore引擎的时候，给他传递的是字符串，这时候，我们是把所有数据都合并在一起传给jscore（所有数据合并在一起，可以减少jscore调用次数，但是需要解析，这时候也会耗时），还是一个个数据段，多次调用jscore来传它呢？

**Comment by chenzefeng09** [comment]
> > 什么时候开源
> 
> 计划是月底

赞啊，第一时间跟进，看看怎么接vue 😂

**Comment by chenzefeng09** [comment]
> > 什么时候开源
> 
> 计划是月底

目前开源节奏是怎么安排的呢？ @andycall

**Comment by 651016236** [comment]
3月底可能开源吗？

**Comment by andycall** [comment]
之前被一些事情耽搁了一阵子，3月底一定开

**Comment by aolsx** [comment]
快点开吧，早就关注了。

**Comment by xmsz** [comment]
21号啦！！！！

**Comment by chenzefeng09** [comment]
https://github.com/openkraken/kraken

**Comment by imsobear** [comment]
Kraken 已开源，欢迎移步 Kraken 仓库讨论：https://github.com/openkraken/kraken
