### ISSUE TITLE
使用Rax的slider和image可以使用百分比表示宽度吗[Question]

### ISSUE THREAD

**Issue by BrunaDeLafel** [alibaba/rax#1924]
`
<Slider className="Scanner" width="600" height="200" autoplay={true}>
                <View className="scanner-items" width="600" height="200" key={props.uriArr[0]}>
                    <Image source={{uri: props.uriArr[0]}} style={{width:100,height:100}}/>
                </View>
</Slider>
`

**Comment by fyangstudio** [comment]
可以用我们推荐的 rpx 变量 http://rax.alibaba-inc.com/docs/guide/style#rpx-%E5%8D%95%E4%BD%8D
