### ISSUE TITLE
[rax-player] style 传入 undefined 的时候报错

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#193]
![image](https://cloud.githubusercontent.com/assets/3922719/24390473/b4f4120a-13bb-11e7-9887-696aa0533c8b.png)

复现地址：https://alibaba.github.io/rax/playground/65203435-73c6-41ab-b32d-aee5ac7a982f

**Comment by yacheng** [comment]
player 是需要指定宽高的，我增加一下默认宽高的支持

**Comment by wssgcg1213** [comment]
嗯，style 不传入值的时候就不会报错。 可以考虑 console.warn 提示？
