### ISSUE TITLE
Kraken怎么打包apk

### ISSUE THREAD

**Issue by huoxiangdong** [alibaba/rax#1930]
我在文档里没有看到怎么构建打包啊，构建完了，怎么打包成apk呢?

**Comment by andycall** [comment]
目前 Kraken 还仅面向阿里集团内部使用， 还没有对外发布支持 iOS 和 Android 的 SDK。

**Comment by Tonyangl** [comment]
> 目前 Kraken 还仅面向阿里集团内部使用， 还没有对外发布支持 iOS 和 Android 的 SDK。
Kraken cli linux win 什么时候支持，
Kraken 什么时候可以对外使用，希望能在下个项目中使用。

**Comment by Tonyangl** [comment]
> 目前 Kraken 还仅面向阿里集团内部使用， 还没有对外发布支持 iOS 和 Android 的 SDK。

@andycall 
Kraken cli linux win 什么时候支持，
Kraken 什么时候可以对外使用，希望能在下个项目中使用。

**Comment by andycall** [comment]
要等内部应用成熟之后才会考虑对外，敬请期待

**Comment by xmsz** [comment]
> 要等内部应用成熟之后才会考虑对外，敬请期待

有没有可能有内测版 确实想尽快尝鲜一下
