### ISSUE TITLE
多页应用路由跳转问题[Question]

### ISSUE THREAD

**Issue by AaronW-BE** [alibaba/rax#1932]
多页应用中使用默认路由跳转报错``` Cannot read property 'push' of undefined```，使用```a```标签的```href```可以跳转
```jsx
<a href="/login">Login</a>
<Text onClick={() => history.push('/login')}>Login</Text>
```
是否是在多页应用中需要额外配置？
谢谢

**Comment by SoloJiang** [comment]
目前在多页应用中，没有注入 `history`，因为多页场景下，现在应该使用的是 `window.history` 这个和 spa 中还是有一定区别的，我们会在接下来推出的 Web Framework App 中去统一相关的概念，并且给出能够用法抹平的方式

**Comment by yrcs** [comment]
> 目前在多页应用中，没有注入 `history`，因为多页场景下，现在应该使用的是 `window.history` 这个和 spa 中还是有一定区别的，我们会在接下来推出的 Web Framework App 中去统一相关的概念，并且给出能够用法抹平的方式

一年过去了，现在MPA模式下仍然不能使用history.push进行路由跳转
