### ISSUE TITLE
[BUG] findDOMNode 无法获取 render 返回多个 element 的组件的 dom 元素

### ISSUE THREAD

**Issue by yinhangfeng** [alibaba/rax#1934]
**To Reproduce**
```javascript
class FindDOMNodeBUG extends Component {
  render() {
    return (
      <Fragment>
        <div>div1</div>
        <div>div2</div>
      </Fragment>
    );
  }
}

render(<FindDOMNodeBUG ref={ref => {
  if (ref) {
    console.log(findDOMNode(ref));
    // null
   }
}/>);
```

**Expected behavior**
跟 react 一样，返回 dom 元素数组

 (please complete the following information)
 - Device: Mac
 - OS: Mac
 - Browser chrome
 - Rax Version 1.1.3

**Additional context**
rax 1.1.2 版本是可以的
顺便说一下，上面例子在 render 的最顶层给组件设置 ref 是有问题的
https://github.com/alibaba/rax/issues/1904

**Comment by SoloJiang** [comment]
上面的 demo 在 react 上的返回结果不是一个数组，并且 React 目前已经推荐直接使用 `ref` 来获取 dom 元素：
https://codesandbox.io/s/laughing-water-zb43k?fontsize=14&hidenavigation=1&theme=dark
从 React 实现上来看也没有返回数组相关的逻辑：https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOM.js#L224
