### ISSUE TITLE
怎么引用本地图片呀[Question]

### ISSUE THREAD

**Issue by AaronW-BE** [alibaba/rax#1946]
使用```import```或```require```都没办法引用本地图片

**Comment by SoloJiang** [comment]
静态资源放到 `src/public` 下

**Comment by AaronW-BE** [comment]
> 静态资源放到 `src/public` 下

已经放在```src/public```下了，找到原因了，```import```导入图片后是一个对象，不能直接用于原生```img```标签，使用其```uri```属性，也可用于```rax-image```中的```source```
