### ISSUE TITLE
[BUG] 小程序运行时方案使用 ReactDOM 渲染时提示 Cannot read property 'createElement' of null

### ISSUE THREAD

**Issue by chenbin92** [alibaba/rax#1970]
## 问题

小程序方案 miniapp-renderer 使用 ReactDOM 渲染时报错，错误截图如下：

![image](https://user-images.githubusercontent.com/3995814/89117153-340f7080-d4ce-11ea-8835-1b407c1aeda2.png)

## 排查

错误代码：

```ts
const canUseDOM: boolean = !!(
  typeof window !== 'undefined' &&
  typeof window.document !== 'undefined' &&
  typeof window.document.createElement !== 'undefined'
);
```

初步排查问题原因在于 [miniapp-renderer](https://github.com/alibaba/rax/blob/master/packages/miniapp-render/src/document.js#L170) 处理逻辑和 react-dom 的 [canUseDOM](https://github.com/facebook/react/blob/1078029af6ecf9f85c5235e4323b853b78d86da0/packages/react-interactions/events/src/dom/DeprecatedFocus.js#L88) 判断逻辑冲突

```diff
  get defaultView() {
-    return cache.getWindow() || null;
+    return cache.getWindow() || undefined;
  }
```

## 预期

错误修复，支持使用 ReactDOM 正常渲染。

**Comment by chaselss02** [comment]
@chenbin92 是怎么解决的，我怎么还是用不了document
![image](https://user-images.githubusercontent.com/43427635/97535565-ca343380-19f6-11eb-96c3-fdd2e5a75d5a.png)
