### ISSUE TITLE
[rax-gotop] name的默认值并不是‘顶部’

### ISSUE THREAD

**Issue by miaojing** [alibaba/rax#198]
* [rax-gotop] name的默认值并不是如文档中描述的“顶部”，而是"click"
* demo中是click，demo建议默认按视觉规范的样式，减少业务使用成本。

**Comment by wssgcg1213** [comment]
- name 的默认值应该是 `Top`，这个会在文档中做一下修正

**Comment by wssgcg1213** [comment]
视觉规范的问题由 @yacheng 负责跟进
