### ISSUE TITLE
[Question]运行时不支持alias吗？

### ISSUE THREAD

**Issue by DroganC** [alibaba/rax#1983]
Please describe the problem you meet.
运行时不支持alias吗？

**Comment by DroganC** [comment]
![image](https://user-images.githubusercontent.com/32896700/90089637-7483af80-dd54-11ea-97cc-301fb732db6c.png)
![image](https://user-images.githubusercontent.com/32896700/90089653-7cdbea80-dd54-11ea-91a9-b50d15161dd1.png)

**Comment by HadiChen** [comment]
在你的**tsconfig.json**加上paths的配置
`{
   "compilerOptions": {
        "paths": [
            "@components/*":  [
                   "./src/components/*"
             ]
         ]
   }
}`
![image](https://user-images.githubusercontent.com/11555571/92987483-4e893080-f4f5-11ea-8c85-da1b81db748a.png)
