### ISSUE TITLE
[Question]小程序支持分包

### ISSUE THREAD

**Issue by DroganC** [alibaba/rax#1984]
Please describe the problem you meet.
微信小程序如何分包

**Comment by SoloJiang** [comment]
即将支持，先明确一下是否存在体积问题，发布前要 `npm run build`

**Comment by Navi-1993** [comment]
2020-10-16 11:59:14，请问当前是否支持微信小程序分包？

**Comment by imsobear** [comment]
分包能力下周发布

**Comment by ChrisCindy** [comment]
已支持
