### ISSUE TITLE
[Question]npm init rax MyRax 创建项目没有weex了吗？

### ISSUE THREAD

**Issue by xusion** [alibaba/rax#2004]
? What's your project type? (Use arrow keys)
❯ App (Build universal application) 
  Component (Build universal component) 
  API (Build universal API library) 
  Plugin (Build plugin for miniapp) 

? What's your project type? App (Build universal application)
? Choose targets your project want to run? (Press <space> to select, <a> to togg
le all, <i> to invert selection)
❯◉ Web
 ◯ Alibaba MiniApp
 ◯ WeChat MiniProgram
 ◯ Kraken (Flutter)

**Comment by imsobear** [comment]
是的，需要 weex 的话在 build.json 里的 targets 字段加下 weex。
