### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ayranz** [alibaba/rax#2010]
**Describe the bug**
I am using on of Rax components "Canvas". One of the first steps is to obtain its context in order to access its functions.
That behaviour works well in H5. However, every time I try to obtain the context of my canvas it throws the following error "TypeError: undefined is not an object (evaluating 'GCanvasModule.enable')"

**To Reproduce**
1. Import canvas
2. Add one canvas to your component
3. In weex, try to obtain its context
It will trow the exception mentioned above

**Expected behavior**
When calling canvas.getContext() it should return an object that represents the state of he canvas as well as access to functions such as "fillRect" or "clearrect"

**Screenshots**
![image](https://user-images.githubusercontent.com/71080902/92735610-d5b19980-f379-11ea-8924-cebc0555735b.png)

 (please complete the following information)
 - Device: Samsung galaxy s9+
 - OS: Android
 - Browser Native, H5 works fine
 - Rax Version 1.1.0

**Additional context**
I am an internal employee. My employee number is WB611264, please do not hesitate to contact me in order to make a live demonstration. Or share more context if needed.

**Comment by SoloJiang** [comment]
Rax will not support Weex.
