### ISSUE TITLE
在tsx中如何配置jsx-plus的语法

### ISSUE THREAD

**Issue by HadiChen** [alibaba/rax#2012]
如在tsx文件中使用 **x-for** 语法，typescript一直提示报错。
![image](https://user-images.githubusercontent.com/11555571/92987339-2947f280-f4f4-11ea-9f2c-ff77c1fd4b82.png)
![image](https://user-images.githubusercontent.com/11555571/92987347-3d8bef80-f4f4-11ea-8cd2-9022db4954c6.png)
![image](https://user-images.githubusercontent.com/11555571/92987356-4da3cf00-f4f4-11ea-96a9-aaa557ba72f3.png)

**Comment by SoloJiang** [comment]
jsx+ 暂时无法和 ts 一起使用
