### ISSUE TITLE
[BUG]build-plugin-rax-pha@0.01 缺少ignoreLoader.*文件

### ISSUE THREAD

**Issue by HadiChen** [alibaba/rax#2013]
在**src/nsr/getBase.js**中有加载使用ignoreLoader文件，但包中缺少该文件。
![image](https://user-images.githubusercontent.com/11555571/92988638-ef7ce900-f4ff-11ea-9e7e-bb0551fb83c7.png)

**Comment by SoloJiang** [comment]
这个插件将会为新的 rax-app 重写
