### ISSUE TITLE
useEffect里setInterval调用setState报错

### ISSUE THREAD

**Issue by PathogenABC** [alibaba/rax#2017]
![image](https://user-images.githubusercontent.com/9835322/93963873-d6dac180-fd90-11ea-9e2c-400afcae89c5.png)

TypeError: null is not an object (evaluating 'this(INTERNAL).__isPendingForceUpdate=!0')

我看源码像是时序问题

**Comment by SoloJiang** [comment]
异步更新组件的时候需要判断组件是否已经被销毁，可以直接使用这个 https://rax.js.org/docs/api/use-mounted-state  hooks
