### ISSUE TITLE
[Question]kraken什么时候能看到？

### ISSUE THREAD

**Issue by chenzefeng09** [alibaba/rax#2026]
![image](https://user-images.githubusercontent.com/7556537/96679652-a5144500-13a6-11eb-80e8-b00a12f883fc.png)
官网上看到已经不推荐weex写原生了，那下一代的框架啥时候能看到？

**Comment by andycall** [comment]
内部 Kraken 已经从 0.1 发展到 0.5 版本，目前已经有阿里系的 App 在进行灰度试点，初步反馈首屏性能比 Weex 要快。

欢迎持续关注。
