### ISSUE TITLE
[Question]Cannot read property 'createElement' of undefined

### ISSUE THREAD

**Issue by chaselss02** [alibaba/rax#2028]
开发小程序时，没有document

Please describe the problem you meet.
![image](https://user-images.githubusercontent.com/43427635/97535031-f3a08f80-19f5-11eb-8930-c9a5246a05a4.png)
![image](https://user-images.githubusercontent.com/43427635/97535051-fbf8ca80-19f5-11eb-9de7-1c60a64df795.png)

**Comment by SoloJiang** [comment]
这是小程序什么方案
