### ISSUE TITLE
Rax + egg 下的 ssr 方案有吗

### ISSUE THREAD

**Issue by fisherw** [alibaba/rax#2029]
Please describe the problem you meet.
目前尝试使用 Rax + egg 作为 SSR 方案，但存在几个问题：
1. dev 模式下，怎么搭建 egg 进行服务端渲染调试？
2. 服务端渲染时，初始化数据逻辑一定得放在组件的 getInitialProps 方法中吗，如果我有一些只能在 nodejs 端的调用来获取数据，该如何作为服务端渲染的初始化数据?

比如：
const page = require('./build/node/about/index.js')

const initialData = nodeService.queryData();

// 此时 initailData 有办法作为服务端渲染初始数据吗？
page.render(req, res);

**Comment by SoloJiang** [comment]
最新版本的 rax-app 支持通过 `page.render(ctx, {  initialData })` 传入初始化数据
