### ISSUE TITLE
[Question]rax官方文档-状态管理中的示例代码是不是少了参数 dispatch

### ISSUE THREAD

**Issue by komagic** [alibaba/rax#2030]
官方文档中的示例代码是不是少了参数 dispatch? 函数体中的dispatch没有来源哦。
![image](https://user-images.githubusercontent.com/13415767/99023915-8cabda80-25a0-11eb-92e1-154f8a4f1a12.png)

**Comment by SoloJiang** [comment]
https://github.com/raxjs/docs/pull/45
