### ISSUE TITLE
[BUG]universal-request不能正确提交FormData

### ISSUE THREAD

**Issue by Newbit13** [alibaba/rax#2031]
**Describe the bug**
使用RAX.js提供的API ```universal-request```在POST请求且请求体为FormData时无法正确设置Content-Type

**To Reproduce**
伪代码
```
import request from 'universal-request';

let fromData = new FormData()
    fromData.append('xx', 123)
    request({
      url: "someurl",
      method: 'POST',
      data: fromData,
    }).then(function (res) {})
```
由于默认不设置Content-Type时默认为application/json，设置为multipart/form-data时却又没有boundary。

**Expected behavior**
data值为FormData实例时，Content-Type自动为multipart/form-data且带上boundary的值

**Screenshots**

**Comment by SoloJiang** [comment]
universal-request 不会把请求这件事做的很复杂，即不会添加对 `data` 类型的推导，然后自动设置 `Content-Type`。
从我的测试代码来看，表现是符合预期的，并且是带上 `boundary ` 的，示例代码如下：
```js
import request from 'universal-request';
  let fromData = new FormData();
  fromData.append('xx', 123);
  request({
    url: 'https://httpbin.org/post',
    method: 'POST',
    data: fromData,
    withCredentials: true,
    headers: {
      'Content-Type': 'multipart/form-data',
    }
  }).then(function (res) {
    console.log(res);
  });
```
universal-request 版本号为：2.2.0，代码地址 https://github.com/raxjs/universal-api/blob/master/packages/request/src/web/index.ts
issue 暂且关闭，如果依然有问题，可以贴出完整复现代码，然后 reopen 这个 issue

**Comment by Newbit13** [comment]
> ```js
> multipart/form-data
> ```

是说Request Headers中的Content-type没有boundary，有时候后端没做处理会判断不出来
![image](https://user-images.githubusercontent.com/17379717/99096596-6d996100-2611-11eb-8b21-0c941113f8da.png)
