### ISSUE TITLE
[BUG]rax-embed在微信小程序中报错

### ISSUE THREAD

**Issue by Newbit13** [alibaba/rax#2032]
**Describe the bug**
当我使用RAX提供的Embed组件并生成微信小程序时，
控制台提示```[ comp.json 文件内容错误] comp.json: ["usingComponents"]["cf210e3"]: "rax-embed\lib\wechat-miniprogram\index" 未找到```

**To Reproduce**
在默认构建的/src/pages/Home/index.jsx中写上
```
import { createElement } from 'rax';
import Embed from 'rax-embed';

export default function Home() {
  return (
    <Embed
      src={'https://baidu.com'}
    />
  );
}
```
运行npm run build后用微信开发者工具打开build文件夹下生成的小程序代码，出现
```[ comp.json 文件内容错误] comp.json: ["usingComponents"]["cf210e3"]: "rax-embed\lib\wechat-miniprogram\index" 未找到```

**Expected behavior**
在微信小程序上正确显示https://baidu.com的内容

**Screenshots**
![image](https://user-images.githubusercontent.com/17379717/99184515-5f1c8800-277e-11eb-91dd-95d13e08be58.png)

 (please complete the following information)
 - windows10
 - Rax 1.1.0
 - rax-embed 1.1.1

**Additional context**

**Comment by ChrisCindy** [comment]
@Newbit13 进入 build/wechat-miniprogram 并执行 npm install，然后通过微信 IDE 构建 npm 即可

**Comment by ChrisCindy** [comment]
目前 rax embed 组件 package.json 可能没有 miniprogram 字段从而导致构建 npm 后路径不对，明天我检查处理一下。

**Comment by Newbit13** [comment]
> @Newbit13 进入 build/wechat-miniprogram 并执行 npm install，然后通过微信 IDE 构建 npm 即可



> @Newbit13 进入 build/wechat-miniprogram 并执行 npm install，然后通过微信 IDE 构建 npm 即可

不可行，然后我将node_modules下的rax-embed移到微信小程序根目录下后，出现：
![image](https://user-images.githubusercontent.com/17379717/99185030-1070ed00-2782-11eb-9404-7b7468a21657.png)

**Comment by ChrisCindy** [comment]
rax-embed 应该走运行时的实现，此处未做兼容，本周发版修复。如果着急使用，可直接使用小程序原生 webview 组件

**Comment by wstcyx** [comment]
这个BUG解决了吗？

**Comment by ChrisCindy** [comment]
今日发版，处理中
https://github.com/raxjs/miniapp/pull/65

**Comment by ChrisCindy** [comment]
> 这个BUG解决了吗？

@wstcyx 已修复
