### ISSUE TITLE
[BUG]REOPEN universal-request不能正确提交FormData

### ISSUE THREAD

**Issue by Newbit13** [alibaba/rax#2033]
**Describe the bug**
使用universal-request提交FormData不能出现预期情况，不能在Request Headers的Content-type自动加上boundary,
截图为一个正常formdata表单提交的情况：
![image](https://user-images.githubusercontent.com/17379717/99096596-6d996100-2611-11eb-8b21-0c941113f8da.png)

使用universal-request时只能是：
![image](https://user-images.githubusercontent.com/17379717/99184724-fd5d1d80-277f-11eb-9cd2-f45b4432dea8.png)

想jquery的$.ajax函数，提交formData时不用也不建议设置Content-type

**To Reproduce**
[[BUG]universal-request不能正确提交FormData](https://github.com/alibaba/rax/issues/2031)

Request Headers中的Content-type没有boundary，有时候后端没做处理会判断不出来

**Comment by SoloJiang** [comment]
universal-request 和 jquery 所提供的请求库，定位是有区别的，universal-request 只是抹平多端的基础请求，更进一步的封装或者更复杂的场景支持需要业务自己来做

**Comment by SoloJiang** [comment]
基于上面的解释，所以 Content-Type 应该完全由使用者自己决定

**Comment by Newbit13** [comment]
> 基于上面的解释，所以 Content-Type 应该完全由使用者自己决定

这样的话，Content-Type不应该有默认值，这样使用者会更加自由点
