### ISSUE TITLE
[BUG]windows10下@kraken-project/cli不能正常安装

### ISSUE THREAD

**Issue by Newbit13** [alibaba/rax#2034]
**Describe the bug**

**To Reproduce**
在windows10终端执行```npm i @kraken-project/cli```

然后出现
> @kraken-project/cli@0.5.1 postinstall D:\yong_workplace\demo\react\testapp\node_modules\@kraken-project\cli
> node install.js

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   299  100   299    0     0    299      0  0:00:01 --:--:--  0:00:01   736
tar: Error opening archive: Unrecognized archive format
child_process.js:669
    throw err;
    ^

Error: Command failed: tar xzf D:\yong_workplace\demo\react\testapp\node_modules\@kraken-project\cli\kraken-win32-0.5.1.tar.gz -C ./build
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (D:\yong_workplace\demo\react\testapp\node_modules\@kraken-project\cli\install.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21676,
  stdout: null,
  stderr: null
}
npm WARN @ice/store@1.4.2 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN add-asset-html-webpack-plugin@3.1.3 requires a peer of html-webpack-plugin@^3.0.4 || ^4.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@7.2.2 requires a peer of react@^16.8.3 || ^17 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fork-ts-checker-webpack-plugin\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-mock\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @kraken-project/cli@0.5.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @kraken-project/cli@0.5.1 postinstall script.
**Expected behavior**
正常安装

**Screenshots**
![image](https://user-images.githubusercontent.com/17379717/99188745-9435d400-2798-11eb-9511-d123e0fa8987.png)

 (please complete the following information)
 - OS: [windows10]
 - Rax Version [1.1.0]

**Comment by andycall** [comment]
kraken-cli 不支持 windows
