### ISSUE TITLE
[Question] Kraken 的文档使用的地址是不是都是内部地址

### ISSUE THREAD

**Issue by tdida** [alibaba/rax#2035]
Please describe the problem you meet.
![image](https://user-images.githubusercontent.com/18672870/99345082-76698b80-28cc-11eb-8290-398a1ecaf632.png)
![image](https://user-images.githubusercontent.com/18672870/99345095-7bc6d600-28cc-11eb-8ab4-1977909a3beb.png)

**Comment by wssgcg1213** [comment]
Kraken 暂不提供外部使用, 谢谢关注

**Comment by tdida** [comment]
@wssgcg1213 有对外使用的时间表计划吗
