### ISSUE TITLE
Add support for Graphql

### ISSUE THREAD

**Issue by joedevgee** [alibaba/rax#2037]
**Is your feature request related to a problem? Please describe.**
I know some teams inside Alibaba is already using Graphql. Is it possible to integrate a Graphql client in Rax?

**Describe the solution you'd like**
A graphql integrated into Rax

**Describe alternatives you've considered**
Something like Apollo Graphql

**Additional context**

**Comment by SoloJiang** [comment]
Something sounds different ~ But now, we haven't planned to do that yet.
