### ISSUE TITLE
[Question]监控埋点和质量控制相关的能力现在有吗？

### ISSUE THREAD

**Issue by jsaddnf** [alibaba/rax#2038]
组件很棒！
看了一下官方文档，似乎没有找到监控和质量相关的能力。
作为类似基础基建的角色，相关的监控和质量是十分关键的。
想问一下是这部分没有开源吗？还是这部分能力是用其他外部的组件实现的？
如果是没有开源未来有开源打算吗？

**Comment by SoloJiang** [comment]
- 监控埋点这块可以看下社区的一些方案，比如谷歌的监控方案或者百度的站长工具等，我们自身在内部未来会通过插件的形式来支持这一块，通过插件可以在应用或者页面的生命周期里做拦截，然后达到监控的目的
- 质量这块，我们会通过 [iceworks](https://ice.work/docs/iceworks/about) 来做代码规范提示，以及代码健康度检查

**Comment by jsaddnf** [comment]
感谢回复！
请问一下代码健康度检查有相关文档吗？找了一圈没找到。

**Comment by fyangstudio** [comment]
https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks

可以安装下这个 VS Code 插件，执行 scan 命令
