### ISSUE TITLE
[Feature]希望 rax-app 3.0 可以支持文件结构嵌套的页面，形如 pages/a/b/index.jsx

### ISSUE THREAD

**Issue by kucinl** [alibaba/rax#2045]
![image](https://user-images.githubusercontent.com/15089544/100608110-eb19dc80-3346-11eb-879c-6842a4485173.png)
类似于上图中的结构，在 rax-app 版本：3.0.9 中，address-manage/address-edit/address-edit 不会在 .rax 中生成对应的文件

**Comment by SoloJiang** [comment]
目前不支持嵌套路由，要看具体场景，比如是在 spa 还是 mpa，以及只是源码结构需要这样放，还是最后产物的路由结构需要是 /address-manage/address-edit

**Comment by kucinl** [comment]
是 spa；希望是源码结构和路由结构都能支持；但目前的主要诉求是 源码结构能够支持，因为现有许多页面已经是这个结构，拍平有一定成本和风险，且页面文件不能按模块分布聚拢的话，也不便于管理

**Comment by SoloJiang** [comment]
预期 1 月份支持这个功能

**Comment by SoloJiang** [comment]
目前已经可以使用这种结构
