### ISSUE TITLE
[Question]是否会同步kbone的更新？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2047]
打算从kbone的方案迁移到rax
原来用kbone主要是因为运行时方案更加的『合理』，成本低开发效率高，除了性能问题其他都极度的好。
但是kbone只兼容web端，小程序端仅仅兼容微信小程序和勉强兼容QQ小程序，其他都不兼容。如果要自己在去扩展编译然后兼容，那有点得不偿失，不如直接换个方案一劳永逸。当然也不支持App端，毕竟kbone只是一种专注微信小程序的方案，并不是全端

而且现在需求虽然还没到App端，但是可能要扩展到其他平台，那么kbone就不再适用了

然后之前用过Taro，就是能用但是写得不好，对于强迫症来说非常的不友好，坑更多，毕竟技术就摆在那。相当于比kbone只是多了兼容更多小程序平台而已。

所以现在把希望寄托在rax上，但是有几个问题

1. 会和kbone同步更新吗？
因为kbone那边也还没有到已经完善的地方（毕竟用的人少），所以一些特性还在持续更新。那么Rax会和kbone同步更新，还是自己维护一个相关的包，如果不持续更新的话有什么备用方案。

2. 目前是仅有小程序支持运行时方案吗？
其他端web端 App端(Flutter)支持吗？如果要兼容所有平台是不是只能写编译时方案（主要是小程序的JSX限制太多）。
如果现在不支持，以后会支持吗？还是说推荐直接用编译时的写法？

3. 什么时候支持其他平台小程序？
还有百度小程序、支付宝小程序、头条小程序、快手小程序等
大概什么节点会兼容，或者有没有其他方法临时兼容，不然还不是不满足需求

**Comment by ChrisCindy** [comment]
@xmsz 回答一下：
1. Rax 小程序运行时方案从 kbone 1.0 fork 出来后一直是独立在发展，二者的发展理念和侧重点已经产生了比较大的区别，同时，由于 kbone 性能略差，Rax 经历数次重构后技术方案已经与 kbone 不太一样。因此 Rax 不会去定期同步 kbone 的更新。但是我们是有在关注 kbone 的发展的。kbone 站在微信官方产品的角度，与其他开发者天然存在着一些信息沟通上的优势，其运用到的一些新的特性 Rax 是会借鉴的。同时，Rax 自身由于在阿里较高的使用量也在驱动着 Rax 进行迭代，保持持续的更新。

2. 所谓的运行时方案其实只针对小程序端，在其他端并没有编译时、运行时的区分，或者说其他端都是『运行时』。Rax 的理念是『一次开发，多端运行』，对用户来说，无论是用编译时方案还是运行时方案开发小程序，同样的代码都可以构建出 web、weex、Flutter（即 Kraken，开发中） 的应用。

3. Rax 目前已经支持阿里系小程序（包括支付宝/钉钉/淘宝小程序）和微信小程序，其他的视用户需求而定是否支持。

**Comment by xmsz** [comment]
@ChrisCindy 
1. 明白了 ，那大概与kbone性能差多少，因为我们现在小程序功能模块有点多，且有一些长列表之类的性能场景（使用原生小程序组件解决但是编写、配置和维护都比较麻烦）。用kbone的时候卡顿几率太高。而且本来用jsx写，后来用Vue的template重写后才解决问题。
2. 明白了，那默认还是采用运行时方案好
3. 因为我们小程序主要是做社交或者工具类，所以QQ、头条、快手之类这些是主战场。毕竟微信和阿里不适合。所以很需要其他平台的支持。当然和我们一样方向的开发团队很多，不过因为没有其他工具，大部分都是使用Taro。如果能支持，应该可以抢一些用户过来

**Comment by ChrisCindy** [comment]
@xmsz 
1. 从我们内部做的性能测试结果来看，Rax/Remax/Taro 性能处于同一水准，Kbone 与上述三个是存在不小的性能差距的。当然以上是基于 Kbone 1.x 版本，可能现在是有提升了的。
2. 下一步我们有计划做出更开放的能力，帮助用户能更好地拓展到其他小程序端

**Comment by xmsz** [comment]
@ChrisCindy 

有没有什么产品开发计划表可以追踪看。
现在我们团队就等着如果Rax适配其他平台了，就马上迁过来

**Comment by ChrisCindy** [comment]
> @ChrisCindy
> 
> 有没有什么产品开发计划表可以追踪看。
> 现在我们团队就等着如果Rax适配其他平台了，就马上迁过来

@xmsz 目前小程序在迭代支持分包加载，该需求支持后就会来处理关于适配的问题。后续我们会把产品开发计划同步在 github 上。可以关注一下 github.com/raxjs/miniapp 仓库
