### ISSUE TITLE
[Question]rax-app里没有 IStoreModels, IStoreDispatch, IStoreRootState

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2049]
第一个问题

https://rax.js.org/docs/guide/store

```
import { createStore, IStoreModels, IStoreDispatch, IStoreRootState } from 'rax-app';
```

rax-app里并没有这些类型，或者说`.rax/index.ts`里没有导出这些内容

要import `.rax/types`  或者 `.rax/store/types` 才有

-----

第二个问题
ModelConfig的reducers类型，为什么是联合类型，是为了兼容更多情况吗？
```
  reducers?: ModelReducers<S> | ConfigReducers; 
```
因为这种情况下，类型最终会变成any
![image](https://user-images.githubusercontent.com/5879146/101452287-70654880-3968-11eb-9fdf-3847584128d3.png)
如果只指定一种类型就没有问题

----

第三个问题 能否有约束model的类型
如果是直接
```
const UserStore: ModelConfig<IState> 

```
那里面effects的类型就无法通过

如果不能约束的话，那写的时候还要多写很多类型，而且容易写错

----- 
第四个问题，按照文档写的根本通不过类型检查
![image](https://user-images.githubusercontent.com/5879146/101452799-406a7500-3969-11eb-91ec-723a1b94db25.png)

-----

第五个问题 文档里API部分为什么没有useModel的详细说明，如果没看上面的内容很容易忽略掉

**Comment by SoloJiang** [comment]
第一个问题最新版的 rax-app 已经修复，后面的问题感觉没有表述清楚，可以贴出实际代码更详细的表达一下

**Comment by guoguo0202** [comment]
使用npm init rax

import { createStore } from 'rax-app';

提示模块“"../.rax"”没有导出的成员“createStore”;

"rax": "^1.1.0",
"rax-app": "^3.0.0",

**Comment by SoloJiang** [comment]
> 使用npm init rax
> 
> import { createStore } from 'rax-app';
> 
> 提示模块“"../.rax"”没有导出的成员“createStore”;
> 
> "rax": "^1.1.0",
> "rax-app": "^3.0.0",

npm start 之后提示就会消失
