### ISSUE TITLE
建议小程序支持百度小程序[Feature]

### ISSUE THREAD

**Issue by thisTom** [alibaba/rax#2050]
**建议支持百度小程序**

现在主流小程序多端开发框架都支持百度小程序。百度小程序用户量大，而且互联网业务为了更好的做百度SEO，大多会有开发百度小程序的需求，开启WEB化后对SEO提升效果很明显。如果Rax支持，我会考虑下个框架选用Rax

**Comment by xmsz** [comment]
支持 希望支持其他平台小程序 现在越来越多人了解到Rax.js 但是还有几个比较基础的需求没有解决

- [ ] 支持分包
- [ ] 支持多平台构建（百度和QQ应该是最需要优先的）

虽然Rax是阿里生态，不过就普通公司来说，最普遍的场景还是微信小程序 > 百度小程序 > QQ小程序 > 快应用/阿里
所以现在的Rax对于普通人来说就相当于仅支持了微信小程序而已

**Comment by ChrisCindy** [comment]
分包加载能力目前正在开发中，多端支持也已经排上日程。后续可以关注下

**Comment by ChrisCindy** [comment]
分包加载能力已开发完毕进入测试阶段，预计下周上线

**Comment by ChrisCindy** [comment]
https://github.com/raxjs/miniapp/milestone/1

**Comment by SoloJiang** [comment]
项目构建已经支持，基础组件这周发布，可以先使用 div 之类的标签试用

**Comment by ChrisCindy** [comment]
百度、字节和快手小程序已经实验性支持，可以参考文档配置开发 https://rax.js.org/docs/guide/miniapp-getting-start
