### ISSUE TITLE
[Question]没有处理eslint里的max-len

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2053]
如果同一行代码量超过100，则会提示max-len错误
为什么没有处理这个情况

现在临时解决是
```
// .prettierrc.js

const { getPrettierConfig } = require('@iceworks/spec');

module.exports = Object.assign(getPrettierConfig('rax'), { printWidth: 100 });
```

**Comment by fyangstudio** [comment]
eslint max-len 本身就不具备 **fixable** 能力：
https://github.com/eslint/eslint/blob/master/lib/rules/max-len.js

**Comment by xmsz** [comment]
> eslint max-len 本身就不具备 **fixable** 能力：
> https://github.com/eslint/eslint/blob/master/lib/rules/max-len.js

那要不要帮用户处理以下，例如在通过prettierrc自动帮用户换行

**Comment by fyangstudio** [comment]
prettier printWidth 有设置 10，eslint 规则在上述 PR 中已同步

**Comment by fyangstudio** [comment]
已发布，可以更新下 依赖
