### ISSUE TITLE
[Feature]建议文档侧边&顶部导航支持新标签页打开

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2054]
场景
我想要新窗口打开文档里的某个导航，现在没办法操作，必须自己手动在打开一个标签页，然后进入Rax首页，一个一个找到要找的地方。

非常麻烦

所以，希望文档可以用a标签跳转，这样可以比较快速的打开不同文档页面

**Comment by imsobear** [comment]
右键新标签页打开或者 Command/Ctrl + 左键。

**Comment by xmsz** [comment]
> 右键新标签页打开或者 Command/Ctrl + 左键。

... 
![image](https://user-images.githubusercontent.com/5879146/101874497-f0d3b580-3bc3-11eb-86b7-176e2b9049fc.png)

侧边导航和顶部导航都不行

**Comment by imsobear** [comment]
这个我们支持下

**Comment by imsobear** [comment]
已支持。
