### ISSUE TITLE
[Feature]支持Midway

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2056]
因为serverless框架用的是Midway，所以需要有将Rax整合到Midway的示例。或者Rax直接支持兼容Midway。目前文档只有阿里云云函数

**Comment by chenjun1011** [comment]
安装 Iceworks 插件后  https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks，可以在 Iceworks 的新建工程中，找到 Midway 模板

![image](https://user-images.githubusercontent.com/1303018/102295672-d82e1b80-3f86-11eb-872c-9a5b264739e2.png)

**Comment by xmsz** [comment]
> 安装 Iceworks 插件后 [https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks，可以在](https://marketplace.visualstudio.com/items?itemName=iceworks-team.iceworks%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%9C%A8) Iceworks 的新建工程中，找到 Midway 模板
> 
> ![image](https://user-images.githubusercontent.com/1303018/102295672-d82e1b80-3f86-11eb-872c-9a5b264739e2.png)

看到了 藏得有点小深 希望在文档里有介绍一下

**Comment by xmsz** [comment]
@chenjun1011 
有hooks版本的吗，@midwayjs/hooks

```
  "dependencies": {
    "@midwayjs/faas": "^2.5.5",
    "@midwayjs/faas-middleware-static-file": "^1.0.0",
    "rax": "^1.1.0",
    "rax-document": "^0.1.0",
    "rax-image": "^2.0.0",
    "rax-link": "^1.0.1",
    "rax-text": "^2.0.0",
    "rax-view": "^2.0.0",
    "universal-request": "^2.2.0"
  },
  "devDependencies": {
    "@iceworks/spec": "^1.0.0",
    "@midwayjs/faas-cli": "^1.2.32",
    "@types/rax": "^1.0.0",
    "build-plugin-midway-faas": "^1.0.0",
    "eslint": "^6.8.0",
    "prettier": "^2.1.2",
    "rax-app": "^3.0.0",
    "stylelint": "^13.7.2",
    "typescript": "^4.1.3"
  },
```
如果是这样的依赖跑不起来
