### ISSUE TITLE
Slider组件，垂直滚动失效问题[Question]

### ISSUE THREAD

**Issue by ChrisXYF** [alibaba/rax#2057]
在写组件的时候使用Slider组件，在direction设置了“vertical”，并且也加上了vertical={true}，但是依然为水平滚动
文档样例：
<img width="664" alt="ttt" src="https://user-images.githubusercontent.com/38465558/102520826-159dc080-40cf-11eb-86a5-70b8375fe273.png">

效果：
![11](https://user-images.githubusercontent.com/38465558/102520884-29e1bd80-40cf-11eb-95c6-08b1f56bb036.gif)

**Comment by fyangstudio** [comment]
slider web 环境不支持 切换方向。  可以使用 rax-swiper
