### ISSUE TITLE
H5页面使用rax-slider，在微信的小程序的webView容器里面会无法滚动

### ISSUE THREAD

**Issue by ZhenyuCheng** [alibaba/rax#2058]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

 (please complete the following information)
 - Device: [e.g. iPhone6, Mac]
 - Rax Version [e.g. 1.0.13]

**Additional context**

**Comment by fyangstudio** [comment]
rax-slider 在web 下不支持 切换方向。 可以使用 rax-swiper
