### ISSUE TITLE
使用RefForwardingComponent定义组件，但是构建之后组件props中缺少children类型[BUG]

### ISSUE THREAD

**Issue by Genluo** [alibaba/rax#2059]
**Describe the bug**
使用RefForwardingComponent定义组件，组件构建之后，其他项目中使用，提示缺少children类型定义，正常不应该带上这个定义吗？

**To Reproduce**
1. Go to '[source code](http://gitlab.alibaba-inc.com/industry-innovation/industry-innovation-content-layer/tree/daily/0.1.4)'
2. 切换分支至：daily/0.1.4
3. 安装依赖
4. 执行构建
5. 查看构建代码

**Expected behavior**
组件存在children定义Rax.RaxNode

**Screenshots**
组件中类型定义：
![image](https://user-images.githubusercontent.com/46585516/102797035-0fb72080-43ea-11eb-80f0-524ba07d305f.png)

构建的代码：
![image](https://user-images.githubusercontent.com/46585516/102796518-5f491c80-43e9-11eb-872a-d3b5a90b9c0c.png)

TS报错：
![image](https://user-images.githubusercontent.com/46585516/102796603-7b4cbe00-43e9-11eb-92c7-c4645cac5543.png)

 (please complete the following information)
 - Device: [e.g. iPhone6, Mac]
 - Rax Version [e.g. 1.0.13]

**Additional context**

**Comment by SoloJiang** [comment]
我看下这个问题

**Comment by SoloJiang** [comment]
示例项目拉下来没有报错，看了下实现，是考虑到了 children 的
