### ISSUE TITLE
[Question][universal-asyncstorage]要不要帮用户处理一下"getStorage:fail data not found"的问题

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2060]
背景及原因：

在小程序端调用AsyncStorage.getItem的表现
```
const res = await AsyncStorage.getItem('test');
```
默认情况下localstorage是没有`test`这个key，H5正常就返回null。
但是比较叛逆的小程序返回的是
```
       wx.getStorage({
            key: 'test',
            fail: (res) => {
                // res.errMsg 安卓返回 'getStorage:fail'， iOS 返回 'getStorage:fail data not found'
            },
        });
```
也就是会走fail（而且安卓和iOS返回的还不同），然后universal-asyncstorage就会直接返回一个Promise.reject对象。

![image](https://user-images.githubusercontent.com/5879146/102870793-7be06580-4478-11eb-8d40-29bc18f7ff09.png)
(找这个错误还有点蛋疼，因为不打log，根本看不出在哪错了)

----

我的想法是：
小程序这个情况要不要和**Web端对齐**，就是找不到也返回Promise.resolve对象，内容是个null就行。
其次如果只能在业务代码里写`err.errMsg === 'getStorage:fail data not found'`这种判断，其他人可能会看不懂这是哪来的错误

**Comment by SoloJiang** [comment]
需求应该是合理的

**Comment by DOBEEE** [comment]
我们会在新的 universal-storage api解决这个问题，预计在下周发布

**Comment by DOBEEE** [comment]
universal-asyncstorage@2.0.0-beta1已经发布了，用法有些不同，可以看下文档
https://www.npmjs.com/package/universal-asyncstorage

**Comment by xmsz** [comment]
> universal-asyncstorage@2.0.0-beta1已经发布了，用法有些不同，可以看下文档
> https://www.npmjs.com/package/universal-asyncstorage

改动有点略大 不过也不是不行 👍🏻

**Comment by xmsz** [comment]
> universal-asyncstorage@2.0.0-beta1已经发布了，用法有些不同，可以看下文档
> https://www.npmjs.com/package/universal-asyncstorage

改动有点略大 不过也不是不行 👍🏻

**Comment by imsobear** [comment]
https://universal-api.js.org/
