### ISSUE TITLE
[Feature]路由配置能否带有其他自定义字段？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2064]
需求

例如给特定路由添加`meta`自定义字段，内容为`{auth:true}`，在业务代码中也能够获取到该字段内容然后进行处理

**Comment by SoloJiang** [comment]
单页还是多页?

**Comment by xmsz** [comment]
> 单页还是多页?

单页

**Comment by SoloJiang** [comment]
特定路由添加 meta 标签这个能力不支持，目前只能通过高阶组件包裹一层处理相关需求
