### ISSUE TITLE
[Feature]支持选择postcss rpx转换vw还是rem

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2065]
现在rpx转换的是rem
但是现在代码中有一些自适应处理是调整font-size + rem来实现

所以希望可以让用户自己选择 rpx => rem 还是 rpx => vw

另外有没有什么临时的处理办法

----- 
https://www.npmjs.com/package/postcss-plugin-rpx2vw
我看到可以配置参数，再哪可以配置这个参数

一个是覆盖postcss.config.js，但是感觉太重了，没必要

一个是https://rax.js.org/docs/guide/build-config 这里scssLoaderOptions一样配置最好

**Comment by SoloJiang** [comment]
建议迁移过程中，可以先把你之前 rpx 转换逻辑改掉，在 Rax 项目里，`rpx` 是属于关键词单位。

**Comment by xmsz** [comment]
> 建议迁移过程中，可以先把你之前 rpx 转换逻辑改掉，在 Rax 项目里，`rpx` 是属于关键词单位。

之前也是rpx，不过最终转换的是rem单位。

现在就是想能不能控制最终转换的单位是rem而不是vw

因为vw没办法手动控制自适应缩放比例，或者说我们项目是vw + rem 都在用的方案
