### ISSUE TITLE
[Feature]sass-loader版本太老了

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2066]
sass-loader的版本太老了，导致无法使用https://webpack.js.org/loaders/sass-loader/#options参数

例如
prependData在新版本中是additionalData

**Comment by SoloJiang** [comment]
这个月尝试进行升级

**Comment by imsobear** [comment]
关联 issue：https://github.com/alibaba/ice/issues/4060

**Comment by SoloJiang** [comment]
done
