### ISSUE TITLE
[Feature]希望完善history的类型提示

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2069]
![image](https://user-images.githubusercontent.com/5879146/103847877-17f6a780-50dc-11eb-9122-96ba22bd27e8.png)
现在的history类型是any，使用时候就没有类型提示

------
另外「https://rax.js.org/docs/guide/route」文档中
![image](https://user-images.githubusercontent.com/5879146/103848043-76238a80-50dc-11eb-968a-969864a49382.png)

这个链接是错的

----
还有history.listen的回调参数和history API不一致
history API是
```
history.listen(({ action, location }) => {
  console.log(
    `The current URL is ${location.pathname}${location.search}${location.hash}`
  );
  console.log(`The last navigation action was ${action}`);
});
```
Rax是
```
history.listen((location) => {
  console.log(
    `The current URL is ${location.pathname}${location.search}${location.hash}`
  );
});
```

**Comment by SoloJiang** [comment]
https://github.com/raxjs/miniapp/pull/80

只是文档表述有问题，实际运行代码已经是 history 标准的返回值

**Comment by xmsz** [comment]
> [raxjs/miniapp#80](https://github.com/raxjs/miniapp/pull/80)
> 
> 只是文档表述有问题，实际运行代码已经是 history 标准的返回值

就是下面这个文件里的history类型是any，导致在使用过程中没办法使用history的类型补全

![image](https://user-images.githubusercontent.com/5879146/105453666-7c5c5e00-5cbb-11eb-9ccc-e06207ff4f73.png)


```
// node_modules/create-app-shared/lib/history.d.ts

declare let history: any; // <= 这个是any，理论上是History
declare function createHistory({ routes, customHistory, type, basename, location }: any): any;
declare function getHistory(): any;
export { getHistory, createHistory, history };


```

**Comment by xmsz** [comment]
所以 咋整？
```
import { history } from 'rax-app';
```
这样调用history的类型是any

我要怎么处理才能有类型提示，如果安装`miniapp-history`，那web端怎么使用

**Comment by xmsz** [comment]
现在临时就是`npm i history -D` 来获取类型提示
但是实际上是api没对齐


比如并不支持这种写法，需要填写完整的url
```
history.push({
 pathname:""
})
``

还有go这个方法在小程序里并不能用，也没有back，而是goBack
