### ISSUE TITLE
[Question]请问@alifd/meet和@alifd/next是什么区别 以及其他微信小程序相关问题

### ISSUE THREAD

**Issue by waylon-edmodo** [alibaba/rax#2072]
1. 我从iceworks引入的模版都是 @alifd/meet，不晓得他们有什么区别。有没有相关文档。
2. 打出的微信小程序包超过了5M，不知道大家有没有遇到。
3. 部分控件在微信小程序下显示不正常。

![image](https://user-images.githubusercontent.com/51694657/105176031-a6007280-5b5f-11eb-9e47-bd136fc24896.png)

求大佬们指点。首次研究rax。

**Comment by waylon-edmodo** [comment]
2. 移除@alifd/next后包大小降到了900k。 --- Done

**Comment by ChrisCindy** [comment]
dev 模式下可以关闭 source-map 以减小体积，build 模式下会进一步压缩代码。如果还存在体积问题，可以使用分包加载。

**Comment by ChrisCindy** [comment]
fusion mobile 目前还没有开源，敬请期待。

**Comment by waylon-edmodo** [comment]
回复好快。
3. 在真机上ui正常。
![image](https://user-images.githubusercontent.com/51694657/105177504-ba456f00-5b61-11eb-8c14-3f424693b68d.png)
