### ISSUE TITLE
[Feature]有人做axios的adapter吗？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2073]
### 背景
- 一般项目都使用axios作为多端请求工具
- Rax中只能使用universal-request来作为多端使用工具
- universal-request的只能满足基础需求，但很多需求需要axios这类扩展工具处理

### 需求
- 在项目中直接使用axios
- axios新增rax universal-request相关adapter，这样就可以使用了

目前来说要简单实现是可以，但是希望有人做出官方一点的版本

**Comment by SoloJiang** [comment]
我之前自己有 fork 一份 axios，做过兼容微信的版本，目前来看，其实只需要一份 adapter 就好了，这种就留社区生态自己建设就好，如你所说只需要 universal-request + adapter 即可完成，针对 HTTP 请求这块，最终我们所希望的解决方案可能是和 ICE 一样 https://github.com/alibaba/ice/blob/master/packages/plugin-request/README.md，如果感兴趣的话，可以在 github.com/raxjs/rax-app 给我们提 pr 支持

**Comment by xmsz** [comment]
> 我之前自己有 fork 一份 axios，做过兼容微信的版本，目前来看，其实只需要一份 adapter 就好了，这种就留社区生态自己建设就好，如你所说只需要 universal-request + adapter 即可完成，针对 HTTP 请求这块，最终我们所希望的解决方案可能是和 ICE 的 [useRequest](https://github.com/alibaba/ice/blob/master/packages/plugin-request/README.md) 一样 ，如果感兴趣的话，可以在 github.com/raxjs/rax-app 给我们提 pr 支持

Ice的useRequest看起来不错，已经能我的需求

我现在走的就是axios adapter这条，fork一份https://github.com/bigmeow/axios-miniprogram-adapter然后加了rax的适配。很简单的实现，不过有个字段比较蛋疼，就是其他小程序里的头部字段是`header`但是rax里的是`headers`
