### ISSUE TITLE
[Question]tabbar的图片在编译成小程序可以显示，但是web下不能显示。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2074]
app.json

  "tabBar": {
    "textColor": "#6e6d6b",
    "selectedColor": "#ff9966",
    "borderStyle": "black",
    "backgroundColor": "#ffffff",
    "items": [
      {
        "path": "/",
        "name": "首页",
        "icon": "images/tabBar/home.png",
        "activeIcon": "images/tabBar/home_on.png"
      },

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/105606849-976fc080-5dd6-11eb-9518-c7110aeb6a4c.png)

**Comment by waylon-gmail** [comment]
另： tabbar在小程序下点击 tab可以切换。但是在web下点击不会切换，虽然路由会变，但是界面没有切换。

**Comment by waylon-gmail** [comment]
图片放在 src/public 下不行， inlineStyle: true也不行

**Comment by SoloJiang** [comment]
图片放到根目录 public 文件夹下，然后路径直接通过 /tab.png 这样引用就好了
