### ISSUE TITLE
[Question]当设置font-size: 28rpx时报，Invalid property value

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2082]
不知道是哪里错了，求大佬帮忙看下。

![image](https://user-images.githubusercontent.com/51048705/106362457-d913e480-635d-11eb-899f-92ce94954beb.png)

**Comment by waylon-gmail** [comment]
好像是css文件import另一个css的时候才会出现这个问题

**Comment by SoloJiang** [comment]
可以提供一下复现 demo，确定下是不是 @import 一个 CSS 文件导致的

**Comment by waylon-gmail** [comment]
可以确定是的。demo的话我明天弄一个，也许你们也可以自己重现。我是这样引入的。

@import "../CommonCss/index.module.css";  // 这个文件里面的font-size会有问题。

/* 搜索框 */

.homeTitle {
  font-size: 45rpx;
  font-weight: bold;
  margin: 20rpx 0;
}

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/106771258-ba715e80-6679-11eb-9a59-3b6f1d8ed5d5.png)

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/106771376-d8d75a00-6679-11eb-9843-8e1ab2bc1f78.png)
![image](https://user-images.githubusercontent.com/51048705/106771428-e55bb280-6679-11eb-9c4a-55d5c0461ec1.png)
![image](https://user-images.githubusercontent.com/51048705/106771462-f0164780-6679-11eb-8514-cfa03793857d.png)

Demo: https://github.com/waylon-gmail/rax-demo

**Comment by waylon-gmail** [comment]
把 <Text className={styles.testText}>Test Font Size</Text>
改成
<Text className='testText'>Test Font Size</Text>
就会正常

**Comment by waylon-gmail** [comment]
文件名没有module的css也有相同的问题。
import 'index.css'
然后 index.css又import其他的css，比如 import 'common.css'

**Comment by SoloJiang** [comment]
我来看下这个问题
