### ISSUE TITLE
[Question]navigateTo:fail can not navigateTo a tabbar page

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2083]
![image](https://user-images.githubusercontent.com/51048705/106779687-340d4a80-6682-11eb-8ade-fd914fc4e1b8.png)

import Navigate from 'universal-navigate';

    Navigate.push({
      url: '/pages/Home/index'
    }).then(() => {
    });

请问大佬这个不支持跳转tab，有其他可以替代的吗？

**Comment by waylon-gmail** [comment]
没有找到 switchTab 方法。只有Link组件那边有。但是我这边的需求是用方法调用。

**Comment by waylon-edmodo** [comment]
![image](https://user-images.githubusercontent.com/51694657/107488452-55aa8c80-6bc2-11eb-842b-eaf5cdcfe5a2.png)
这个效果好像也没有。

**Comment by SoloJiang** [comment]
小程序中跳转 tab 比较特殊，所以可能需要自己调用 `wx.switchTab` 方法来实现跳转，目前所有的 Link 组件应该都是没有下划线的，可以再确认下
