### ISSUE TITLE
@kraken-project/cli 安装失败

### ISSUE THREAD

**Issue by hlsky1988** [alibaba/rax#2084]
sudo npm i @kraken-project/cli -g

Warning: Failed to create the file kraken-darwin-0.6.4.tar.gz: Permission

Error: Command failed: curl -O https://kraken.oss-cn-hangzhou.aliyuncs.com/kraken-cli-vendors/kraken-darwin-0.6.4.tar.gz

@kraken-project/cli@0.6.4 postinstall: `node install.js`

挂不挂代理都是这样, 官方源和淘宝源都试过了

OS: macOS Catalina 10.15.6 19G73 x86_64
"rax-app": "^3.0.0"

**Comment by imsobear** [comment]
@hlsky1988 这个问题是否还存在？

**Comment by imsobear** [comment]
https://github.com/openkraken/kraken 可以移步 kraken 仓库
