### ISSUE TITLE
[Question]universal-canvas-context如何正确获取canvas实例

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2087]
微信小程序运行时
```
import { createElement, useEffect, Fragment } from 'rax';
import createContext from 'universal-canvas-context';
 
function App() {
  useEffect(() => {
    createContext('canvasId', '2d').then(context => {
      context.fillStyle = 'red';
      context.fillRect(0, 0, 100, 100);
      context.draw();
    });
  }, []);
 
  return (<>
    <canvas id='canvasId'></canvas>
  </>)
}
```

这里拿到的是 `[null]`

![image](https://user-images.githubusercontent.com/5879146/107846297-9d792000-6e1d-11eb-8bf3-bc7b763cc96c.png)

当然直接用微信小程序API也是一样，原因可能是在自定义组件中的canvas实例需要通过 this.createSelectorQuery而不能wx.createSelectorQuery

硬写的话

- 用旧的获取方式`var context = wx.createCanvasContext('firstCanvas')`倒是没问题但不符合需求
- 获取dom => 拿到组件实例 => 组件实例.createSelectorQuery 不好的写法

   
----------------------------------

**Comment by ChrisCindy** [comment]
this.createSelectorQuery 这里的 this 在 rax 中需要通过特定方法获取。假设需要取的节点的 id 为 test，则通过以下方式：

```
const element = document.getElementById("id")

const instance = element._internal

// instance 即为小程序的 this 对象

```

**Comment by xmsz** [comment]
> this.createSelectorQuery 这里的 this 在 rax 中需要通过特定方法获取。假设需要取的节点的 id 为 test，则通过以下方式：
> 
> ```
> const element = document.getElementById("id")
> 
> const instance = element._internal
> 
> // instance 即为小程序的 this 对象
> ```

对 这个是我现在用的方法

> 获取dom => 拿到组件实例 => 组件实例.createSelectorQuery

这样的话用起来比较奇怪 而且也没办法用`universal-canvas-context`这个包，有没有其他办法

**Comment by SoloJiang** [comment]
API 本身的实现是不耦合框架的，而微信这个获取实例的方式本身就依赖于使用环境：页面/组件，所以在特殊场景下，用户主动传入实例更加合理

**Comment by xmsz** [comment]
> API 本身的实现是不耦合框架的，而微信这个获取实例的方式本身就依赖于使用环境：页面/组件，所以在特殊场景下，用户主动传入实例更加合理

那有没有办法
- `universal-canvas-context`支持传入小程序实例，不然如果是小程序环境用不到这个包还得自己再写一层有点麻烦
- 更优雅一点获取`_internal `，现在这种获取方法既没有类型提示，用起来有点暴力

**Comment by SoloJiang** [comment]
- `universal-canvas-context` 第二个参数就是传入小程序实例，更优雅一点的写法是通过 ref 获取到节点，`ref.current._internal`
- 小程序上比较特殊的是：同时存在 Rax 实例、模拟 Node 实例、小程序原生节点实例，而小程序原生实例本身用到的场景很少，所以当初的设计是把这个变量作为私有变量提供，后续可以考虑框架提供一个方法 `getMiniAppInstance(ref)` 更优雅的获取

**Comment by SoloJiang** [comment]
待微信模板改造完成之后再确定实现方式

**Comment by xmsz** [comment]
> * `universal-canvas-context` 第二个参数就是传入小程序实例，更优雅一点的写法是通过 ref 获取到节点，`ref.current._internal`

我记得源码里直接是`wx.`写死的，没有传入实例的地方
```
import { CanvasContext, ContextAttributes } from '../types';

declare const wx: any;

function createContext(
  selector: string,
  type: string = '2d',
  options: ContextAttributes = {}
): Promise<CanvasContext> {
  return new Promise((resolve, reject) => {
    const query = wx.createSelectorQuery();
    query
      .select(`#${selector}`)
      .fields({ node: true, size: true })
      .exec((res) => {
        if (!res[0] || !res[0].node) reject('The canvas node may not exist.');
        const canvasNode: HTMLCanvasElement = res[0].node;
        const context: CanvasContext = canvasNode.getContext(type, options);
        // For fallback
        context.draw = function() {};
        resolve(context);
      });
  });
}

export default createContext;
```

**Comment by SoloJiang** [comment]
这个地方我们要再看看，最近微信模版在重构，可能存在变动

**Comment by ChrisCindy** [comment]
https://rax.js.org/docs/guide/miniapp-faq#3.%20%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8E%9F%E7%94%9F%E4%BD%9C%E7%94%A8%E5%9F%9F%E6%80%8E%E4%B9%88%E8%8E%B7%E5%8F%96%EF%BC%9F
