### ISSUE TITLE
[Question]微信小程序现在只有使用微信的button才能获取用户信息，不知道在rax中怎么写，求助大佬们。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2088]
https://developers.weixin.qq.com/community/develop/doc/000aee01f98fc0cbd4b6ce43b56c01

``
<button class="btn-normal" openType="getUserInfo" lang="zh_CN" bindgetuserinfo="getUserInfo">授权登录</button>
``

在代码中这么写，编译后就变掉了，无法正常使用。

**Comment by ChrisCindy** [comment]
bindgetuserinfo 改成 onGetUserInfo 即可
@waylon-gmail

**Comment by waylon-gmail** [comment]
十分感谢！
