### ISSUE TITLE
[Question]路由使用browser，二级目录部署，需要publicPath，设置后发现一些问题。 

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2089]
``
"publicPath": "/webapp/"
``
1. Link组件需要web开发加上publicPath, 小程序不能加；
2. Navigator组件需要web开发加上publicPath(使用history不需要开发拼), 小程序不能加；
3. tabbar的image在public文件夹下会识别不到image，如果加上 publicPath就会影响小程序。
4. 请问代码中如何获取publicPath

**Comment by SoloJiang** [comment]
1. 跳转：建议使用 history 路由方案，`history.push(path)`
2. public 文件夹使用参照：https://rax.js.org/docs/guide/public

**Comment by waylon-gmail** [comment]
tabbar不是配置在app.json中吗，好像没法用 process.env.PUBLIC_URL

**Comment by SoloJiang** [comment]
> tabbar不是配置在app.json中吗，也可以用 process.env.PUBLIC_URL吗

这其实是个伪命题，`publicPath` 是你自己手动配置的，你必然是知道 publicPath 具体值的

**Comment by waylon-gmail** [comment]
嗯。主要是同时编译web跟小程序的时候，会有问题。app.json 加了pubicPath，小程序就认不到图片，不加publicPath，web就认不到图片。

**Comment by waylon-gmail** [comment]
``
[ app.json 文件内容错误] app.json: ["tabBar"]["list"][0]["selectedIconPath"]: "/publicPath-web/images/home-active.png" 未找到
``
如果在app.json加publicPath，在小程序下，public文件夹里面得再加一层 publicPath的目录，小程序才能识别。
如果public文件夹里面多加了一层publicPath，web模式下就会有两层publicPath，就会识别不到图片。

**Comment by SoloJiang** [comment]
这里应该不是一个 bug，在小程序构建过程中，由于小程序对目录的特殊性，`publicPath` 其实是个无效配置，但是对于 Web 而言在部署的时候，用户需要把静态资源放到 `publicPath` 目录下，所以针对 tabbar 场景会有你所描述的问题。
解决方法：**使用相对路径** 配置 tabbar 的 icon，比如 `./images/home-active.png`

**Comment by waylon-gmail** [comment]
我试一试

**Comment by waylon-gmail** [comment]
path: /pages/home/index

http://domain/public_path/pages/home/images/home-active.png --- 404

测试发现用相对路径, 如果path不是 / 的情况下，只有小程序是正常的。首页的path是 /，所以没有问题。当首页不是 /， 或者切到其他tab的时候，就会出现问题，因为其他tab的path不是 /

**Comment by waylon-gmail** [comment]
我现在是使用两个tab.json ，编译的时候用自己的脚本先替换然后再npm run build

**Comment by SoloJiang** [comment]
publicPath 本身在构建 Web 应用的时候路径关系就是复杂的，以你这个例子为例，当配置成 / 开头之后，这个时候资源是相对于服务器的位置，此时你是人为的将静态资源部署到了服务器上 webapp 目录，然而对于小程序而言，如果你设置了 publicPath 你同样需要人为的将静态资源（public 文件复制到 build/wechat-miniprogram 里的内容）复制到 build/wechat-miniprogram/webapp 下面，从而你可以在 app.json 里去写 /webapp/home.png 这样。

简单来说就是，Web 在配置 publicPath 的时候有人工部署的环节，小程序同样亦是如此

**Comment by waylon-gmail** [comment]
这个如果就是这样的话关系不大哈。我现在用rax基本上已经快要完成我的应用了，总体问题不大。感谢大佬们的支持。

对我影响最大的应该是这个问题： https://github.com/alibaba/rax/issues/2082
如果能够尽快有解决方案的话非常感谢，因为我有很多css是import其他css的，目前只能把他们都复制过来放到一个css下。

**Comment by SoloJiang** [comment]
那这个 issue 先关掉了？
