### ISSUE TITLE
[Question]如何正确配合使用icestark使用

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2090]
现在使用React方案
[主应用开发与接入（React）](https://ice.work/docs/icestark/guide/framework-app)

但是遇到
`validateChildKeys.js:89 Uncaught TypeError: Cannot add property __validated, object is not extensible` 的问题，而且需要额外安装react比较不合理

所以我的问题

1. 如何配合使用icestark

1.1 有没有更简单的配置或者使用方式
1.2 该用哪种方法才能跑起来

2. 如何使用第三方react库而无需安装react
现在安装第三方react还得再安装一遍react，并且不一定能跑起来。这种情况该怎么解决

**Comment by SoloJiang** [comment]
Rax 暂时没有微前端方案

**Comment by imsobear** [comment]
@xmsz 可以提供下子应用的 demo 仓库以及对应子应用的配置，我们试一下。

**Comment by xmsz** [comment]
> @xmsz 可以提供下子应用的 demo 仓库以及对应子应用的配置，我们试一下。

又试了一下 好像没什么问题 后面有时候再看看
