### ISSUE TITLE
[Question]微信小程序的picker，bindchange不生效，不知道该怎么写。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2091]
``
<picker mode="region" bindchange="bindRegionChange"></picker>
``

微信小程序的picker，bindchange不生效，不知道该怎么写。

**Comment by ChrisCindy** [comment]
onChange

**Comment by SoloJiang** [comment]
原生事件中所有的 `bindxxxx`，在 Rax 中均使用 JSX 规范：`on` + 单词首字母大写

**Comment by waylon-gmail** [comment]
这个控件我试了好像不起作用。

**Comment by imsobear** [comment]
@waylon-gmail 问题如果还没解决的话，可以多提供点信息然后 reopen 下 issue。

**Comment by waylon-gmail** [comment]
谢谢三位大佬。问题解决了，是使用的时候一个参数传错了，还以为是onChage不支持。
