### ISSUE TITLE
[Question]appConfig getInitialData 小程序不会触发，web每个页面都会触发，请问是设计如此吗？

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2095]
![image](https://user-images.githubusercontent.com/51048705/108522911-46d18180-7308-11eb-8996-7227c6ad020f.png)

const appConfig = {
  app: {
    getInitialData: async () => {
      const restUserRes = await queryCurrentUser();
      return { initialStates: {user: { currentUser: restUserRes } }};
    },
  },
}

**Comment by waylon-gmail** [comment]
开始以为这个是打开应用的时候首次触发一次。经过实际测试，web在push页面的时候每次都会触发。小程序从不会触发。

**Comment by waylon-gmail** [comment]
web每次都触发是因为用的是：
import Navigate from 'universal-navigate';
Navigate.push({url: '/page'});

如果改成 
import { history } from 'rax-app';
history.push('/page')

则跟预期的一致，只在首次进入页面时触发。

**Comment by SoloJiang** [comment]
1. 小程序确实不会触发，`getInitialData` 的用途是在 SSR 的时候，能够获取到来自服务端的数据
2. web 使用 `universal-navigate` 每次都触发的原因是，这个 API 本质上是利用浏览器的能力 location.href 进行跳转，对页面有刷新行为，而后者是纯前端路由

**Comment by imsobear** [comment]
@SoloJiang 第一点不合理吧

**Comment by SoloJiang** [comment]
- 职责问题，`getInitialData` 在 CSR 阶段对于有没有开启 SSR 构建表现是不一样的，如果开启 SSR 且获取到了初始化数据，那么在 CSR 的时候，`getInitialData` 是不会再执行的，若关闭 SSR，`getInitialData` 是会执行的
- 小程序上前置同步获取数据的合理性，如果需要 `await` `getInitialData` 执行，会导致生命周期相关的代码直接失效，因为触发生命周期的时序是由容器决定的
- 总结：目前来说，`getInitialData` 可能只适合纯 Web 场景使用，多端一致性难以得到保证

**Comment by imsobear** [comment]
职责这块我觉得是合理的，核心还是实现问题也就是框架侧的问题，我们应该想办法去实现，如果实现不了那就做好引导。

**Comment by waylon-gmail** [comment]
建议能有一个类似的实现给小程序，用于启动应用的时候拉取一些配置。

**Comment by SoloJiang** [comment]
> 建议能有一个类似的实现给小程序，用于启动应用的时候拉取一些配置。

启动的时候拉取配置，会用在组件渲染吗？

**Comment by waylon-gmail** [comment]
> > 建议能有一个类似的实现给小程序，用于启动应用的时候拉取一些配置。
> 
> 启动的时候拉取配置，会用在组件渲染吗？

目前主要是用来拉取一些权限相关的配置，会控制一些入口。

**Comment by SoloJiang** [comment]
那还是会影响渲染的，这种情况下目前的建议是通过高阶组件来鉴权，然后进行重定向。小程序的渲染和 Web 存在天然不一样的是，Web 是可以在路由加载前进行路由守卫或者阻止页面渲染的，但小程序的渲染以及生命周期是容器决定的，一旦在 app 启动的时候做了拦截，容器的事件都会错过造成混乱

**Comment by waylon-gmail** [comment]
好的，没有统一的入口处理也是有办法可以的，虽然麻烦一点，但是这个问题也不大。谢谢。
