### ISSUE TITLE
[Question] Rax 开发的组件库可以在非 Rax 项目中使用吗？还是必须要在 Rax 项目中

### ISSUE THREAD

**Issue by shenxiang11** [alibaba/rax#2099]
Please describe the problem you meet.

**Comment by imsobear** [comment]
想在什么项目里使用？

**Comment by shenxiang11** [comment]
> 想在什么项目里使用？

使用Rax开发组件库，分别用于 h5  和 原生小程序项目

**Comment by imsobear** [comment]
> > 想在什么项目里使用？
> 
> 使用Rax开发组件库，分别用于 h5 和 原生小程序项目

只要是 Rax 项目就没有问题。

**Comment by shenxiang11** [comment]
好的，感谢，那 rax 可能不能满足我的需求了，其他项目不是 rax 的。

**Comment by shenxiang11** [comment]
好的，感谢，那 rax 可能不能满足我的需求了，其他项目不是 rax 的。
