### ISSUE TITLE
[rax-calendar]feature：是否提供以周维度的选择功能

### ISSUE THREAD

**Issue by fattydevelop** [alibaba/rax#210]
- Feature request
> 移动端的日历组件占用空间比较大，以周维度提供，能够减少空间占用更加适合实际业务场景。

- 类似如下视觉稿：
![image](https://cloud.githubusercontent.com/assets/3349721/24838061/3b329740-1d73-11e7-99b8-ee604ae4d558.png)

**Comment by wssgcg1213** [comment]
cc @yacheng

**Comment by yacheng** [comment]
未来会提供 datepicker 组件来支持精简的日期选择
