### ISSUE TITLE
[BUG] [微信小程序] - style 不支持 WebkitLineClamp 或者 -webkit-line-clamp

### ISSUE THREAD

**Issue by Rabbitzzc** [alibaba/rax#2109]
代码：
```
<view style={{
      '-webkit-box-orient': 'vertical',
      '-webkit-line-clamp': 2,
      color: 'blue',
    }}>
```
渲染成小程序代码以后，可以发现 `-webkit-line-clamp` 丢失

**Comment by ChrisCindy** [comment]
@Rabbitzzc 微信端还是支付宝端？

**Comment by Rabbitzzc** [comment]
通过 className 是可以的，这块感觉是 style 解析的问题

**Comment by Rabbitzzc** [comment]
微信端

**Comment by Rabbitzzc** [comment]
也尝试使用了 `WebkitLineClamp` 与 `-WebkitLineClamp`
> demo: https://codesandbox.io/s/clever-diffie-n0lq1?file=/src/App.js

可以发现，`WebkitLineClamp` 可以在 PC 端作用，但是通过 Rax 写的小程序解析失败

**Comment by Rabbitzzc** [comment]
看到两个比较类似的场景：
> https://github.com/remaxjs/remax/commit/1e7997d432fc4416c4bf43c656dc777a67fbc66c
https://github.com/NervJS/taro/issues/1056

**Comment by ChrisCindy** [comment]
style 中会过滤一部分的 css 样式属性，建议使用 class 方式配置

**Comment by Rabbitzzc** [comment]
是的，但是需要动态设置样式，请问有好的解决办法么，比如说根据 props 传递属性，设置 style

**Comment by xmsz** [comment]
有哪些属性会被过滤

flexShrink（这个比较常用 ）也被过滤了

**Comment by Rabbitzzc** [comment]
> 有哪些属性会被过滤
> 
> flexShrink（这个比较常用 ）也被过滤了

可以看一下源码，有个 `style.ts`

**Comment by ChrisCindy** [comment]
> 有哪些属性会被过滤
> 
> flexShrink（这个比较常用 ）也被过滤了

flexShrink 不会被过滤，再检查下代码看看。miniiapp-render/src/node/style-list.js 里有 style 的映射关系

**Comment by ChrisCindy** [comment]
> 是的，但是需要动态设置样式，请问有好的解决办法么，比如说根据 props 传递属性，设置 style

如果没有遇到一些冷门 style 被过滤的情况，是可以正常动态设置 style 的。如果遇到的话，建议动态设置 class。

**Comment by xmsz** [comment]
> > 有哪些属性会被过滤
> > flexShrink（这个比较常用 ）也被过滤了
> 
> flexShrink 不会被过滤，再检查下代码看看。miniiapp-render/src/node/style-list.js 里有 style 的映射关系

确实是我自己的问题，我才发现原来如果设置为`Falsy`值是不会渲染的


类似这种，最终不会渲染`flexShrink`，因为`0`属于`Falsy`，带单位的除外

```
<div
            style={{
              flexShrink: 0,
            }}
          >
            FlexShrink
          </div>
```



不过正常，`flex:0` 可以被渲染成 `flex: 0 0 0%;`
