### ISSUE TITLE
[Feature][小程序]如何配置自定义TabBar

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2112]
背景
- 项目需要配置自定义TabBar

表现
- 不知道怎么配置，在`app.json`配置了`custom: true`，就无从下手了

希望
- 了解如何配置自定义TabBar
- 有没有更方便的方式配置
- 【不相关的问题】小程序tabBar的图片需要本地图片，这个要如何兼容Web端

**Comment by SoloJiang** [comment]
- 目前根据小程序官方文档，自定义 TabBar 需要在产物的根目录，所以需要把自定义 TabBar 的实现放在 Rax App 的 public 文件夹下，而且只支持原生语法
- 使用本地图片，也是将资源放在 `public` 目录下，具体可以参见 Rax 文档 public 文件夹使用这一章节
- 面向未来，Rax 会提供更强大的通过 JSX 写自定义 TabBar 的能力

**Comment by xmsz** [comment]
> * 目前根据小程序官方文档，自定义 TabBar 需要在产物的根目录，所以需要把自定义 TabBar 的实现放在 Rax App 的 public 文件夹下，而且只支持原生语法
> * 使用本地图片，也是将资源放在 `public` 目录下，具体可以参见 Rax 文档 public 文件夹使用这一章节
> * 面向未来，Rax 会提供更强大的通过 JSX 写自定义 TabBar 的能力 [raxjs/rax-app#705](https://github.com/raxjs/rax-app/issues/705)

ok，我先在public写原生代码

**Comment by SoloJiang** [comment]
后续 TabBar 的进展在 rax-app 中相关 RFC 归纳

**Comment by xmsz** [comment]
现在这个需求怎么样了

我本地设置
```
{
  "routes": [
    {
      "path": "/",
      "source": "pages/Home/index"
    },
    {
      "path": "/mine",
      "source": "pages/Mine/index"
    }
],
  "window": {
    "title": "Rax App"
  },
  "tabBar": {
    "custom": true,
    "list": ["/", "/mine"]
  }
}
```
- 也创建了CustomTabBar组件

但
- web页也没有
- 小程序也没有
