### ISSUE TITLE
[BUG] 使用 vant 添加到 miniapp-native，组件 linked 事件调用失败

### ISSUE THREAD

**Issue by Rabbitzzc** [alibaba/rax#2113]
#### 问题描述
在 Rax 开发的小程序中，使用 vant 添加到 miniapp-native，使用了 drop-menu 组件，发现无效果。经过测试，发现组件内部 link 事件调用失败。
![image](https://user-images.githubusercontent.com/26913511/114397888-bf9ade80-9bd1-11eb-8626-2410e78bb105.png)

**Comment by Rabbitzzc** [comment]
Rax 默认生成的 bundle.js 就已经超过代码片段分享大小限制了[￣□￣｜｜]

**Comment by ChrisCindy** [comment]
提供一下具体的代码片段。另外 dev 模式下因为存在 source map 所以体积比较大，如不需要可在 build.json 中配置关闭 source map，同时可以配置开启压缩代码。具体选项参考文档 https://rax.js.org/docs/guide/build-config

**Comment by ChrisCindy** [comment]
提供一下具体的代码片段。另外 dev 模式下因为存在 source map 所以体积比较大，如不需要可在 build.json 中配置关闭 source map，同时可以配置开启压缩代码。具体选项参考文档 https://rax.js.org/docs/guide/build-config

**Comment by Rabbitzzc** [comment]
了解，[代码片段 link](https://developers.weixin.qq.com/s/cNLKRwmr73py)

**Comment by ChrisCindy** [comment]
@Rabbitzzc 源码也提供一下吧

**Comment by Rabbitzzc** [comment]
done. https://github.com/fd532/rax-components-link-test

**Comment by ChrisCindy** [comment]
@Rabbitzzc 确实存在 linked 未调用的问题，具体原因需要进一步排查。绕过方法是自行封装一个原生自定义组件 CustomDropdownMenu，该组件内部使用 van-dropdown-menu 和 van-dropdown-item。然后在 Rax 的代码中引入 CustomDropdownMenu 即可。

**Comment by Rabbitzzc** [comment]
了解

**Comment by Rabbitzzc** [comment]
不过对于小程序自定义的 trigger 事件，Rax 中如何能监听到呢？通过 on 好像不行

**Comment by ChrisCindy** [comment]
假设小程序中通过 this.triggerEvent('Test') 触发事件，则在 Rax 端通过 onTest 即可监听。

**Comment by Rabbitzzc** [comment]
是的，我通过 trigger 好像不行，目前是通过传递 props_function 去解决了，不知道是不是个人使用问题。

**Comment by ChrisCindy** [comment]
> 是的，我通过 trigger 好像不行，目前是通过传递 props_function 去解决了，不知道是不是个人使用问题。

这个问题如果还存在可以提供一个可复现的排除 vant 的 demo。

**Comment by Rabbitzzc** [comment]
> > 是的，我通过 trigger 好像不行，目前是通过传递 props_function 去解决了，不知道是不是个人使用问题。
> 
> 这个问题如果还存在可以提供一个可复现的排除 vant 的 demo。

可以。不过我记得在写 Rax 自定义事件的时候，有点问题，我回头再试试
