### ISSUE TITLE
[Question]为啥是"jsxFactory": "createElement"而不是"jsx": "react"？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2118]
背景：
rax现在的配置是
```
    "jsx": "preserve",
    "jsxFactory": "createElement",
```

然后在ice的项目中又是
```
"jsx": "react",
```

两边的不对齐，导致会出现说确实引入这种提示

问题：
- 为什么不是默认的`react`
- 如果我改成`react`会不会有其他副作用

**Comment by SoloJiang** [comment]
可以看下这篇文档 https://www.typescriptlang.org/docs/handbook/jsx.html

本质是 Rax 本身和 React 的导出方式不同

**Comment by xmsz** [comment]
> 可以看下这篇文档 https://www.typescriptlang.org/docs/handbook/jsx.html
> 
> 本质是 Rax 本身和 React 的导出方式不同

好吧
