### ISSUE TITLE
[@ali/universal-tracker] 问题

### ISSUE THREAD

**Issue by miaojing** [alibaba/rax#212]
此组件和 goldlog中的report方法重复，不建议在文档中透出，之前 和@法海 讨论对业务使用收敛到 goldlog，不用再单独使用tracker。

**Comment by wssgcg1213** [comment]
@miaojing 帮你迁移到内部反馈渠道 http://gitlab.alibaba-inc.com/raxjs/questions/issues/3

**Comment by pushiming** [comment]
此组件可以废弃。
