### ISSUE TITLE
[BUG] 组件上设置 data-* 数据，会被过滤

### ISSUE THREAD

**Issue by Rabbitzzc** [alibaba/rax#2120]
如题，比如
```
<button data-id="123">
```
生成的小程序原生组件中不存在 `data-id`，只会存在 `data-private-node-id` 属性

**Comment by ChrisCindy** [comment]
由于组件需要提前渲染生成，dataset 较为灵活，无法提前绑定至模板，因此用户绑定的 dataset 不会生效。但是用户在绑定的点击等事件的 event 中能够获取到 dataset。除此之外，由于 button 的特殊性（拉起用户登录、分享等），我们提供了 data-params 这一属性，用户可以在该属性上进行配置。

**Comment by Rabbitzzc** [comment]
收到，原来 data-params 可以这么用，看默认生成都是 undefined
