### ISSUE TITLE
[Feature]提供组件的渲染信息

### ISSUE THREAD

**Issue by cryzzchen** [alibaba/rax#2121]
两个需求。
1）
在页面初次渲染开始时和结束时 mark一下，并计算所用时长。
目的：了解页面的初次渲染的情况，提供比FP、FCP等更准确的页面情况数据。

2）
在生产环境中，用户可以自定义收集某段时间内，各组件的：
- 触发渲染的时间戳
- 渲染次数
- 每次渲染的时长

目的：方便的获得各组件的渲染情况，对于渲染频率过高或渲染耗时过长的组件可针对性的用 useMemo 之类的手段进行优化。可参考 [react Profile API](https://reactjs.org/docs/profiler.html)

**Comment by 7213** [comment]
#2042 和此issue相同
