### ISSUE TITLE
[BUG] cannot find createStore method

### ISSUE THREAD

**Issue by zhangzyi** [alibaba/rax#2122]
管理数据状态， 按照官方给出来的例子，在store.js中    createStore 打印是undefined

// store.js文件
import { createStore } from 'rax-app';
import count from './modules/count';
console.log('createStore', createStore) // undefined
const store = createStore({count});

export default store;

// count.js文件
const delay = (time) => new Promise((resolve) => setTimeout(() => resolve(), time));

export default {
  // 定义 model 的初始 state
  state: {
    count: 0
  },
  // 定义改变该模型状态的纯函数
  reducers: {
    increment(prevState) {
      return { count: prevState.count + 1 };
    },
    decrement(prevState) {
      return { count: prevState.count - 1 };
    },
  },
  effects: (dispatch) => ({
    async decrementAsync() {
      await delay(10);
      dispatch.counter.decrement();
    },
  }),
}

**Comment by SoloJiang** [comment]
可以通过 github 提供下代码仓库吗

**Comment by SleepDevil** [comment]
> 可以通过 github 提供下代码仓库吗

我也遇到了这个问题，发现原因为：.rax文件夹下的index.ts文件与之前不同了，少了
```
import { createStore } from '@ice/store';
```
以及其他相关代码。

**Comment by SoloJiang** [comment]
> > 可以通过 github 提供下代码仓库吗
> 
> 我也遇到了这个问题，发现原因为：.rax文件夹下的index.ts文件与之前不同了，少了
> 
> ```
> import { createStore } from '@ice/store';
> ```
> 
> 以及其他相关代码。

可以提供给下对应代码

**Comment by SleepDevil** [comment]
![image](https://user-images.githubusercontent.com/55879038/117650299-20163f00-b1c3-11eb-8263-4ac8ad132aec.png)
![image](https://user-images.githubusercontent.com/55879038/117650383-37edc300-b1c3-11eb-97ba-2824f1846da8.png)
这是两个不同版本的raxjs项目，项目的.rax文件夹下的index.ts文件内容不同。以前的`import { createStore } from 'rax-app';`最终会引入.rax文件夹下的index.ts里的`import { createStore } from '@ice/store';`
