### ISSUE TITLE
[Question]有没有小程序share功能的使用文档，没有找到

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2126]
求助。
https://rax.js.org/docs/guide/syntax-constraints

import { usePageShare } from 'rax-app';
好像没有这个方法。

**Comment by waylon-gmail** [comment]
if (isWeChatMiniProgramEnv) {
      wx.showShareMenu();
      addNativeEventListener('onShareAppMessage', handleOnShareAppMessage);
      registerNativeEventListeners(Index, ['onShareAppMessage']);
    }

**Comment by waylon-gmail** [comment]
addNativeEventListener('onShareAppMessage', handleOnShareAppMessage);

const handleOnShareAppMessage = (res) => {
 // 这里取不到state变化后的数据，只会取到初始化的数据，不知道该怎么获取。
}

**Comment by ChrisCindy** [comment]
看一下你这个函数定义的地方是否有问题，导致出现闭包，获取的是 state 的旧数据。
