### ISSUE TITLE
[Feature] 迫切希望 Rax 能支持录音和蓝牙功能。录音很多场景都要用到，蓝牙打印也有业务需求。

### ISSUE THREAD

**Issue by ymw2017** [alibaba/rax#2127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SoloJiang** [comment]
什么容器？

**Comment by ymw2017** [comment]
类似微信长按录音那种。

**Comment by SoloJiang** [comment]
你的代码是想投放到哪个容器？微信小程序还是 Web？

**Comment by ymw2017** [comment]
@SoloJiang  不好意思忘了回复，录音功能需要投放到web上，然后以文件的形式上传到后台，用户可以在线播放。
web应用需要接入“浙里办”App和支付宝浙里办小程序中。

**Comment by DOBEEE** [comment]
录音相关API 目前已经开发完成，预计下周发布，蓝牙相关也在计划中，预计6月中旬发布

**Comment by DOBEEE** [comment]
@uni/recorder@1.0.0-beta 录音api beta 已发布  
文档：https://universal-api.js.org/packages/media/recorder
欢迎试用

**Comment by SoloJiang** [comment]
正式版已全部支持
