### ISSUE TITLE
[Question]现在和ice有点混乱了

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2131]
目前公司有
- pc端 to b后台 需要用到微前端方案
- 移动端 普通应用
- 小程序
- app（未来）

然后，pc用ice无可厚非，因为需要微前端方案

但是客户端跨端就很疑惑
因为理论上需求就是构建出不同平台产物

换句话

pc更需要框架和业务方案
客户端需要构建方案

——

那ice和rax能否再整合一下

即最终的想法就是
- 使用ice框架
- 集成rax及karken的多端构建能力

真正实现一份代码多端运作，包括构建环节

**Comment by SoloJiang** [comment]
Rax App 的目标就是整体构建体验和 icejs 一致，使用 Rax 作为 DSL 构建；我理解你的想法是想通过 React 来写无线端？

**Comment by xmsz** [comment]
> Rax App 的目标就是整体构建体验和 icejs 一致，使用 Rax 作为 DSL 构建无线端应用；我理解你的想法是想通过 React 来写无线端？

没错
- 构建环节（创建、工程配置、构建等）统一cli工具
- 直接使用react来写无线端、不需要rax组件或者其他专属于跨端的要求
-

**Comment by SoloJiang** [comment]
- 本质上 Rax 作为 DSL 来写无线端，是可以针对无线场景做对应优化的，有些东西使用 React 可能没法满足诉求，1. 轻量；2. 稳定性；3. 事件绑定的机制，能够更好的处理小程序场景
- 其实 Rax App 和 icejs 的底层构建能力是复用的，只是 Rax App 上层有一些针对多端场景的扩展
- Rax 组件，如果不是有投放 weex 的诉求，是更推荐用 Web 标签的，目前小程序和 kraken 也都是朝着这个标准去做的
- Rax DSL 面向未来也会在 API 等使用层面更加靠近 React，能够做到最大化复用 React 生态

**Comment by SoloJiang** [comment]
也就是，面向社区开发者，我们未来的计划是，添加官方兼容的 React 的插件，就可以直接在项目里 `import React from 'react'` 这样无感知的使用 Rax

**Comment by SoloJiang** [comment]
没啥问题，我就关闭这个 issue 了？

**Comment by xmsz** [comment]
> 没啥问题，我就关闭这个 issue 了？

ok
