### ISSUE TITLE
[BUG]<TextInput />组件同时设置maxLength和 keyboardType属性的时候，长度限制不起作用。

### ISSUE THREAD

**Issue by ymw2017** [alibaba/rax#2132]
TextInput 组件同时设置maxLength={11} 和 keyboardType={numberic} 属性的时候，长度限制不起作用，可以无限输入，如果不设置keyboardType，那长度限制就有效。

**Comment by SoloJiang** [comment]
这是表达什么？

**Comment by SoloJiang** [comment]
@ymw2017 什么端？

**Comment by ymw2017** [comment]
> 
> 
> @ymw2017 什么端？

web端，开发H5应用，想在TextInput 中设置属性限制手机号只能输入11位纯数字的时候发现。

**Comment by ymw2017** [comment]
请问老师是否能复现这个问题？

**Comment by ChrisCindy** [comment]
https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome

参考该回答，keyboardType 设置为 numeric 时 input type 被设置为 number。此时 maxLength 失效为默认表现。解决方案亦可参考上方回答。
