### ISSUE TITLE
[Question]有没有什么好的办法兼容react默认导入React而不是{createElement}？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2133]
背景
- 引用其他React项目的组件，普通react组件都是直接`import React from 'react'`，但是rax如果引用了这个组件就会报错，没办法直接使用。从而导致无法复用其他组件，明明只是引入jsx的方式不同
- 保存一致的习惯，大部分react项目都是`import React from 'react'`，在rax则变成`import {createElement} from 'react'`，不仅麻烦而且有心智负担

想要的
- 在rax中直接使用`import React from 'react'`
- 扩展`build-plugin-rax-compat-react`，现在只是alias的功能，希望可以支持编译`import React from 'react'`的写法
- 其他方式解决复用其他react组件

**Comment by SoloJiang** [comment]
大部分的回答和 https://github.com/alibaba/rax/issues/2131 类似，本质上 Rax 是类 React DSL，而不是 React 本身，可以参考社区内类似产品 Preact。所以想要兼容 React 还是需要通过 alias 的手段来做。
------------------
至于第一个问题，后续会通过支持 [jsx-runtime](https://github.com/alibaba/rax/pull/2101) 的方式省略掉引 `createElement` 这一步
