### ISSUE TITLE
[Question]upload只能加1张图片，如果一次要传2张图片，求大佬帮忙看看怎么弄

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2136]
upload只能加1张图片，如果一次同时要传2张图片，求大佬帮忙看看怎么弄

**Comment by DOBEEE** [comment]
受限于客户端限制，单次API调用都只支持单张上传，你可以尝试在chooseImage 之后，同时调用多次API，每个API 就是一个上传进程
