### ISSUE TITLE
[Question]SPA单页模式下如何获取urlSearch？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2137]
背景
- URL: http://192.168.31.82:3801/?appid=wx74b0880f3da14d84#/
- 想要获取appid
- 使用`getSearchParams`拿不到，因为spa模式下拿到的其实是hash里的query，这个表现没问题，但是不符合需求
- 使用`getHistory`拿到history，然后获取location，但location的search也是空的，也是因为spa的关系
- 将query放在search而不是hash的原因，原因有一些，例如和mpa保持一致，即用户输入的是http://192.168.31.82:3801/?appid=wx74b0880f3da14d84，更加的简洁而不需要带/#/

需求
- spa模式也拿到urlSearch

临时解决
- web使用location直接获取，但是不知确定其他端是否可以这样做，旧的习惯还是先拿history

**Comment by SoloJiang** [comment]
该场景建议使用 browser history

https://rax.js.org/docs/guide/spa-route#HashHistory%20%E4%B8%8E%20BrowserHistory

**Comment by xmsz** [comment]
> 该场景建议使用 browser history
> 
> https://rax.js.org/docs/guide/spa-route#HashHistory%20%E4%B8%8E%20BrowserHistory

我才发现我描述错了，把HashHistory 与 BrowserHistory直接变成spa和mpa了

因为BrowserHistory模式后端不乐意配合，没法搞

然后我看了下，确实只要路由模式是Hash，那通过history拿到的就是hash里的search，这个表现没问题


那我问题就剩一个

- 如果我直接拿浏览器的location，在小程序里是相同表现吗

**Comment by SoloJiang** [comment]
小程序里的 history 是面向 history 这个包抹平的

**Comment by xmsz** [comment]
> 小程序里的 history 是面向 history 这个包抹平的

我又和kbone搞混了... 


所以理论上，硬拿的话

只有web端可以通过window.location拿到url为`http://192.168.31.82:3801/?appid=wx74b0880f3da14d84#/`的真实search

而小程序没有window.location对象所以拿不到


所以最后的结论就是
- 使用BrowserHistory，后端同学愿意配合的情况下
- 只需兼容web端的情况下，使用window.location对象拿到真实location对象
- HashHistory下不要把query放在search上
