### ISSUE TITLE
[Question]如何设置react-router的alias

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2138]
背景
- 引用了一个包，这个包的一个文件引用了
```
import { useHistory, useLocation } from 'react-router';
```

- 然后rax里编译会报错(即使没有引用到这个包)
```
To install it, you can run: npm install --save react-router
```

- `build-plugin-rax-compat-react` 这个包只处理了react和react-dom，没有处理react-router

需求
- 如何兼容react-router
- 或者再没有使用到改文件的时候下，如何不出现依赖缺失提示

**Comment by SoloJiang** [comment]
先确定下这个包的 package.json 里是否依赖的了 react-router，另外路由相关的包建议使用 Rax 体系已经提供的

**Comment by SoloJiang** [comment]
Rax App 本身已经有前端路由，此时再引入 react-router 其实是冲突的

**Comment by xmsz** [comment]
> 先确定下这个包的 package.json 里是否依赖了 react-router，另外路由相关的包建议使用 Rax 体系已经提供的

嗯 这个包里依赖了react-router的包

用到的是{ useHistory, useLocation }这两个api

然后rax里只有getHistory，如果要自己封装一个还挺麻烦的

**Comment by SoloJiang** [comment]
我理解本质是获取 history 和 location，这个和有没有这两个 API 应该无关

**Comment by xmsz** [comment]
> 我理解本质是获取 history 和 location，这个和有没有这两个 API 应该无关

就是第三方的包用到了`react-router`，主要是{ useHistory, useLocation }这两个API，本质确实还是获取history

然后由于无法改动第三方包，且由于第三方包的导入方式
```
// index.js
export { default as useComponentApi } from './useComponentApi';
```
导致就算没有用到这个函数也还是会提示需要这个文件里的依赖



所以我想要通过alias的方式去兼容它

类似和react/react-dom一样用另外一个包去实现同样的api

然后希望rax官方可以直接提供，这样就很方便

**Comment by SoloJiang** [comment]
应该不会提供类似场景的兼容

**Comment by xmsz** [comment]
> 应该不会提供类似场景的兼容

好吧
