### ISSUE TITLE
[Question] SlideView 组件使用体验

### ISSUE THREAD

**Issue by ming995** [alibaba/rax#2140]
![image](https://user-images.githubusercontent.com/46031112/121280423-d7a88900-c908-11eb-9bb4-2a472465adf6.png)

想问一下 SlideView 滑动如何传递参数？感觉现有的事件都是不支持传递参数的。

业务场景：使用滑动删除交互，需要知道删除的是那一条数据，但是这个标识符无法传递

**Comment by lianmin** [comment]
所有的操作，都是需要在 leftActions 或者 rightActions 自行控制的。 
参考： https://rax.js.org/docs/components/meet-slide-view
![Uploading image.png…]()

**Comment by ming995** [comment]
但是从代码里看，leftActions里的onClick类型是ClickCallBack，这个类型又是只能返回布尔类型
那如果是一个列表展示，需要右滑删除，这个事件怎么知道删除的是列表的那一项呢？

**Comment by lianmin** [comment]
你需要给列表的每一项，绑定不同的 leftAction onClick 回调
