### ISSUE TITLE
[Question]build之后的路径问题

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2143]
新:
![image](https://user-images.githubusercontent.com/51048705/122249109-2783e300-cefb-11eb-9111-bb6c297ec49f.png)

旧：
![image](https://user-images.githubusercontent.com/51048705/122249206-3a96b300-cefb-11eb-963b-d4716170b5d5.png)

最近新建了一个项目，编译出来的路径与之前的工程差别很大，是个绝对路径，这是哪里出问题了，求助。

**Comment by waylon-gmail** [comment]
如果没有 .rax这个目录，新工程编译的结果是不是就不能用了

**Comment by ChrisCindy** [comment]
本地新建项目无法复现，提供一下你的复现代码哈

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/122346484-96a11c00-cf7b-11eb-90fb-331960333fa7.png)
问题出在这里，只要在这加上store, 就会变成这样。

**Comment by waylon-gmail** [comment]
估计是只能用全局的store，不能在页面里面建store。是这样吗？

**Comment by SoloJiang** [comment]
路径不一样是正确表现，现在的问题是在 windows 上渲染不出来？

**Comment by SoloJiang** [comment]
测了下，windows 也没问题

**Comment by waylon-gmail** [comment]
我的是mac电脑。

**Comment by waylon-gmail** [comment]
开始是能渲染的出来。我是有疑问，这个路径包含了.rax, 如果发布的话，服务器上不就没有.rax这个路径了吗？

**Comment by SoloJiang** [comment]
> 开发是能渲染的出来。我是有疑问，这个路径包含了.rax, 如果发布的话，服务器上不就没有.rax这个路径了吗？

此处这个路径只用作渲染的唯一标识而已

**Comment by waylon-gmail** [comment]
好的。后面有问题我再回来。
