### ISSUE TITLE
[Question]config.ts在微信小程序location为undefine

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2144]
![image](https://user-images.githubusercontent.com/51048705/122250981-b3e2d580-cefc-11eb-832e-201ad8b84691.png)

请问该怎么配置可以同时兼容web与小程序。

**Comment by SoloJiang** [comment]
1. 小程序只注入了 `window`，这里需要用 `window.location`
2. 小程序的 `location` 只是尽量对齐标准，像 host 之类的还是没有的
