### ISSUE TITLE
[Question]引入alifd css问题

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2145]
![image](https://user-images.githubusercontent.com/51048705/122260402-d2010380-cf05-11eb-9c33-b99e12d8d568.png)

@import '~@alifd/meet/es/core/index.css';

为什么这个前面不能加 ~
不加的话就是红色的。
![image](https://user-images.githubusercontent.com/51048705/122260498-ef35d200-cf05-11eb-915b-bfe27ea228e3.png)

**Comment by SoloJiang** [comment]
这个报错出现在 Web 还是小程序

**Comment by SoloJiang** [comment]
看了下红线的问题可能是编辑器的问题，解析 CSS 依赖，使用的是 https://github.com/postcss/postcss-import

**Comment by waylon-gmail** [comment]
用的webstorm，可能是编辑器问题。先关了。
