### ISSUE TITLE
[Question] navigate api 的url问题

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2148]
![image](https://user-images.githubusercontent.com/51048705/122640170-89795e00-d130-11eb-8be3-e29f885df2bd.png)

![image](https://user-images.githubusercontent.com/51048705/122640181-9ac26a80-d130-11eb-87cd-8d787bfbded7.png)

为什么navigate 在push的时候，小程序与web要使用不同的参数。比如，
 如果让url=path，那么web可以跳转，但是wx小程序不能跳转
 如果让url=source，那么wx小程序可以跳转，但是web不能跳转。

这样使用的时候很不方便，我们需要判断环境类型使用对应的参数。 如果能够统一使用path，由框架api负责其他的处理会不会比较好。

**Comment by waylon-gmail** [comment]
如果页面在tab上，push不会自动使用 switchTab.

**Comment by SoloJiang** [comment]
跳转建议使用 history 作为多端完全统一的方式，Navigate 本质是独立 API 无法去识别你的项目配置。你提到的 switchTab 这个场景确实没有很好的办法来做，未来框架层面可能提供统一的 switchTab 方法来描述这种行为。

**Comment by waylon-gmail** [comment]
好的。
