### ISSUE TITLE
rax-swiper使用的时候样式不显示

### ISSUE THREAD

**Issue by xutao961212** [alibaba/rax#2150]
当我使用rax-swiper在pc端使用时，页面样式消失，dom是加载了的(onSlideChange函数一直在执行)。

我尝试在build.json里面配置inlineStyle: false，被告知` Config key 'inlineStyle' is not supported `

当我在组件里面import 'rax-swiper/dist/index.css'，页面也无法正常显示样式。

请问，我改如何配置rax-swiper的样式，让它正常使用呢？

**Comment by temp-cc** [comment]
写了个demo试了下 貌似不需要引入外部样式表啊
`import { createElement } from 'rax';
import { Swiper, SwiperSlide } from 'rax-swiper';

export default function Home() {
  return (
    <Swiper
      style={{
        height: 50
      }}
      pagination={{ clickable: true }}
    >
      <SwiperSlide key="1">Slide 1</SwiperSlide>
      <SwiperSlide key="2">Slide 2</SwiperSlide>
      <SwiperSlide key="3">Slide 3</SwiperSlide>
      <SwiperSlide key="4">Slide 4</SwiperSlide>
    </Swiper>
  );
}
`
[
![image](https://user-images.githubusercontent.com/38695280/122743089-3c74c380-d2b9-11eb-8775-7dedf5eae28d.png)
](url)
我觉得这样显示符合预期啊

**Comment by temp-cc** [comment]
写了个demo试了下 貌似不需要引入外部样式表啊
```JSX
import { createElement } from 'rax';
import { Swiper, SwiperSlide } from 'rax-swiper';

export default function Home() {
  return (
    <Swiper
      style={{
        height: 50
      }}
      pagination={{ clickable: true }}
    >
      <SwiperSlide key="1">Slide 1</SwiperSlide>
      <SwiperSlide key="2">Slide 2</SwiperSlide>
      <SwiperSlide key="3">Slide 3</SwiperSlide>
      <SwiperSlide key="4">Slide 4</SwiperSlide>
    </Swiper>
  );
}

```
我觉得还算符合预期
![image](https://user-images.githubusercontent.com/38695280/122743629-bb69fc00-d2b9-11eb-9e1a-c8fef9f50863.png)

**Comment by temp-cc** [comment]
写了个demo试了下 貌似不需要引入外部样式表啊
```JSX
import { createElement } from 'rax';
import { Swiper, SwiperSlide } from 'rax-swiper';

export default function Home() {
  return (
    <Swiper
      style={{
        height: 50
      }}
      pagination={{ clickable: true }}
    >
      <SwiperSlide key="1">Slide 1</SwiperSlide>
      <SwiperSlide key="2">Slide 2</SwiperSlide>
      <SwiperSlide key="3">Slide 3</SwiperSlide>
      <SwiperSlide key="4">Slide 4</SwiperSlide>
    </Swiper>
  );
}
```
![image](https://user-images.githubusercontent.com/38695280/122743976-23b8dd80-d2ba-11eb-80fc-129bec1104c6.png)

**Comment by SoloJiang** [comment]
@xutao961212 可以贴一下你的 build.json，inlineStyle 模式下不支持 rax-swiper
