### ISSUE TITLE
[Question]models中的state如何声明才能满足typescript检查

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2151]
![image](https://user-images.githubusercontent.com/51048705/122684891-d3e70180-d23a-11eb-9500-4736e36d2787.png)

这里的变量想要声明一下类型，但是不知道该怎么写。有没有例子请大佬帮帮忙。非常感谢。

**Comment by SoloJiang** [comment]
https://rax.js.org/docs/guide/mpa-store

**Comment by waylon-gmail** [comment]
看了一下，还是不太明白。State的里面的类型如何定义。
export default {
 state: { testData: {
    key1: 'value1',
    key2: 'value2',
   key3: undefined // 这里面的值实际上是个对象，后期赋值，初始化无值， key3: {key31: 'value'}
 } }
}

testData 当再外部使用testData的时候，如何能定义 testData的类型。

比如 testData.key3.key31 ==> 实际上不会提示key31

**Comment by waylon-gmail** [comment]
如果这边初始化，把内部的字段都写出来，是可以提示的。但是初始化我们是想先定义一个undefined，后面有值了再用。

**Comment by SoloJiang** [comment]
这里类型定义的时候，就需要考虑 `undefined | YOUR_TYPE` 吧

**Comment by waylon-gmail** [comment]
就是不知道怎么写类型定义。写在哪里。
export default {
     state: xxx,  // 这里的xxx是初始化的值，不是类型定义。不知道类型定义该写在哪里。
}

**Comment by waylon-gmail** [comment]
model.ts

export default {
   state: {
      currentUser: undefined, // 这里是初始化的值
   }
}

经过后端获取后
currentUser = {
    id: 1,
    extend: {
       address: '',
    }
}

使用的地方
  const userState = store.useModelState('userModels');
  const { currentUser } = userState;

currentUser.extend.address // 这里识别不到类型。

因为上面state那边 currentUser初始化值是undefined.
不知道怎么定义 state里面 currentUser的类型。

求大佬帮忙看下。

**Comment by waylon-gmail** [comment]
![Screen Shot 2021-06-22 at 3 13 54 PM](https://user-images.githubusercontent.com/51048705/122880371-84a0ee00-d36c-11eb-9d2e-5ddaf64c0386.png)

**Comment by waylon-gmail** [comment]
ModelConfig 能不能暴露出来一下。

**Comment by luhc228** [comment]
或者在你的 `./models/user-models` 中定义类型，比如：

```ts
// ./models/user-models.ts
interface IModel {
   state: {
     count: number | string | object
   }
}
const model: IModel = {
    state: {
      count: 0
    }
}

export default model;
```
