### ISSUE TITLE
[Question]meet-list高度 --list-item-height

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2153]
![image](https://user-images.githubusercontent.com/51048705/122812725-a1a1d680-d304-11eb-944c-964040aaf9f0.png)

--list-item-height ===> 文档错了
--list-item-min-height ==> 正确的

https://rax.js.org/docs/components/meet-list

**Comment by lianmin** [comment]
感谢反馈，我们将在下个正式版本中修正

**Comment by lianmin** [comment]
已修复
