### ISSUE TITLE
[Question]@alifd/meet组件的使用问题

### ISSUE THREAD

**Issue by gavin0510** [alibaba/rax#2154]
@alifd/meet组件不能正常使用
![image](https://user-images.githubusercontent.com/15063672/122873317-312aa200-d364-11eb-9b0a-fd022ea1a44b.png)

**Comment by waylon-gmail** [comment]
你这个View也不能正常使用。跟@alifd/meet好像没有啥关系

**Comment by waylon-gmail** [comment]
是不是文件拓展名不是 tsx，或者jsx

**Comment by gavin0510** [comment]
仅 @alifd/meet 组件有问题。文件扩展名是 tsx，其它的都正常

**Comment by gavin0510** [comment]
View及其它组件是能正常使用的

**Comment by gavin0510** [comment]
@alifd/meet 组件中不能放子组件，否则就有问题，不能正常显示。
![image](https://user-images.githubusercontent.com/15063672/122882366-af8c4180-d36e-11eb-8935-ac29a673ad4a.png)
![image](https://user-images.githubusercontent.com/15063672/122882573-ea8e7500-d36e-11eb-924c-3ed2d6bf6571.png)

**Comment by ChrisCindy** [comment]
@gavin0510 给一下详细的描述，哪个组件里不能放哪个子组件，出现了什么渲染问题？另外是 Web 端还是小程序端？

**Comment by ajunzai** [comment]
@gavin0510 你是修复这个问题了吗，还是一直在报错?可以正常显示了而已

**Comment by lianmin** [comment]
@gavin0510 升级下 @alifd/meet@2.3.8-beta.1 ，ts 的问题我整体修复了一波
