### ISSUE TITLE
[Question]typescript onGetUserInfo

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2155]
![Screen Shot 2021-06-22 at 2 25 18 PM](https://user-images.githubusercontent.com/51048705/122878711-a13c2680-d36a-11eb-8c87-d350e9366537.png)

**Comment by ChrisCindy** [comment]
目前暂时没有针对原生小程序组件的 types 定义。解决方法可以是：

1. 使用 ts ignore
2. 使用 fusion mobile 的 button 组件：https://rax.js.org/docs/components/meet-button
3. 换用 jsx

**Comment by waylon-gmail** [comment]
临时方案：
declare namespace JSX {
  interface IntrinsicElements {
    button: any;
  }
}
