### ISSUE TITLE
[Question]能否支持React Native端

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2157]
背景
- 我们有个项目需要写Android客户端，是个中型项目
- 原先打算用kraken去写，但是一来需要填坑、二来需要学习Flutter
- RN也要填坑但好在已经有很多解决方案
- Flutter最不适应的是Dart的写法，特别是写视图
- 所以感觉更适合我们的是React Native（UniApp这种肯定不会考虑）

然后我们还是想在Rax的框架上开发

所以还是希望可以支持一下RN，这样可以满足更多需求

然后我们的备选方案是Taro，已经支持了RN，不过还没开始踩坑不知道情况如何

当然最次的备选方案就是 Flutter + Webview，可以快速解决需求，但加载速度估计会被骂死

**Comment by SoloJiang** [comment]
推荐使用 Kraken，Rax 没有计划去支持 RN

**Comment by SoloJiang** [comment]
如果你对 RN 有一定的基础，可以尝试基于 Rax 的多端渲染机制支持下 RN，面向未来我们还是推荐基于 Flutter 的 Kraken

**Comment by xmsz** [comment]
好吧 那我们自己再讨论看看
