### ISSUE TITLE
[Question]有没有API可以动态修改title

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2159]
类似 微信小程序 wx.setNavigationBarTitle

**Comment by ChrisCindy** [comment]
Uni API 封装了常见的 API，但是微信、支付宝等提供的 wx.xxx 和 my.xxx 也都可以直接在 Rax 中使用。

**Comment by imsobear** [comment]
@ChrisCindy 所以 uni api 这一层会封装吗？我印象里有人提过类似需求。

**Comment by ChrisCindy** [comment]
> @ChrisCindy 所以 uni api 这一层会封装吗？我印象里有人提过类似需求。

@imsobear @waylon-gmail 可以封装，已经安排在 Uni API 的需求列表中。

**Comment by waylon-gmail** [comment]
最好能同时修改web的title。

**Comment by ChrisCindy** [comment]
Web 会纳入考虑的。
