### ISSUE TITLE
[Question]rax 不支持redux吗？

### ISSUE THREAD

**Issue by JackFeng7** [alibaba/rax#2162]
我在使用class方式进行状态管理的时候，感觉学习成本好高。
个人感觉，redux那一套写法很方便，特别是在状态使用和状态更新操作上。
举个例子：class组件上使用多个model数据时，需要一直的嵌套withModel。
强烈建议支持使用者自己搭建redux。

**Comment by SoloJiang** [comment]
支持 redux~可以配合 rax-redux 一起使用
