### ISSUE TITLE
[Question]web onScroll参数值与小程序不一样

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2164]
![image](https://user-images.githubusercontent.com/51048705/123993308-e6152c80-d9fe-11eb-9c77-3ece9206531b.png)
![image](https://user-images.githubusercontent.com/51048705/123993393-f9c09300-d9fe-11eb-9bd3-bff88907645b.png)

web没有e.detail参数 ==》 undefined.

**Comment by fyangstudio** [comment]
https://github.com/raxjs/rax-components/blob/master/packages/rax-scrollview/src/miniapp/index.tsx#L38

滑动信息可以通过 nativeEvent 获取，不建议读取 detail 和 target
