### ISSUE TITLE
[Question]设置spa和mpa是否会对多端产生影响

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2165]
问题
- 如果我给不同端设置不同模式会不会有兼容问题
- 还是我必须所有端都设置成同一种
- 小程序和Kraken可以设置成spa吗
- 我看默认都是mpa，如果我设置成spa会不会有什么影响？

**Comment by imsobear** [comment]
- 不推荐不同端 MPA SPA 混用，可能会出现各种异常
- 小程序应用生成的 Web 页面默认就是 SPA 也只能是 SPA，否则没法跟小程序的运行生命周期等保持一致

**Comment by xmsz** [comment]
> * 不推荐不同端 MPA SPA 混用，可能会出现各种异常
> * 小程序应用生成的 Web 页面默认就是 SPA 也只能是 SPA，否则没法跟小程序的运行生命周期等保持一致

好的，我们没有特殊需求SPA和MPA都可以，那还是全部SPA好了

那kraken呢，可以使用SPA吗？

**Comment by imsobear** [comment]
我们是推荐两种模式：

- 基于小程序标准的跨端应用，对应的 Web 产物是 SPA，同时不支持构建出 Kraken、Weex 之类的产物（没诉求）
- 基于 Web 标准的跨端应用，可以构建出 Kraken、Weex 产物，默认推荐是 MPA，用 SPA 理论上也可以

**Comment by xmsz** [comment]
> 我们是推荐两种模式：
> 
> * 基于小程序标准的跨端应用，对应的 Web 产物是 SPA，同时不支持构建出 Kraken、Weex 之类的产物（没诉求）
> * 基于 Web 标准的跨端应用，可以构建出 Kraken、Weex 产物，默认推荐是 MPA，用 SPA 理论上也可以

因为我们想搞一个「养成类」的应用，因为一些特殊原因，所以计划

先用web端开发，然后后续支持小程序，最后需要支持手机客户端

那我们先用SPA
