### ISSUE TITLE
[Question]组件都支持Kraken吗

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2166]
我看到都写了 Web / Weex / 阿里小程序 / 微信小程序 / 字节跳动小程序

但是没写Kraken，是不是不支持？

还有我看到swiper不能支持kraken，这是为啥

还有UniApi也都支持吗

还有@alifd/meet都支持吗？

**Comment by SoloJiang** [comment]
Kraken 是面向 Web 标准，所以大部分 API 和组件都可以正常使用，但是由于当前版本 Kraken 还不支持 css 外联样式，所以 rax-swiper 和 meet 暂时用不了，但 Kraken 有计划解决这个问题

**Comment by xmsz** [comment]
> Kraken 是面向 Web 标准，所以大部分 API 和组件都可以正常使用，但是由于当前版本 Kraken 还不支持 css 外联样式，所以 rax-swiper 和 meet 暂时用不了，但 Kraken 有计划解决这个问题

ok 👍🏻
