### ISSUE TITLE
[Question] Fusion Mobile  Input 组件 hasClear 在受控状态下无效

### ISSUE THREAD

**Issue by ming995** [alibaba/rax#2168]
hasClear 如何在受控下执行，现在貌似只是支持非受控下

**Comment by lianmin** [comment]
能贴下复现的 demo 代码吗，如下代码是正常的

```jsx
import { createElement, render } from 'rax';
import DriverUniversal from 'driver-universal';
import { Input } from '@alifd/meet';

const Demo = () => {
  return <Input placeholder="please input" defaultValue="init" hasClear />;
};

render(<Demo />, null, { driver: DriverUniversal });
```

**Comment by ming995** [comment]
![image](https://user-images.githubusercontent.com/46031112/124228024-23cc9f00-db3e-11eb-8d38-b3ee8940d57a.png)
我使用的是 value 属性，value的值是通过别的操作获取的

**Comment by lianmin** [comment]
> ![image](https://user-images.githubusercontent.com/46031112/124228024-23cc9f00-db3e-11eb-8d38-b3ee8940d57a.png)
> 我使用的是 value 属性，value的值是通过别的操作获取的

能否给个完整的 demo 呢？我本地测试一下
