### ISSUE TITLE
[Question]微信小程序下store中的数据翻页之后就丢失了

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2169]
微信小程序下store中的数据翻页之后就丢失了
https://rax.js.org/docs/guide/spa-store

A页面 --> push 到 B页面，A页面的store中state数据都被清空了。

**Comment by waylon-gmail** [comment]
是因为A页面push到B页面的时候app.ts中的store初始值又触发了。被重置为初始的值。挺奇怪的。
  store: { 
    initialStates: {
      // 这里的 key 即对应 model 名称
      userModels: {
        userId: 9999999,
      },
    },
  },

**Comment by cryzzchen** [comment]
@waylon-gmail 
感谢 issue，BUG 已知晓，目前你可以先在 models/ 下初始化 store 的全局状态来避免这个问题。

**Comment by waylon-gmail** [comment]
还有一个问题，使用全局store的时候，如果后一个页面执行了 replace动作，前面页面的store的数据可能也会丢失。

**Comment by waylon-gmail** [comment]
请问这个会在哪个版本修复。

我想用这个初始化读取storage中的token，但是有时候token过期需要刷新一下，但是因为每次翻页这个token都会被置成初始读取的那个，所以不知道如何处理。

**Comment by SoloJiang** [comment]
这个问题需要改动较多底层代码，所以暂且先绕过下，现在不能确定什么时候能够修复

**Comment by cryzzchen** [comment]
@waylon-gmail https://rax.js.org/docs/guide/miniapp-store#%E5%85%A8%E5%B1%80%E7%8A%B6%E6%80%81 用这个写法来绕过多次初始化问题
