### ISSUE TITLE
[Question] registerNativeEventListeners 有点不明白

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2171]
https://rax.js.org/docs/guide/page-lifecycle-and-event-handler

// state只要发生变化，就会一直触发。
if (isMiniApp) {
  registerNativeEventListeners(Index, ['onReachBottom']);
}

  useEffect(() => {
    if(isMiniApp) {
      // 开始监听 onReachBottom 事件 - 打开页面时一次
      addNativeEventListener('onReachBottom', handlePageReachBottom);
    }
    return () => {
      if (isMiniApp) {
      // 移除onReachBottom 事件的监听器 - 关闭页面时一次
      removeNativeEventListener('onReachBottom', handlePageReachBottom);
    }
    }
  }, []);

addNativeEventListener - 打开页面时一次
removeNativeEventListener - 关闭页面时一次
registerNativeEventListeners -state只要发生变化，就会一直触发 (这个方法为什么不是跟add一样，放在useEffect中，或者用useEffectOnce只触发一次呢？是这个方法触发多少次都没有关系是吗？)

**Comment by SoloJiang** [comment]
原理上，`registerNativeEventListeners` 其实不是运行时方法，我们是通过文件扫描的方式发现该页面组件用到了这个方法，然后通过 AST 解析到需要注册哪些生命周期，最后再添加到 `Page` 对象上，比如的上述的代码，用到了 `registerNativeEventListeners(Index, ['onReachBottom'])`，最终到小程序上就是：

```javascript
Page({
  onReachBottom() {
     // 派发事件
  }
});
```

如果没有注册的事件，最终不会出现在 `Page` 对象上，比如上述示例，`onPageScroll` 就不会被注册在 `Page` 上
