### ISSUE TITLE
[Question]x-if 会导致概率性同级别的另一个元素显示不出来

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2172]
![image](https://user-images.githubusercontent.com/51048705/124633114-8e236d80-deb7-11eb-90ee-3a6cea53d0a5.png)

goods-price-cont  这个view显示不出来。升级了rax-app到最新版本后出现的，之前的版本貌似没有这个问题。

x-for 也有类似的问题(之前的版本也有问题)。当x-for附近有同级别的View，这个view大概率会显示不出来。

它们的外层是 display: flex;  flex-direction: row; 的时候好像概率特别高。

        .money-box {
          margin: 0;
          display: flex;
          flex-direction: row;
          align-items: flex-end;

          .goods-price-cont {
            display: flex;
            flex-direction: row;
            align-items: center;

            .price-sign {
              color: #ff495e;
              font-size: 13px;
            }

            .goods-price-num {
              color: #ff495e;
              font-size: 20px;
            }
          }

          .line-price {
            padding-top: 3px;
            text-decoration: line-through;
            margin-left: 6px;

            .text {
              font-size: 12px;
              color: #999;
            }
          }
        }

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/124633416-d773bd00-deb7-11eb-92f0-01f750640586.png)

为了解决上述问题，只好再套一层view把 x-if 弄到一个独立模块里。或者改用 {xxx && <></>}

但是代码中很多地方都要改。建议能修复这两 个问题。

**Comment by waylon-gmail** [comment]
以上问题，在web下没问题。在微信小程序下出现。

**Comment by ChrisCindy** [comment]
可否抽离业务场景提供一个稳定复现的最小 demo

**Comment by waylon-gmail** [comment]
弄了很久都无法重现。最后发现，只要有Dialog在，问题才会发生。demo已经ready。
https://github.com/waylon-gmail/rax-demo

如果去掉布局中的Dialog，则所有问题都消失。我在另外一个issue上提的问题，也是因为那个页面有Dialog导致的。

![image](https://user-images.githubusercontent.com/51048705/126283838-16a56d33-aed0-4951-ab15-65bb3ec38dca.png)
![image](https://user-images.githubusercontent.com/51048705/126283872-0817e34c-e47a-47f5-b8e8-9e549d21870d.png)

当有Dialog在的时候，如果没有使用x-if，没有问题，如果在x-if外面再套一层<View><View x-if={xxx}></View></View>
则也可以解决问题。但是有些情况怎么弄都不行。

https://github.com/alibaba/rax/issues/2181
比如这边这个问题的情况。

**Comment by waylon-gmail** [comment]
麻烦大神帮忙分析一下。 谢谢。

**Comment by ChrisCindy** [comment]
@waylon-gmail 渲染问题已经修复，注意一下 miniapp-render 这个依赖包升级到最新的 2.8.3 版本即可。（注意处理一下 package-lock.json 文件）
