### ISSUE TITLE
[Question]tab的第三个页面跳转到tab的第一个页面，底部的tab按钮不会跳过去，页面会正常跳过去

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2173]
小程序： 正常
web端：tab的第三个页面跳转到tab的第一个页面，底部的tab按钮不会跳过去，页面会正常跳过去

**Comment by wjq990112** [comment]
能给一个最小复现 demo 吗？ @waylon-gmail

**Comment by waylon-gmail** [comment]
![1626436830538](https://user-images.githubusercontent.com/51048705/125944284-ccff6ba0-f229-4747-bb8e-25e494cf064f.jpg)

git@github.com:waylon-gmail/rax-demo.git

**Comment by wjq990112** [comment]
有问题的不是 Tab 栏按钮没有正常跳转嘛？最小复现 Demo 也要包括一下 Tab 栏吧？ @waylon-gmail

**Comment by SoloJiang** [comment]
已经确认是 bug，下一个版本修复该问题

**Comment by waylon-gmail** [comment]
好的。之前账号登录错误没有收到回复提示。demo里面有tab的配置。感谢。
