### ISSUE TITLE
[Question]RichText组件在微信小程序下和web下ui差距较大。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2174]
`<p>123</p>`

p {
    display: block;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
}

在web下，p标签的间距巨大。
在微信小程序下就不存在p标签了。

**Comment by ChrisCindy** [comment]
富文本中的 p 标签如何渲染由小程序容器层决定，不是 Rax 框架控制的。
