### ISSUE TITLE
[Question]web构建出来的静态资源地址直接服务器上无法访问

### ISSUE THREAD

**Issue by cielyic** [alibaba/rax#2175]
背景
- 有一个1.png图片放在/public下
- 代码引用是'/web/1.png'
- 我构建到线上是，是将web里的内容当做根目录
- 那这样就访问不到web

需求
- 如何解决这种需求

**Comment by wjq990112** [comment]
能给一个最小复现 demo 吗？

**Comment by cielyic** [comment]
> 能给一个最小复现 demo 吗？

有时间再给

**Comment by SoloJiang** [comment]
用 `process.env.PUBLIC_URL` 来设置引用时的前缀，参考文档：https://rax.js.org/docs/guide/public
