### ISSUE TITLE
[Question]model中的reducers中的prevState， 不是上一次state的值吗？

### ISSUE THREAD

**Issue by waylon-edmodo** [alibaba/rax#2178]
![image](https://user-images.githubusercontent.com/51694657/125185616-743baf00-e258-11eb-975b-3ef5486c0677.png)

![image](https://user-images.githubusercontent.com/51694657/125185624-7f8eda80-e258-11eb-86fd-140c7e19d3b3.png)

不知道为什么log打印出来是这个。好奇怪。跟官网的例子对不上。

![image](https://user-images.githubusercontent.com/51694657/125185655-a5b47a80-e258-11eb-8b90-84c497297771.png)

**Comment by waylon-gmail** [comment]
取不到 prevstate怎么办

**Comment by luhc228** [comment]
store 默认是开启了 [Immer](https://github.com/immerjs/immer)，会变成 Immutable 对象，所以你拿到的是被 Proxy 代理的对象。

如果你需要拿到原始的对象，你可以禁用掉 immer 

```js
const store = createStore(models, { disableImmer: false });
```

**Comment by waylon-gmail** [comment]
谢谢。
