### ISSUE TITLE
[Question]能否通过package.json.script直接指定平台进行构建

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2179]
背景
- 我需要构建web端和kraken端
- 大部分情况是在写web端，但是每次编译和构建都需要同时构建两个平台，构建速度慢很多
- 我想自己指定这次构建的平台，但又不想每次都去修改build.json文件内容

需求
- 例如：rax-app start --target=web => 只构建web端，但是build.json包含了多端的配置
- 或者：rax-app start --config=./build.web.json => 自己选择build.json的路径

**Comment by imsobear** [comment]
这两个能力貌似都有

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/125582938-23eea192-b972-4662-b0e3-c9fa35284c9e.png)

**Comment by imsobear** [comment]
@SoloJiang  --target 这个你确认下

**Comment by xmsz** [comment]
就是这个 是我昨天眼睛看花了 打扰了

**Comment by SoloJiang** [comment]
还可以开发阶段通过 `--dev-targets=web` 指定，文档好像有一次改丢了
