### ISSUE TITLE
[Question]微信小程序下有些布局会有问题，情况比较复杂

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2181]
web端没有问题：
![6061626362387_ pic](https://user-images.githubusercontent.com/51048705/125846272-40a94fb1-215d-4d49-b1c1-8d41bcc99679.jpg)

小程序端，会莫名出现问题：后面的模块会显示在前面的模块里。非常奇怪，目前还没找到方案解决它。先记录一下，后续统一弄demo出来。小程序下，布局经常出一些奇怪的问题，也不知道是不是我的写法问题。待查。疑难杂症。
![6051626362378_ pic](https://user-images.githubusercontent.com/51048705/125846519-889f0be6-1597-45fc-b578-36263e2a7d3d.jpg)
![6071626362426_ pic_hd](https://user-images.githubusercontent.com/51048705/125846535-d820e23a-b789-4f7d-b86c-f58ca205c637.jpg)

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/125847007-30ffa037-51ff-425d-8410-01486a1c82d4.png)
如果将子组件数据改到usestate中获取，微信小程序下数据加载不出来。web端正常。==》非所有组件，只是自定义的部分组件出现问题。

**Comment by ChrisCindy** [comment]
好的，后续有 demo 的话一起排查下这些问题。

**Comment by waylon-gmail** [comment]
移除 Dialog组件后，恢复正常。可是Dialog要用，不移除没有办法解决这个问题。

**Comment by waylon-gmail** [comment]
![image](https://user-images.githubusercontent.com/51048705/127146652-1c997899-8f6a-4440-b3b0-78a4863ccf60.png)
![image](https://user-images.githubusercontent.com/51048705/127146719-a30f82be-ddc4-4dd5-b868-f3a5e1651bb1.png)


import { Dialog } from '@alifd/meet';

小程序下： Dialog放入页面会引发很多布局问题。Dialog放的位置不同引发的问题也会不一样，会影响到其他的布局，实在不知道是什么原因，很多有dialog的页面都出问题。不放Dialog则全部恢复正常。

**Comment by waylon-gmail** [comment]
其中一种情况Demo： https://github.com/waylon-gmail/rax-demo

**Comment by waylon-gmail** [comment]
想到一个办法，把dialog放到判断里面，visible的时候才加入，问题解决。

```
      {
        dialogVisible && 
        <Dialog
          visible={dialogVisible}
        />
      }
```

**Comment by ChrisCindy** [comment]
demo 我来验证一下。

**Comment by ChrisCindy** [comment]
https://github.com/alibaba/rax/issues/2172
应该是同样的渲染问题，可以一起验证一下。
