### ISSUE TITLE
[Question]getSearchParams 在微信小程序下翻页后前一个页面的参数变了

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2184]
const searchParams = getSearchParams();

如果写在 page function 内部： 在微信小程序下翻页后前一个页面的参数变成了后一个页面的参数。

如果写在page fuction 外部: 参数就不会变，也有问题。

**Comment by SoloJiang** [comment]
小程序的架构对标的是 Web SPA，每个页面共用同一个 window，所以路由参数是同一引用

**Comment by swl880422** [comment]
Ok. 谢谢。

**Comment by waylon-gmail** [comment]
ok. 谢谢。
