### ISSUE TITLE
[BUG]rax-slider出现Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2185]
```
    <Swiper
      width="750"
      height="310"
    >
      <Swiper.Item>
     1
      </Swiper.Item>
      <Swiper.Item>
     2
      </Swiper.Item>
    </Swiper>

```

各种滑动几下以后

```
Uncaught TypeError: Cannot read property 'current' of undefined
    at Slider._this.onSwipe (index.js:114)
    at Object.onPanResponderMove (SwipeEvent.js:135)
    at HTMLDivElement.onTouchMove (index.js:381)

```

![image](https://user-images.githubusercontent.com/5879146/126153454-9e4417c5-43b7-411d-8f2a-2e9b6fe461fc.png)

**Comment by wjq990112** [comment]
可以给一个简单的 demo 吗？方便我们调试 @xmsz

**Comment by xmsz** [comment]
> 可以给一个简单的 demo 吗？方便我们调试 @xmsz



https://github.com/xmsz/demo-20210722

核心代码就是

```
import { createElement } from 'rax';

import Swiper from 'rax-slider';

function Home() {
  return (
    <Swiper width="750" height="310">
      <Swiper.Item>1</Swiper.Item>
      <Swiper.Item>2</Swiper.Item>
    </Swiper>
  );
}

export default Home;

```

复现
- 一直滑动即可

![image](https://user-images.githubusercontent.com/5879146/126587790-825735c2-5d8e-4778-96a2-b617525c5b9c.png)

**Comment by wjq990112** [comment]
已经定位问题，正在修复，感谢反馈。

**Comment by wjq990112** [comment]
@xmsz 如果你的项目中只需要支持 Web/小程序，推荐使用 rax-swiper，rax-slider 存在一些设计上的缺陷，需要择期重构。

**Comment by xmsz** [comment]
> @xmsz 如果你的项目中只需要支持 Web/小程序，推荐使用 rax-swiper，rax-slider 存在一些设计上的缺陷，需要择期重构。

我想在Kraken里用 不过除了这个问题rax-slider在kraken还是跑不起来 滑动非常的卡 动画会丢失 应该是kraken的问题

**Comment by wjq990112** [comment]
@xmsz 这个问题修复了，可以试一试了，感谢反馈。
