### ISSUE TITLE
[Question]rax-slider高度如何设置成屏幕高度

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2186]
背景
- 我需要一个全屏的rax-slider
- 我设置高度'100vh' => 无效
- 我设置高度'100%' => 无效
- 我设置高度'window.screen.height' => 不符合
- 我设置高度'window.screen.height * window.pixelRadio' => 只有iphone6符合
- 我设置高度'window.screen.height * 2 => 真机不符合

需求
- 可以设置100%
- 可以设置100vh
- 或者其他办法解决需求

**Comment by waylon-gmail** [comment]
纯粹设置css没有办法生效。必须在组件上设置一个height，我之前也研究了很久。
···
<Slider className="ld-slider" height={'374px'} 
···

**Comment by waylon-gmail** [comment]
如果要全屏，可以直接用快捷方式：

```
    Slider.show({
      items,
      activeIndex: index,
      // only works in web
      onClose: () => {
        // only works in web
      },
    });
```

**Comment by wjq990112** [comment]
按照楼上的同学的方法，这个问题是否解决了？ @xmsz

**Comment by wjq990112** [comment]
我们在小程序和 Web 项目中使用 rax-swiper。

**Comment by xmsz** [comment]
> 按照楼上的同学的方法，这个问题是否解决了？ @xmsz

还是希望可以传递`100vh`或`100%`这样的值比较方便

或者当我传传入真实的屏幕高度时表现是正常


rax-swiper什么时候支持kraken，rax-slider确实有点不好用

**Comment by wjq990112** [comment]
rax-swiper 是基于 swiper.js 封装的，使用到了外联样式，由于 Weex/Kraken 暂不支持样式外联，因此还没办法在 Kraken 上使用。

**Comment by xmsz** [comment]
> rax-swiper 是基于 swiper.js 封装的，使用到了外联样式，由于 Weex/Kraken 暂不支持样式外联，因此还没办法在 Kraken 上使用。

好吧 现在就希望rax-slider能先用一下

**Comment by wjq990112** [comment]
看了一下 rax-slider 内部的代码实现，由于使用的是内联样式，涉及到的计算较多，暂时还是只支持 rpx/px，想要实现高度与屏幕高度一致，推荐传入 `window.innerHeight * 2`，我测试了一下真机上是符合的。

**Comment by xmsz** [comment]
> window.innerHeight * 2
ok 那我还是先临时用一下 

window.innerHeight * 2 在真机（iphone11微信）高度不正确，不确定是什么原因
然后我现在为了实现效果

- slider就不管它实际多高了
- 本来基于slider定位的全部改为fixed(反正是全屏)
- slider里面的item用vh单位

这样是可以实现效果，但是写起来比较麻烦

**Comment by wjq990112** [comment]
这个组件后面找个时间重构一下，目前是推荐使用 rax-swiper 了，kraken 未来会支持 CSS，可以期待一下。

**Comment by xmsz** [comment]
> 这个组件后面找个时间重构一下，目前是推荐使用 rax-swiper 了，kraken 未来会支持 CSS，可以期待一下。

ok cool
