### ISSUE TITLE
[Question]Slider(横向图片切换) 设置autoplay, 纵向滚动的时候，页面闪烁厉害

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2188]
微信小程序下:

Slider(横向图片切换) 设置autoplay, 纵向滚动的时候，页面闪烁厉害。

```
<View>
   <ScollView>
<View>
   <Slider />
   <View>
      复杂的ui，
   </View>
</View>
</ScrollView>
<View /> // 悬浮按钮， 只有在scrollview滚动到距离头部200的时候才显示
</View>
```

如果这时候，scrollview再监听滚动距离，然后根据滚动距离显示某个按钮， onScroll={handleScroll}， 页面就闪烁的更厉害了。
因为滚动的时候会不停的setState。

不知道有没有好的办法，目前只能是 关闭Slider的autoplay， scrollview的滚动距离也不监听了。

**Comment by ChrisCindy** [comment]
关于 rax-slider 的问题，可以考虑删除模板中的 current 属性，看看闪烁问题是否还存在。参考文档：https://rax.js.org/docs/guide/performance-optimization#%E5%88%A0%E9%99%A4%E7%BB%84%E4%BB%B6%E5%B1%9E%E6%80%A7%E5%8F%8A%E4%BA%8B%E4%BB%B6

关于 onScroll 频繁触发 setState 的问题，需要开发者注意避免，这个是在原生小程序以及 web 都可能存在的问题。

**Comment by waylon-gmail** [comment]
onScroll 触发 setState 。 只触发一次也会闪一下。

**Comment by waylon-gmail** [comment]
swiper?

**Comment by waylon-gmail** [comment]
"wechat-miniprogram": {
    "template": {
      "swiper": {
        "delete": {
          "props": ["current"],
        }
      }
    }
  }

**Comment by waylon-gmail** [comment]
配置之后，好像slider滚动的时候，纵向滚动就会停下。不知道有没有配错，现象是这样。没有像之前那样闪烁。
