### ISSUE TITLE
[Question]网络请求没结束，切换页面概率性报错 __isPendingForceUpdate

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2189]
![image](https://user-images.githubusercontent.com/51048705/126347904-d28c767f-1fd6-410a-a17e-2d0c7bf35ba2.png)

**Comment by ChrisCindy** [comment]
这个问题的出现一般是因为组件被销毁后还在执行 setState 的操作，需要避免该情况发生

**Comment by SoloJiang** [comment]
rax v1.2.1 下个版本将不会针对此类场景报错，策略调整为：开发时 warning，生产环境静默

**Comment by waylon-gmail** [comment]
网络回来可能时间较久，不知道如何能够判断当前页面或组件已经不在了。

**Comment by ChrisCindy** [comment]
试一下这个包：https://www.npmjs.com/package/rax-use-mounted-state
