### ISSUE TITLE
[Question]Attempt to use history.pushState() more than 100 times per 30 seconds 

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2196]
![image](https://user-images.githubusercontent.com/51048705/127089675-1aefd5ce-d985-4052-8e2d-218428af1c2e.png)

**Comment by waylon-gmail** [comment]
web端: tab来回切换出现

**Comment by SoloJiang** [comment]
社区里好像有很多类似的问题，我这里可以优化一下相同路径不进行 push 操作
