### ISSUE TITLE
[Question]二级页面分享到微信朋友圈，从微信朋友圈点击回到小程序报错，页面白的。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2200]
![image](https://user-images.githubusercontent.com/51048705/127626281-85cf0094-1961-4ae8-b811-7c3fa500be51.png)

二级页面分享到微信朋友圈，从微信朋友圈点击回到小程序的时候，提示这个。

**Comment by ChrisCindy** [comment]
从错误日志看来非 Rax 层的报错，可以根据日志排查一下看看

**Comment by waylon-gmail** [comment]
谢谢大佬，反馈很快，刚排查了一下感觉像是微信自己的bug。我先去找微信开发者频道。
