### ISSUE TITLE
[使用历史组件，不想转化rpx直接复用，如何解决呢？]

### ISSUE THREAD

**Issue by Believe-Myself** [alibaba/rax#2202]
您好！已有的历史组件是用px写的，如果想直接在rpx中使用的话，因为写rax的单位都是rpx，该如何解决呢？我看控制是否转化的位置是在driver- universal的导出时的createElement函数，但具体没有大的思路。小白一枚，求指教！感谢

**Comment by SoloJiang** [comment]
是什么容器？

**Comment by Believe-Myself** [comment]
主要是web小程序，好像也有以前的weex，大佬能分开讲讲吗？给个思路

**Comment by SoloJiang** [comment]
- web、小程序这种 px 直接替换成 rpx 其实从样式表现上不符合你预期的，即单位不对等
- weex 中 px 完全等于 rpx，所以不转换也是 ok 的

**Comment by Believe-Myself** [comment]
嗯嗯。我的想法是px不转化，直接使用原始的单位，就是需要把修改源码return DriverDOM.createElement(type, props, component, true);为false。然后自己发一个基于源码的包。但是自己具体怎么修改比较懵

**Comment by SoloJiang** [comment]
为什么需要自己改？本身写的是 px 就会保留 px

**Comment by Believe-Myself** [comment]
我们以为必须是原始的必须rpx，所以那我们之前写的px单位的组件是可以直接复用的吧？

**Comment by SoloJiang** [comment]
是的

**Comment by Believe-Myself** [comment]
好的，感谢大佬！

**Comment by Believe-Myself** [comment]
师兄，你好！我前面搞错了。以前的组件没有加任何单位，现在想基于rax使用并添加px单位，应该如何控制呢？我是看driver-dom中有一个 __shouldConvertUnitlessToRpx的参数，如果为否的话就会加 ‘px‘单位。我想基于driver-dom封装一个为false的库 可以吗？
