### ISSUE TITLE
[Question][Solution] How to dynamically only change the sub-component, and also push one history item

### ISSUE THREAD

**Issue by yrcs** [alibaba/rax#2206]
As follows, the "{children}" is not text content, it's sub-component node. I don't know how to dynamically only change it (not the whole `<Layout />`), and also push one history item at the same time. There is no `<Route path="/about" component={About} />` like React in Rax. Please help me provide a best solution. Thank you very much!

`export default function Layout() {
  return (
    <div>
      <h2>Header</h2>
      <main>
        {children}
      </main>
    </div>
  );
};`

**Comment by SoloJiang** [comment]
We will support Layout for Rax App. Please see this issue https://github.com/raxjs/rax-app/issues/791

**Comment by SoloJiang** [comment]
由于本身的规划问题，Layout 的能力不再计划提供
