### ISSUE TITLE
[BUG] Windows 下启动带 TabBar 的项目时报错

### ISSUE THREAD

**Issue by Aoey-1015** [alibaba/rax#2207]
[
![lADPD3zUOidPqcDNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/73510283/128662883-4f23746e-fa3a-42ae-add3-2a02541db78c.jpg)
](url)

![image](https://user-images.githubusercontent.com/73510283/128662908-fdcdcc34-d0cc-4a2f-8e05-e50f7d73c718.png)

使用官方文档的这个,启动会报错

windows

**Comment by wjq990112** [comment]
@Aoey-1015 你尝试使用过 git bash 启动吗？

**Comment by Aoey-1015** [comment]
> @Aoey-1015你尝试使用过git bash启动吗？

我这边是对接浙里办的

**Comment by Aoey-1015** [comment]
> @Aoey-1015你尝试使用过git bash启动吗？

主要是要上传到浙里办的平台上不会有问题

**Comment by Aoey-1015** [comment]
> @Aoey-1015你尝试使用过git bash启动吗？

这个是不能用powershell启动吗

**Comment by Aoey-1015** [comment]
> @Aoey-1015 你尝试使用过 git bash 启动吗？

上传到浙里办的平台上是可以现实的,就只是powershell会报错

**Comment by wjq990112** [comment]
@Aoey-1015 你改用 gitbash 尝试启动一下？初步怀疑是这块的问题，排除一下。我这边 Windows 暂时还没启动起来，今天再看下。

**Comment by wjq990112** [comment]
@Aoey-1015 我看了一下，应该定位到问题了，给你一个初步的解决方案：

在项目的 `package.json` 中添加一段内容试一下，我们发了一个 `beta` 版本，先锁一下版本。

```diff
{
+   "resolutions": {
+      "@builder/mpa-config": "3.2.7-beta.0"
+   }
}
```

**Comment by Aoey-1015** [comment]
> @Aoey-1015 我看了一下，应该定位到问题了，给你一个初步的解决方案：
> 
> 在项目的 `package.json` 中添加一段内容试一下，我们发了一个 `beta` 版本，先锁一下版本。
> 
> ```diff
> {
> +   "resolutions": {
> +      "@builder/mpa-config": "3.2.7-beta.0"
> +   }
> }
> ```

只要加这个就行了吗,我加了之后用powershell的话还是报错

**Comment by wjq990112** [comment]
@Aoey-1015 加了之后要删除 `node_modules`，然后使用 `yarn` 重新安装依赖。

**Comment by Aoey-1015** [comment]
> @Aoey-1015 加了之后要删除 `node_modules`，然后使用 `yarn` 重新安装依赖。

ok了,谢谢
