### ISSUE TITLE
[BUG]视频播放组件，根据判断手动设置playControl的值，控制台报错：TypeError: node.pause is not a function

### ISSUE THREAD

**Issue by yanshengjie** [alibaba/rax#2208]
循环渲染了多个Video组件 ，当点击下一个时，暂停上一个的播放，通过playControl属性控制是否播放，但是报错node.pause is not a function
<img width="1122" alt="截屏2021-08-10 下午3 04 32" src="https://user-images.githubusercontent.com/66824206/128823036-7517c288-da78-4fb1-97fa-42f686ca2a80.png">

**Comment by ChrisCindy** [comment]
提供一下最小可复现 demo 代码

**Comment by yanshengjie** [comment]
const  [str,setStr] = useState('pause');

**Comment by yanshengjie** [comment]
const  [str,setStr] = useState('pause');

**Comment by yanshengjie** [comment]
公共组件
import { createElement, useState } from 'rax';
import View from 'rax-view';
import Video from 'rax-video';
import cls from 'classnames';
import { Button, Icon } from '@alifd/meet';
import { history } from 'rax-app';
import { getPreviewUrl } from '@utils';

import style from './index.module.scss';

const MiniDetail = (props) => {
  const { className, item = {} } = props;
  const {
    exhibit,
    owner,
    price,
    id
  } = item;
  const  [str,setStr] = useState('pause');

  return (
    <View className={cls(className, style.miniDetailItem)}>
      <View className="showcase-cover__container" onClick={()=>{
        console.log(111);
        setStr('play')
      }}>
        <Video className={cls('showcase-cover', id)}
          mode="aspectFit"
          src={getPreviewUrl(exhibit.preview)}
          poster={getPreviewUrl(exhibit.cover)}
          showPlayBtn={false}
          showFullscreenBtn={false}
          showCenterPlayBtn
          showThinProgressBar={false}
          playControl={str}
        />
      </View>
    </View >
  );
};

export default MiniDetail;

**Comment by yanshengjie** [comment]
调用时
data.map(ele => {
              return <MiniDetailItem item={ele} />;
            })

**Comment by yanshengjie** [comment]
> 提供一下最小可复现演示代码

**Comment by yanshengjie** [comment]
> > 提供一下最小可复现演示代码

OK

**Comment by yanshengjie** [comment]
> 提供一下最小可复现演示代码

发到评论区了

**Comment by ChrisCindy** [comment]
是微信小程序吗

**Comment by yanshengjie** [comment]
> 是微信小程序吗
支付宝

**Comment by ChrisCindy** [comment]
playControl 属性不支持小程序平台，文档里有说明。小程序端如果期望用 js 控制视频的播放，可以使用 https://raxjs.org/docs/api/createVideoContext

**Comment by ChrisCindy** [comment]
https://github.com/raxjs/rax-components/pull/392

小程序平台现已支持 playControl 属性
