### ISSUE TITLE
H5手机端使用rax-video会出现层级过高无法被遮挡的问题。

### ISSUE THREAD

**Issue by XAihan** [alibaba/rax#2214]
在H5端使用rax-video会出现层级过高，定位问题发现，是因为支付宝使用的apollo，所以需要添加raw-controls属性。
其它的如微信端，H5浏览器等也需要添加对应的属性。

所以提议，是不是可以在进行编译的时候，rax直接就把对应属性加上，防止用户遇到这些问题。
目前获取到的常用属性如下：
  webkit-playsinline={true}
  x5-video-player-type="h5"
  raw-controls
基本把这三个属性添加上，就不会出现层级问题了

**Comment by ChrisCindy** [comment]
H5 端只面向 W3C 标准添加属性，不会为特定的 webview 容器做兼容处理
