### ISSUE TITLE
[Question]国际化Provider报错

### ISSUE THREAD

**Issue by swl880422** [alibaba/rax#2221]
import { IntlProvider, addLocaleData } from 'react-intl';
![image](https://user-images.githubusercontent.com/45808551/130028687-06552614-4e93-4232-bdfc-9e541f7f1c76.png)

**Comment by wjq990112** [comment]
方便看下报错详情吗？鼠标悬浮在错误代码上会弹框？

**Comment by swl880422** [comment]
![Screen Shot 2021-08-19 at 4 12 19 PM](https://user-images.githubusercontent.com/45808551/130032639-f2c0b5bc-fb70-47fd-aad8-8ac6e09780e6.png)

**Comment by swl880422** [comment]
![Screen Shot 2021-08-19 at 4 12 54 PM](https://user-images.githubusercontent.com/45808551/130032719-5c8acce3-6151-4bba-897d-82f4b21ea92c.png)

**Comment by swl880422** [comment]
还有一个问题: 这种引入如果要动态切换语言，应该要怎么处理呢？

**Comment by wjq990112** [comment]
从这个报错提示来看基本都是 TS 类型的报错，可以结合一下 d.ts 文件来定位一下是什么问题

**Comment by swl880422** [comment]
不引入react-intl， 自己实现了一下。
剩下的问题就是 tab 不知道如何国际化，看了一下很多原生小程序也没有提供方案。先关闭问题了，目前用国际化只是web版，只要不使用tab配置的情况下还是可以的。
