### ISSUE TITLE
[Question]miniapp-render 2.8.1

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2225]
miniapp-render 2.8.1 升级这个后报错 (恢复成2.6.1没有问题)
rax-app 3.6.6

npm run start后微信小程序报错
![image](https://user-images.githubusercontent.com/51048705/130331151-8993def8-d718-4944-af5b-4a0d50174e3b.png)

**Comment by waylon-gmail** [comment]
https://github.com/alibaba/rax/issues/2201

**Comment by waylon-gmail** [comment]
node module删掉重新安装报下边错误：
![image](https://user-images.githubusercontent.com/51048705/130331771-4bd7a914-ea40-4a6e-9728-4867e041dea6.png)

**Comment by ChrisCindy** [comment]
有依赖未更新，尝试使用 cnpm install 重装依赖试一下

**Comment by ChrisCindy** [comment]
目前有一些内部使用的包版本需要互相配合，上述问题出现的原因是某些包的班班升级了，某些包的版本没升级。确认一下 rax-miniapp-runtime-webpack-plugin 是 v4.9.0，miniapp-builder-shared 是 v0.2.10

**Comment by waylon-gmail** [comment]
npm i miniapp-render@2.8.1
npm i rax-miniapp-runtime-webpack-plugin@4.9.0
npm i miniapp-builder-shared@0.2.10
安装这3个可以。
