### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by yyf-fjj** [alibaba/rax#2232]
使用
 <Progress
                      size="small"
                      percent={50}
                      shape='circle'
                      color='#aab'
                      backgroundColor='#fff'
                    />
的时候，微信小程序报错
![企业微信截图_1630634353271](https://user-images.githubusercontent.com/52846530/131940508-64cd94e2-b4bb-44a1-809b-3617915d5a94.png)
使用方式：
![企业微信截图_16306347764544](https://user-images.githubusercontent.com/52846530/131940607-2ed374af-2081-4d74-a44f-7c36dcf57299.png)
![企业微信截图_16306347969907](https://user-images.githubusercontent.com/52846530/131940659-a78553b2-2652-462e-8074-7792ca9b120d.png)

**Comment by SoloJiang** [comment]
现在技术上暂无法支持环形进度条
