### ISSUE TITLE
[Question]支付宝小程序真机storage报错

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2234]
![image](https://user-images.githubusercontent.com/51048705/132550153-09e07a36-e242-4e7a-894b-c95c9c4427b9.png)

微信小程序模拟器没问题；
微信小程序真机没问题；
支付宝小程序模拟器没问题；
支付宝小程序真机报如上错误。

**Comment by waylon-gmail** [comment]
```
const setStorage = (key, value): Promise<boolean> => {
  return new Promise((resolve) => {
    storage.setStorage({
      key: `${key}`,
      data: value,
    }).then((res) => {
      resolve(true);
    }).catch((err) => {
      logger.e(LOG_TAG, 'setStorage', err);
      resolve(false);
    }).finally(() => {
    });
  });
};
```

**Comment by waylon-gmail** [comment]
好像不是rax的问题，直接改成原生api也是一样的错误。奇怪了。

**Comment by brightcd** [comment]
这个问题是因为支付宝小程序真机环境的Promise没有实现finally方法，跟setStorage api的使用方法没有关系，猜测是支付宝小程序真机Promise实例与模拟器实现不一致，建议可以使用complete回调解决
