### ISSUE TITLE
[Question]什么时候可以支持编译android/iOS 原生

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2236]
已经适配完微信小程序，支付宝小程序，web，没有遇到其他问题，总体挺好。期待原生支持。

**Comment by SoloJiang** [comment]
我们推荐通过 Kraken 来支持原生

**Comment by waylon-gmail** [comment]
https://openkraken.com/
官网有点不太好找，很少人分享链接。准备研究一下，3Q。
