### ISSUE TITLE
[Question]Dialog在微信小程序真机下会闪烁，之前不会。模拟器正常。

### ISSUE THREAD

**Issue by waylon-gmail** [alibaba/rax#2239]
https://user-images.githubusercontent.com/51048705/133614430-5ae492b7-1bba-48a5-a009-6fe13c3cff1d.mp4

```
<Dialog
        className="sku-select-dialog"
        visible={skuSelectVisibleState}
        footer={false}
        closeMode={['mask']}
        onClose={() => setSkuSelectVisibleState(false)}
        content={
          <SkuSelectComponent
          />
        }
      />
```

**Comment by ChrisCindy** [comment]
@alifd/meet 已知问题。本周发版修复。

**Comment by waylon-gmail** [comment]
好的，感谢。android的机器试了一台是正常的。这台有问题的是 iphonexs max

**Comment by waylon-gmail** [comment]
https://user-images.githubusercontent.com/51048705/133616820-1b80e662-22f0-4e2d-846f-fb598e743db7.mp4

padding-bottom: env(safe-area-inset-bottom); 这个好像没生效。模拟器是正常的，真机不正常。之前真机也是正常的。

```
  .goods-list-wrapper {
    width: 100%;
    flex: 1;
    margin-top: 35px;
    margin-bottom: 50px;
    padding-bottom: env(safe-area-inset-bottom);
  }
```

**Comment by waylon-gmail** [comment]
可能是因为 margin-bottom 和 padding-bottom同时使用的时候，只生效了1个。
