### ISSUE TITLE
Android与iOS性能差距问题

### ISSUE THREAD

**Issue by jimmyrogue** [alibaba/rax#226]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Discussion

2. Describe your issue:
 - 相同代码，iOS下比Android性能好很多，大致结构为 Tabbar-->三个List。数据均为异步网络或缓存获取，我该往个方向努力才能优化性能？(QAP开发)

**Comment by wssgcg1213** [comment]
会不会跟这个有关 https://github.com/alibaba/weex/issues/2710

**Comment by wssgcg1213** [comment]
还是建议你先抓包看一下 网络中的耗时是否不同。

**Comment by yuanyan** [comment]
1. 在weex下android 的js引擎性能比ios低
2. 在web下android的webview性能比ios低

**Comment by jimmyrogue** [comment]
@wssgcg1213 我试一下

**Comment by jimmyrogue** [comment]
@wssgcg1213 的确和 链接里的情况一下，网络耗时非常少，iOS和Android网络耗时基本相同。

**Comment by jimmyrogue** [comment]
[测试数据.pdf](https://github.com/alibaba/rax/files/945987/default.pdf)
我测试了一下

**Comment by jimmyrogue** [comment]
我又认真的测试了一遍，我们有个获取服务器时间的接口，不需要任何依赖可以直接请求，请求时间都在4ms-7ms内。
![](http://ww1.sinaimg.cn/large/006tKfTcgy1feue51perij31kw0b6q5v.jpg)

我循环调用7次，记录每次从请求开始到进入回调的时间。
Android响应时间如下
![image](http://ww1.sinaimg.cn/large/006tKfTcgy1feue2zpyj9j31kw0ixtcs.jpg)

ios如下
![](http://ww4.sinaimg.cn/large/006tKfTcgy1feue5tu4mgj31kw0jn77s.jpg)

Android花费的时间都在三位数，基本是ios的10倍，我们的业务逻辑中有好多类似的嵌套调用，嵌套的请求越多，这个差距就越大，在真机上渲染时间就越长。
这是我们目前遇到的问题。

麻烦各位大神能帮忙想想办法。
@yuanyan @wssgcg1213

**Comment by yuanyan** [comment]
@jimmyrogue android慢的原因，也需要你从数据上度量不同阶段的事情；结论上android的确会比ios慢
