### ISSUE TITLE
[Feature] Rax and Mdx

### ISSUE THREAD

**Issue by phshy0607** [alibaba/rax#2276]
Mdx is a way to write React(or jsx) code in markdown, it can be used with remark/rehype plugins, which is a huge ecosystem.

I've checked some source code of our component document demo implementation, which separate each coding blocks using Regex, then compile them and combine the raw markdown part(using marked). This approach is a bit hacky.

I think embracing unified ecosystem is such a nice move in the future.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1. Provide 'rax/jsx-runtime' exactly like React did in the new jsx transforming. For speed and for bundle size.
MDX support custom jsx runtime: https://v2.mdxjs.com/packages/mdx/#optionsjsxruntime
2. Provide more remark/rehype plugins to fit the need.

**Comment by fengzilong** [comment]
Hey, I'm also a big fan of `mdx` 😀

For step 1 you metioned above, did you try [`options.pragma`](https://v2.mdxjs.com/packages/mdx/#optionspragma) to compatible with current version of rax?

If it works, in theory, we only need to provide some package like `@mdx-js/rax` exporting `MdxProvider`/... to combining rax with MDX

FYI: you also metioned `remark/rehype plugins`, it's all about markdown and html? IMO it's irrelevant to rax

**Comment by phshy0607** [comment]
@fengzilong 
I thought about the pragma, and I'm still trying to get rax into this.
For the MdxProvider, I will check @mdx-js/preact. Thank you for the tip. I haven't got time for this, but sure i will check that later. XD

And for the remark/rehype plugins, sure it's irrelevant to rax.
