### ISSUE TITLE
[BUG]rax-Countdown没有支持ms

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2279]
背景
- tpl我看到可以设置{d}天{h}时{m}分{s}秒{ms}
- 但实际上并不支持ms

**Comment by fengzilong** [comment]
确实不支持，文档有误

**Comment by xmsz** [comment]
> 确实不支持，文档有误

ok 那可以支持不

我们的场景是抢购倒计时，需要毫秒这种看起来更有紧迫感

**Comment by SoloJiang** [comment]
1. 可以直接使用 react-use-countdown，把 react alias 到 rax 就好
2. rax-countdown 目前是维护状态，如果可以贡献代码的话，提供一个路径参考：
  - 将 react-use-countdown 的代码同步更新到 rax-use-countdown
  - rax-countdown break change 掉，改为直接依赖 rax-use-countdown

**Comment by xmsz** [comment]
> 1. 可以直接使用 react-use-countdown，把 react alias 到 rax 就好

ok

**Comment by fengzilong** [comment]
> ok

看了下我上面提到的那个 npm 包的源码，实现上有点 bug，晚点提个 PR 到 rax-use-countdown 修复下

**Comment by fengzilong** [comment]
https://github.com/raxjs/rax-hooks/pull/18

@xmsz 可以追踪下这个 PR，合入发版后可以试用下，有问题欢迎反馈
