### ISSUE TITLE
[BUG] rax-view组件问题

### ISSUE THREAD

**Issue by 15893361787** [alibaba/rax#2280]
**问题描述**
rax-view  组件onAppear回调没有执行
环境 web

**希望看到的效果**
元素曝光时触发回调

**实际效果**
不管是首屏元素还是滚动后的元素都没有执行回调
**代码示例**
![image](https://user-images.githubusercontent.com/41234952/140754531-b9fd309c-ee31-4196-88c8-b5e871657697.png)

**页面效果**

https://user-images.githubusercontent.com/41234952/140754815-0612f44e-adc3-40e6-9e19-68606de95f65.mov

**Comment by SoloJiang** [comment]
Web 需要看下这个 polyfill https://github.com/raxjs/appear-polyfill

**Comment by fengzilong** [comment]
之前想过是否可以在 `appear-polyfill` 中埋一个特性侦测的变量，然后开发阶段在 rax-components 中检测，在控制台给个明确的 error，但是这个改动有点 breaking

**Comment by SoloJiang** [comment]
文档我加一下相关描述吧
