### ISSUE TITLE
[Feature] fusion mobile 组件优化点建议

### ISSUE THREAD

**Issue by Tesla0916** [alibaba/rax#2284]
rax组件不考虑收集一波用户反馈么，现在生态做的有点差啊，组件各种体验问题和小bug也一直没人关注，希望能有这方面的计划

**Comment by wjq990112** [comment]
你说的组件体验问题指的是 fusion mobile 嘛？

**Comment by Tesla0916** [comment]
是的 fusion还有人在维护么

**Comment by wjq990112** [comment]
有的，有专门的同学负责维护，可以描述一下具体遇到的一些问题吗？我集中反馈一下，谢谢！

**Comment by Tesla0916** [comment]
嗯感觉体验上还要下点功夫，简单的两个例子
1. modal、drawer这些组件，状态不完全受props控制，就算是设置为visible恒为TRUE，点击蒙层空白处还是会关闭当前Drawer
```js
<Drawer visible={true} />
```
2. toast一直点击会一直弹出，直观的方案应该是点击多次在一段时间内也只会生成一个元素。

__可以横向对比antd mobile的各种组件设计__

> 其他问题收总后会贴到这里。

**Comment by wjq990112** [comment]
好的，后续有问题也可以在这个 issue 继续回复，非常感谢反馈！

**Comment by lianmin** [comment]
@Tesla0916 你现在用的 Fusion Mobile 版本是多少呢，我用最新的版本是 ok 的：

1. modal drawer 目前是受控的
2. toast 近期的版本中已经加了处理， 弹出 toast 时，底部元素无法点击

**Comment by SoloJiang** [comment]
后续针对组件的问题可以按需单独提 issue
