### ISSUE TITLE
[Question]内联style的rpx单位在小程序中为什么转换成了px？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2289]
背景
```
   <div style={{
width:"20rpx"
}}>
</div>
```
- web正常变成了vw
- 微信小小程序变成了10px

需求
- 如何在内联style中使用rpx

**Comment by ChrisCindy** [comment]
rpx 转成 px 的逻辑是由小程序容器处理的，20rpx -> 10px 是符合的文档说明的。

**Comment by xmsz** [comment]
> rpx 转成 px 的逻辑是由小程序容器处理的，20rpx -> 10px 是符合的文档说明的。

什么意思哈

是说px是小程序自动转换的吗

但是样式里的rpx没有转换
