### ISSUE TITLE
[Question]有没有什么快捷方法获取和实现小程序自定义导航栏

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2291]
背景
- 需要自定义小程序的导航栏
- 如果自己的写的话，要获取小程序的各种高度，特别麻烦

需求
- 如何快速获取小程序的导航栏高度
- 有没有自定义导航栏的组件

**Comment by ChrisCindy** [comment]
目前 Rax 体系下暂时没有满足需求的库/组件。可以查阅一下对应小程序平台是否有相关的 API 或现成组件，Rax 也支持直接使用的。

**Comment by xmsz** [comment]
> 目前 Rax 体系下暂时没有满足需求的库/组件。可以查阅一下对应小程序平台是否有相关的 API 或现成组件，Rax 也支持直接使用的。

好吧 那期待一下社区共享一下

我们自己搞过好几次，每次都觉得好麻烦有很多优化的地方
