### ISSUE TITLE
[Question]求个0.x版本rax文档

### ISSUE THREAD

**Issue by yunying1** [alibaba/rax#2292]
求个0.x版本rax文档

**Comment by imsobear** [comment]
阿里内部用户？

**Comment by yunying1** [comment]
1688服务市场插件
用的rap是基于rax的，但是他们rap几年不更新了
用的是0.6的rax
rap：https://bspace.1688.com/

**Comment by yunying1** [comment]
> 阿里内部用户？

1688 服务市场插件
用的 rap 是基于 rax 的，但是他们 rap 一年不更新了，
用的是 0.6 的 rax
rap：https://bspace.1688.com/

**Comment by imsobear** [comment]
我问下~现在具体需要哪块的文档？

**Comment by yunying1** [comment]
> 我问下~现在具体需要哪块的文档？

想要一下0.6的组件文档，因为最新版本的组件不兼容老版本的rax

**Comment by imsobear** [comment]
@yunying1 以前在哪里看的组件文档？用到哪些组件，npm 包和版本可以列举下。

**Comment by yunying1** [comment]
> @yunying1 以前在哪里看的组件文档？�用到哪些组件，npm 包和版本可以列举下。

文档在这里：https://bspace.1688.com/developer/components/mobile/rox-button

我看他们的源码 rox-component 是封装的`nuke`这个组件库 但是这个库的官方文档（nuke：http://nuke.alibaba-inc.com/）打不开了，不知道是不是内部项目

所以现在我想直接使用rax0.6的组件自己来封装组件
业务比较复杂，所有组件都可能会用到

项目中：
rax@0.6.3
rax-text@^0.4.20
rax-view@^0.4.20
rax-touchable@^0.5.4
rax-scrollview@^0.5.4
rax-refreshcontrol@^0.5.4
rax-recyclerview@^0.5.0
rax-picker@^0.5.0
rax-link@0.6.5

（因为他们rap封装过的，我只找出来了部分）

**Comment by imsobear** [comment]
@yunying1 现在为什么不使用 rox-components 而要自己封装呀？

**Comment by yunying1** [comment]
> @yunying1 现在为什么不使用 rox-components 而要自己封装呀？

目前rox-components不能满足我们业务的需求
而且也没有人维护，缺陷不能得到解决

**Comment by SoloJiang** [comment]
0.6 的文档可以在 Rax 内部官网最下面的友链看到
