### ISSUE TITLE
[Question]usePageShow表现不符合预期

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2293]
背景

```
const [isTrue, setIsTrue] = useState(false)
usePageShow(()=>{
 console.log(isTrue)
})

useEffect(()=>{
setIsTrue(true)
})
```
- isTrure永远都是显示false
- 需要调用方法才能拿到最新的值

**Comment by SoloJiang** [comment]
这是一个典型的闭包，usePageShow 传入的 callback 创建了该变量的快照，你可以尝试用引用的方式解决问题

**Comment by xmsz** [comment]
> 这是一个典型的闭包，usePageShow 传入的 callback 创建了该变量的快照，你可以尝试用引用的方式解决问题

ok 明白了
