### ISSUE TITLE
[Question]如何去除wx.api接口引用

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2294]
背景
- 是的 微信开发总爱搞一些为难开发的事情 而且什么都是一刀切
- 就是提审的时候微信检测出了我们有用一些api 让外面填写一些隐私说明
- 但我们根本没用到
- 是框架正常打包的

相关问题
https://github.com/remaxjs/remax/issues/1751

需求
- 有没有办法去除没有再用的api

**Comment by ChrisCindy** [comment]
可以列举一下用到了哪些 API 吗？目前框架自身应该用到的很少。如果使用 Uni API 的小包模式，也是按需引入使用的。

**Comment by xmsz** [comment]
说用到了
- 麦克风
- 摄像头
- 相册写入权限


我的依赖
```
    "@uni/env": "^1.0.7",
    "@uni/navigate": "^1.0.8",
    "@uni/request": "^1.1.6",
```

看产物和依赖好像都是@alifd/meet引用到的@uni的其他包


太扯了

**Comment by ChrisCindy** [comment]
我和 @alifd/meet 的开发人员沟通一下

**Comment by ChrisCindy** [comment]
确认一下你这边用到了 @alifd/meet 的哪些组件，以及是否使用了 build-plugin-fusion-mobile 进行无用代码的剔除

**Comment by xmsz** [comment]
> 确认一下你这边用到了 @alifd/meet 的哪些组件，以及是否使用了 build-plugin-fusion-mobile 进行无用代码的剔除

使用了
- Icon
- Message
- Form
- Input
- Button
- Drawer
- Dialog

未使用build-plugin-fusion-mobile剔除无用代码

**Comment by ChrisCindy** [comment]
可以使用 build-plugin-fusion-mobile 剔除一下，看看还有没有 warning

**Comment by xmsz** [comment]
> 可以使用 build-plugin-fusion-mobile 剔除一下，看看还有没有 warning

好像没了 谢谢
