### ISSUE TITLE
[BUG]Dailog+Drawer或者多个popup的时候关闭body.overflow还是hidden

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2296]
背景
- 打开两个弹窗，然后关闭
- 这时候body.overflow还是hidden
- 类似与https://github.com/alibaba-fusion/next/issues/3104

需求
- 修复该问题

**Comment by lianmin** [comment]
@xmsz 这是引用的 @alifd/meet 这个包么， 还是@alifd/next？

**Comment by xmsz** [comment]
> @xmsz 这是引用的 @alifd/meet 这个包么， 还是@alifd/next？

@alifd/meet

**Comment by lianmin** [comment]
@xmsz 能否给个复现的代码 demo？

**Comment by xmsz** [comment]
> @xmsz 能否给个复现的代码 demo？

我用新项目试了一下

https://github.com/xmsz/act-20211129

复现比较复杂
- 进入页面 打开弹窗 => 点击dialog  点击 ok => 会进入新页面
- 通过浏览器回退到上个页面
- 再次重复操作
- 复现

**Comment by lianmin** [comment]
@xmsz 可以复现你的问题，我来解决

**Comment by lianmin** [comment]
此 bug 在最新的版本 2.6.2 中已修复
