### ISSUE TITLE
[Feature]Form类型补全

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2297]
背景

- Form 没有className之类的类型
![image](https://user-images.githubusercontent.com/5879146/143366871-3fd3e587-2866-4827-aef9-bb03f3280ec1.png)

- Form.Item没有children类型
```
不能将类型“{ children: Element; label: Element; className: string; }”分配给类型“IntrinsicAttributes & FormItemProps & RefAttributes<any>”。
  类型“IntrinsicAttributes & FormItemProps & RefAttributes<any>”上不存在属性“children”。ts(2322)
(property) FormWithComponents.Item: Rax.ForwardRefExoticComponent<FormItemProps & Rax.RefAttributes<any>>
```

- FormItem设置name无效，必须设置在Input上，和fusion不同
在fusion里，name是设置在Form.Item上的
但meet则是在Input上

然后设置的时候又说类型不存在
```
不能将类型“{ placeholder: string; className: string; name: string; "confirm-type": string; }”分配给类型“IntrinsicAttributes & InputProps”。
  类型“IntrinsicAttributes & InputProps”上不存在属性“name”。ts(2322)
(JSX attribute) name: string
```

**Comment by lianmin** [comment]
@xmsz 麻烦提供下 meet 的版本，或者尝试升到 Fusion Mobile 的最新版本呢？

**Comment by xmsz** [comment]
> @xmsz 麻烦提供下 meet 的版本，或者尝试升到 Fusion Mobile 的最新版本呢？

 "@alifd/meet": "^2.5.6",

**Comment by lianmin** [comment]
确实有问题， 下个版本我们加上去

**Comment by lianmin** [comment]
form.item 的 children 描述已在 @alifd/meet@2.5.7 上发布

**Comment by wanglianjie91** [comment]
input的name属性依然找不到。  这一块真的太乱了。  编辑器一片红。
