### ISSUE TITLE
[BUG]Input.Textarea focus后会丢失h5-textarea这个classname

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2299]
插件：@alifd/meet
组件：Input.TextArea
环境：小程序

```
<Input.TextArea
              className={styles.ContentInput}
 
            />
```
- 没focus前还可以用， focus后h5-textarea这个classname没了

**Comment by cryzzchen** [comment]
@xmsz @alifd/meet 中的 Input 组件么？

**Comment by xmsz** [comment]
> @xmsz @alifd/meet 中的 Input 组件么？

没错

**Comment by SoloJiang** [comment]
你出问题的容器是小程序还是 Web

**Comment by xmsz** [comment]
> 你出问题的容器是小程序还是 Web

小程序
h5的好像一开始就没有'h5-textarea'这个className

**Comment by lianmin** [comment]
测试了下， 在小程序下，的确是有 h5-textarea 的，输入后，就会丢失。 是 rax-textinput 组件的问题， @SoloJiang 帮看看

**Comment by ChrisCindy** [comment]
rax-textinput@1.4.3-0
可以试用一下这个版本
pr: https://github.com/raxjs/rax-components/pull/423
