### ISSUE TITLE
[Question]如何在web端不引入小程序原生组件

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2301]
背景
- 有一个原生自定义组件
- 然后web端也会引入，但引入会报错
```
Component is not defined
```

**Comment by ChrisCindy** [comment]
https://rax.js.org/docs/guide/miniapp-faq#2.%20%E4%B8%8D%E5%90%8C%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%AB%AF%E4%BB%A3%E7%A0%81%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86%EF%BC%9F

**Comment by xmsz** [comment]
> https://rax.js.org/docs/guide/miniapp-faq#2.%20%E4%B8%8D%E5%90%8C%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%AB%AF%E4%BB%A3%E7%A0%81%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86%EF%BC%9F

ok

然后我之前临时的处理方法就是 在index.js声明
```
if(typeof Component === 'undefined') {
 Component = () =>null
}
```
代价就是代码依旧会被引入，只是不展示而已



不过这种感觉更类似于，会方便一点
```
import Comp from './comp/index.js?wechat'

{Comp ? <Comp/>}

```
