### ISSUE TITLE
[Question]有没有办法拿到构建的本地ip和port

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2304]
背景
- 希望能拿到当前构建的ip和port
- 因为现在只能通过127.0.0.1来指向本地，但如果想把页面分享给局域网其他人，那就只能是具体的ip地址

需求
- 在哪能获取到当前构建的ip和port

**Comment by SoloJiang** [comment]
希望通过怎样的形式获取到 ip 和 port？目前控制台会打印调试 url

**Comment by xmsz** [comment]
> 希望通过怎样的形式获取到 ip 和 port？目前控制台会打印调试 url

希望在代码里获取
```
const request = axios.create({
  baseURL:  getBuildIp()
});
```

**Comment by SoloJiang** [comment]
这类需求感觉不太普遍，但你可以用以下做法自行实现一下:
1. 可以写一个 build-scripts plugin
2. 在插件中通过 https://rax.js.org/docs/guide/plugin-dev#context `context.commandArgs.port` 拿到端口，另外通过 `address` 这个 npm 包获取到本机 `ip`
3. 通过 webpack define plugin 定义到 `process.env.LOCAL_URL` 上

**Comment by xmsz** [comment]
```
const address = require('address');

const defineVariables = {
  'process.env.SERVER_IP': JSON.stringify(address.ip()),
};

module.exports = ({ context, onGetWebpackConfig }) => {
  onGetWebpackConfig((config) => {
    config.plugin('DefinePlugin').tap(([args]) => {
      return [{ ...args, ...defineVariables }];
    });
  });
};
```
