### ISSUE TITLE
[BUG] PropTypes.node 无效 

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#2305]
PropTypes.node 无效 
![image](https://user-images.githubusercontent.com/17898715/145005267-2a195cf7-fdcc-47e8-947e-a9c081713ec8.png)

**Comment by imsobear** [comment]
多提供点信息

**Comment by yuchonghua** [comment]
https://github.com/facebook/prop-types/blob/main/factoryWithTypeCheckers.js#L404
--->
https://github.com/facebook/prop-types/blob/main/factoryWithTypeCheckers.js#L489
--->
https://github.com/facebook/prop-types/blob/main/factoryWithTypeCheckers.js#L58

**Comment by SoloJiang** [comment]
可以怎么复现?

**Comment by SoloJiang** [comment]
如果没有后续，暂时关闭该 issue
