### ISSUE TITLE
[BUG] 页面切换时，页面状态在 web 和小程序侧行为不一致

### ISSUE THREAD

**Issue by fengzilong** [alibaba/rax#2306]
**Describe the bug**

**Demo**

使用 npm init rax rax-example 分别创建 web 单页应用和 小程序跨端应用，新增一个页面，代码如下

```js
import { createElement, useRef, useState } from 'rax';
import View from 'rax-view';
import { usePageShow } from 'rax-app';

export default function Home() {
  const ref = useRef(0);

  usePageShow(() => {
    ref.current += 1;
    console.log('pageshow ref', ref.current);
  });

  return (
    <View className={styles.homeContainer}></View>
  );
}
```

复现步骤：重复进入该页面多次，查看 Console 日志

小程序侧表现（截图为微信小程序，模拟器和真机调试结果一致）

<img src="https://user-images.githubusercontent.com/9125255/146246633-54917b61-cfe6-4484-afb8-e3c6a8ac0987.png" width="100" />

Web 侧表现（chrome 浏览器）

<img src="https://user-images.githubusercontent.com/9125255/146247127-ec040748-aac0-4100-a982-a79899387597.png" width="100" />

根据日志中的结果可以推断出，在小程序上页面的组件实例并没有被销毁，而在 web 单页应用上，切换页面，会导致上一个页面被销毁

小程序上的这种行为，导致我们的开发同学使用了老的页面状态，并且试图在 usePageShow 中引用老的 state，但是这里又有一个坑，usePageShow 不支持传入第二个参数，导致读取的 state 永远是初始值

**Expected behavior**

usePageShow 在设计上并没有支持第二个参数，所以是不是应该保证小程序行为和 web 一致

但从另一个角度说，小程序没有销毁实例，会让切换页面的体验更好，尤其是页面本身是一个 webview 的情况下，不会触发 h5 页面重新加载，如果以小程序上的行为为准，需要为 usePageShow 补上第二个参数 deps，让 usePageShow 内的代码可以追踪状态变化

**Additional context**

 - Rax Version: 1.1.0
 - Rax App: 3.8.0

**Comment by SoloJiang** [comment]
1. 这个行为不一致性本质是容器导致的，从渲染角度来说小程序对应到端上应该是多 WebView 的 MPA 应用，如果是这样对标的话，在端上 Web 的表现和小程序就是一致的
2. 从应用角度来说，本质是小程序在页面切换的时候能够保活上一个页面，所以在 rax-app v3.8.0 开始支持 SPA 页面配置保活
3. 无论哪一种方式，由于容器和实际应用表现的差异性，很难做到真正的一致性
