### ISSUE TITLE
[BUG]input 框在钉钉端无法唤起数字键盘，而且失去焦点事件也无法生效

### ISSUE THREAD

**Issue by funnyproblemboy** [alibaba/rax#2309]
input 框在钉钉端无法唤起数字键盘，而且失去焦点事件也无法生效

**Comment by SoloJiang** [comment]
可以提供更多有效信息么，比如:
- 是钉钉的 WebView 还是小程序
- 最小复现 demo 可以提供么

**Comment by SoloJiang** [comment]
如果后续还有问题可以再提 issue
