### ISSUE TITLE
[Question]如何更好解决docker build「Exit status 137」问题

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2310]
背景
- 我构建一个rax项目，docker build
- 然后出现`Exit status 137`，就是内存不足
- 然后我将docker的内存设置从2g => 4g，正常了，但感觉不是很优雅，因为如果是构建服务器，必须要得要求2g以上?

需求
- 有没有其他办法解决这个问题，比如牺牲构建速度或者其他方法

**Comment by SoloJiang** [comment]
该问题还是需要编译太多文件导致的，目前的解法有两种:
1. 升级 rax-app 最新版开启 swc，或者压缩器指定 esbuild
2. 尽可能减少编译的文件，比如通过[这个字段](https://rax.js.org/docs/guide/build-config#compileDependencies) 按需编译依赖

**Comment by xmsz** [comment]
> 该问题还是需要编译太多文件导致的，目前的解法有两种:
> 
> 1. 升级 rax-app 最新版开启 swc，或者压缩器指定 esbuild
> 2. 尽可能减少编译的文件，比如通过[这个字段](https://rax.js.org/docs/guide/build-config#compileDependencies) 按需编译依赖

ok 我尝试一下
