### ISSUE TITLE
[Question]pha现在还有用不？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2311]
背景
- 我在文档中没找到pha相关的信息（很早以前有）
- 但是创建新项目的时候，是默认开启pha
- 所以pha这个已经不需要/不推荐使用了吗？

**Comment by imsobear** [comment]
1. pha 是一个内部的方案，依赖客户端的很多能力，对外部社区是没有意义的
2. 目前开启了 pha 选项对项目没有副作用，不过对开发者的确会有困惑，这块我们优化下
