### ISSUE TITLE
[BUG] 使用pnpm安装依赖，使用start命令预览微信小程序组件，依赖路径不正确

### ISSUE THREAD

**Issue by Awen-hub** [alibaba/rax#2315]
**问题**
使用pnpm安装依赖，进行“组件开发“，使用`build-scripts start`命令进行预览，此时产物中引用依赖的路径不正确。

![QQ图片20220114165550](https://user-images.githubusercontent.com/45597415/149488375-9ef891a8-bb20-43e1-831c-bd1bebed2576.png)

此问题仅在使用pnpm安装依赖时出现，在npm下载依赖时表现正常。
pnpm版本:  6.26.1
电脑系统: Win10

**Demo**

[bug复现仓库地址](https://github.com/Awen-hub/bugs-report-components)

**Comment by ChrisCindy** [comment]
推测目前没有针对 pnpm 的路径机制做适配处理，用户可以暂时先使用 npm、yarn 等绕过

**Comment by SoloJiang** [comment]
暂没有再支持 pnpm 的计划

**Comment by sky-admin** [comment]
在项目根目录下创建 .npmrc ，里面填写 node-linker=hoisted 试试呢？
改为 提升模式 ，应该能和 npm/yarn 安装结果类似。参考：https://pnpm.io/zh/motivation
