### ISSUE TITLE
[BUG] 在“组件开发”功能中引入由Rax开发的小程序原生自定义组件时出错

### ISSUE THREAD

**Issue by Awen-hub** [alibaba/rax#2319]
**详细描述**
在组件开发场景下，通过npm包的使用方式引入由Rax开发的小程序原生组件，得到报错如下：
![QQ图片20220123175828](https://user-images.githubusercontent.com/45597415/150673363-c795cce1-1306-4166-ad23-19c23582d022.png)

**使用的npm包**
"test-rax-component": "^1.0.18"

**相关代码**
```
import { TestView } from 'test-rax-component'


const Index = () => {
  return <TestView>1111</TestView>
}

export default Index
```

**疑问**
“组件开发”功能是否不支持通过npm包方式引入原生小程序自定义组件？

**Comment by SoloJiang** [comment]
不支持解构导出的形式
