### ISSUE TITLE
Rax组件开发功能中无法使用usePageShow生命周期钩子

### ISSUE THREAD

**Issue by Awen-hub** [alibaba/rax#2327]
### ⌨️

- [ ] Would you like to work on a fix?

### Where is the bug from?

Rax Components

### Minimal code and steps to reproduce the bug

```
import { usePageShow } from "rax-app";
```

### Current and expected behavior

在组件开发功能中使用上述代码会有ts报错，rax-app没有导出usePageShow，同时微信小程序开发者工具中会报错。

### Environment

-OS：win10
-node：16

### build.json

{
  "type": "rax",
  "targets": ["wechat-miniprogram"],
  "plugins": ["build-plugin-component", "./plugin.js"],
  "enablePlatformLoader": true,
  "outputDir": "dist"
}

### Possible solution

no

### Additional context

no

**Comment by SoloJiang** [comment]
页面级别的生命周期不会直接暴露给组件，避免组件耦合页面的逻辑，如果需要的话，1. 自行通过对应容器的 API 实现；2. 页面级组件给子组件传递钩子
