### ISSUE TITLE
使用组件功能开发微信小程序组件时时，希望能通过增加配置项的方式，使start命令下构建依赖行为和build命令一致

### ISSUE THREAD

**Issue by Awen-hub** [alibaba/rax#2331]
#2330  #2315 
参考上面两个issue，都是由于start命令下没有正确处理依赖导致。而在build命令生成的产物中，第三方包依赖都会被处理成require('xxx')的形式，rax不进行依赖打包，而是由开发者通过微信开发者工具自行构建依赖。
如果可以在build.json中增加配置项，使start命令构建产物行为与build一致，把构建依赖的行为交予开发者自行解决，这样也许可以在无法及时适配各种包管理器下载的依赖时给开发者一个兜底的选择。

**Comment by ChrisCindy** [comment]
build.json 中配置 

```json
{
  "wechat-miniprogram": {
    "disableCopyNpm": true
  }
}
```

看看是否能满足你的需求

**Comment by Awen-hub** [comment]
可以，非常感谢。
