### ISSUE TITLE
使用组件开发功能编写微信小程序原生组件，在app.json中指定"lazyCodeLoading": "requiredComponents"时触发报错

### ISSUE THREAD

**Issue by Awen-hub** [alibaba/rax#2334]
### ⌨️

- [X] Would you like to work on a fix?

### Where is the bug from?

Rax Components

### Minimal code and steps to reproduce the bug

```
//组件1
export default () => {
  const toSecondPage = () => {
    wx.navigateTo({
      url: "/secondPage/index",
    });
  };
  return (
    <view>
      <button onClick={toSecondPage}>toSecondPage</button>
    </view>
  );
};

//组件2
export default () => {
  return (
    <view>
      hello world
    </view>
  );
};
```

### Current and expected behavior

使用Rax组件开发功能，把两个Rax组件编译成微信小程序原生自定义组件，在页面```firstPage```中使用组件1，在页面```secondPage```中使用组件2。当点击```firstPage```中的跳转按钮跳转到```secondPage```，再点击左上角返回键返回```firstPage```，再次点击```firstPage```中的跳转按钮跳转到```secondPage```时在微信开发者工具中看到有报错，并且页面渲染白屏。

![微信图片_20220321110730](https://user-images.githubusercontent.com/45597415/159223405-01616846-87a3-4512-94ff-02fa4ce59968.png)
![微信图片_20220321111158](https://user-images.githubusercontent.com/45597415/159223457-a6abdec0-b0b0-491d-9837-9e43f45860d5.png)
![微信图片_20220321111228](https://user-images.githubusercontent.com/45597415/159223469-5a348e71-621a-418a-b059-079350644e64.png)
![微信图片_20220321111309](https://user-images.githubusercontent.com/45597415/159223482-24f8e27e-1cc9-4581-a712-47b491fbc0e8.png)

这个问题同时在微信开放社区给微信提供了反馈，目前不清楚是微信本身的问题还是Rax的渲染逻辑问题。更详细的报错和复现demo可以查看我在微信开放社区的[反馈帖子](https://developers.weixin.qq.com/community/develop/doc/0006c6e761011061bfad75e2952800) ,里面有可以直接在微信开发者工具打开的复现代码片段。

### Environment

- rax: 1.2.2
- jsx2mp-runtime: 0.4.25
- build-plugin-component: 1.9.4
- build-scripts: 1.1.1
- OS：Windows

### build.json

{
  "type": "rax",
  "targets": ["wechat-miniprogram"],
  "plugins": ["build-plugin-component"],
  "outputDir": "dist",
  "minify": true
}

### Possible solution

如果删除在```app.json```中的```"lazyCodeLoading": "requiredComponents"```的配置项则可以正常使用，不清楚这个配置项怎么影响到编译时组件的运行以及是否有消除影响的方法。

### Additional context

[微信小程序配置项lazyCodeLoading说明文档](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/lazyload.html#%E7%94%A8%E6%97%B6%E6%B3%A8%E5%85%A5)

**Comment by ChrisCindy** [comment]
可以等待微信社区反馈。目前从报错上来看并非 Rax 这边的运行错误。

**Comment by Awen-hub** [comment]
![微信图片_20220321162157](https://user-images.githubusercontent.com/45597415/159225787-226b6f56-f03e-4cc1-8566-b2e74ae3227d.png)
![微信图片_20220321162204](https://user-images.githubusercontent.com/45597415/159225797-66ff1724-9410-4cbe-a752-519f6408cf75.png)

从报错信息来看是```jsx2mp```库运行时候导致的报错，怀疑是指定了```"lazyCodeLoading": "requiredComponents"```导致rax的生命周期出现了一些问题导致渲染错误，希望你们这边可以从jsx2mp出发查看一下引发bug的原因，或者看看有没办法从Rax层面去规避这个Bug。

**Comment by Awen-hub** [comment]
继续调试了一下发现在使用`"lazyCodeLoading": "requiredComponents"`之后，微信小程序会在一个内置文件执行时reload，导致了变量被清空。目前已经有微信官方人员跟进。

**Comment by Awen-hub** [comment]
此Bug已被微信官方修复，升级最新的微信小程序基础库即可。
