### ISSUE TITLE
[Question]history.goBack为什么不是history.back

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2339]
背景
- 在使用history过程中，之前都是用history.back或者history.go(-1)来返回
- 但rax中，histroy.go小程序并不支持，没有back这个方法
- 然后相对应的是goBack这个方法

问题
- 为什么叫goBack而不是back

**Comment by SoloJiang** [comment]
对应实现的时候，history 提供的方法就是 goBack -- https://github.com/remix-run/history/blob/v4/docs/Navigation.md

**Comment by xmsz** [comment]
> 对应实现的时候，history 提供的方法就是 goBack -- https://github.com/remix-run/history/blob/v4/docs/Navigation.md

原来如此
