### ISSUE TITLE
[Question]自定义插件/onGetWebpackConfig如何区分构建的环境

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2340]
背景
- 构建web和wechat-miniprogram两个多端环境
- 有一个针对wechat-miniprogram环境的webpack插件
- 希望只有当构建wechat-miniprogram时才启用这个插件
- 

需求
- 是否可以拿到当前构建的环境，然后我可以针对不同环境进行区别配置
- 其他方式解决

**Comment by ChrisCindy** [comment]
onGetWebpackConfig 支持传入 target 及获取该 target 对应的 config：
```js
onGetWebpackConfig('wechat-miniprogram', (config) => {
  // modify config     
});
```
