### ISSUE TITLE
[Question]meet的Input组件如何监听回车或提交事件

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2343]
背景
- 监听用户输入时回车

fusion有onPressEnter是通过onKeyDown实现
小程序原生是onConfirm事件

meet要如何做

目前是用onKeyDown可以触发，但没有类型提示，然后小程序端没测试是否可用

**Comment by lianmin** [comment]
这个问题，跟 meet 没关系，是小程序或者 web 的逻辑。 通常，input 需要包裹在表单里，然后使用 onSubmit 或者 onConfirm 来处理。 可以参考下 meet 的 search 组件

**Comment by xmsz** [comment]
> 这个问题，跟 meet 没关系，是小程序或者 web 的逻辑。 通常，input 需要包裹在表单里，然后使用 onSubmit 或者 onConfirm 来处理。 可以参考下 meet 的 search 组件

那这个可以优化一下吗或者可以和fusion保持一致 封装`onPressEnter`方法 想方便一点调用

**Comment by lianmin** [comment]
暂时不打算这么做， Input 是高频组件，如果封装了 form ，可能引起业务上逻辑的异常，建议自己包裹一个 Form 用来处理 onConfirm 类的提交问题

**Comment by xmsz** [comment]
> 暂时不打算这么做， Input 是高频组件，如果封装了 form ，可能引起业务上逻辑的异常，建议自己包裹一个 Form 用来处理 onConfirm 类的提交问题

好吧
