### ISSUE TITLE
[Question] 微信小程序中useEffect中监听不到数组的变更

### ISSUE THREAD

**Issue by wgcairui** [alibaba/rax#2358]
`
/** DTU设备信息 */
  const [DTUs, setDtus] = useState<Uart.Terminal[]>([]);

useEffect(() => {
    console.log(DTUs);
  },[DTUs]);

setDtus((u) => {
        u.splice(0,-1,...data.UTs as any)
        return u;
      });
`

以上代码下,DTUs更新之后useEffect 和 useMemo 都监听不到变更,请问监听数组有什么技巧吗?

**Comment by ChrisCindy** [comment]
https://reactjs.org/docs/hooks-effect.html
了解一下数组中每一项的比较机制
