### ISSUE TITLE
[BUG] addProvider无法正常渲染

### ISSUE THREAD

**Issue by yehuozhili** [alibaba/rax#2364]
### ⌨️

- [ ] Would you like to work on a fix?

### Where is the bug from?

Rax App

### Minimal code and steps to reproduce the bug

本来是想像官网一样添加alifd/meet的configprovider，结果发现一添加页面就空白，去了就好了。于是我就换个view看看到底是alifd/meet的问题还是rax的问题，结果发现view也不能渲染，只有单独返回children才正常渲染。
预览看的阿里钉钉小程序
```js
// MPA 模式下该文件无效
import { runApp, IAppConfig } from 'rax-app';

const appConfig: IAppConfig = {
  app: {
    addProvider: ({ children }) => {
      return <view>{children}</view>;
    },
    onLaunch() {
      console.log('onlaunch ');
    },
    onShow() {
      console.log('on show');
    },
  },
};
runApp(appConfig);

```

### Current and expected behavior

页面正常显示

### Environment

Node: 14.15.0
rax:1.2.2
rax-app:3.8.19

**Comment by ChrisCindy** [comment]
使用 JSX 必须手动添加一下 `import { createElement } from 'rax';`
