### ISSUE TITLE
[Feature]如何定制root.wxml的内容？

### ISSUE THREAD

**Issue by xmsz** [alibaba/rax#2387]
背景
- 微信小程序团队这个大傻逼，如果有类似<live-pusher>之类的标签
![image](https://user-images.githubusercontent.com/5879146/194698965-8634b9d6-dedc-48d9-ae85-4a84c664ff04.png)
https://developers.weixin.qq.com/community/develop/doc/000ece06e602482cdafc5473f53400?highLine=%25E6%2591%2584%25E5%2583%258F%25E5%25A4%25B4%252F%25E9%25BA%25A6%25E5%2585%258B%25E9%25A3%258E

就会说：『用户隐私保护指引设置中没有使用麦克风，摄像头和照片的功能』

需求
- 如何定制哪些标签不打包到root.wxml，比如我想忽略一些标签

**Comment by ChrisCindy** [comment]
参见 rax 官网小程序-性能优化一章，可以删除组件 template
