### ISSUE TITLE
[BUG] registerNativeEventListeners 重新build 配置失效

### ISSUE THREAD

**Issue by yiescc** [alibaba/rax#2399]
### ⌨️

- [ ] Would you like to work on a fix?

### Where is the bug from?

Rax Core

### Minimal code and steps to reproduce the bug

demo: https://github.com/yiescc/test-demo-2022-12-16
 

### Current and expected behavior

- build第一次 onReachBottom 注册上去了
 ```
const render=require("./../../render");function init(e,n){require("./../../bundle.js")(e,n)}Page(render.createPageConfig("pages/Home/index",["onReachBottom"],init,""));
```
 - 没有任何修改 build 第二次 注册就失效了
 ```
const render=require("./../../render");function init(e,n){require("./../../bundle.js")(e,n)}Page(render.createPageConfig("pages/Home/index",[],init,""));
```

- 只要任意修改 再build 配置就又出现了

### Environment

*

**Comment by ChrisCindy** [comment]
这里的 build 指的是执行 `npm run build` 命令吗？

**Comment by ChrisCindy** [comment]
问题已修复，确保 build-plugin-rax-miniapp 这个包升级到 2.1.0 即可
