### ISSUE TITLE
[Question] app.json 支持按平台配置属性

### ISSUE THREAD

**Issue by yiescc** [alibaba/rax#2412]
- app.json是否支持按平台配置属性
- 需求：
- 1. 微信小程序导航栏背景颜色白色
- 2. 字节小程序导航栏背景颜色黑色

- 如果采用原生api更改配置，可能会闪一下

**Comment by ChrisCindy** [comment]
不支持。可以通过插件的形式在编译阶段手动进行 app.json 内容的替换
