### ISSUE TITLE
[Question]你们被裁了吗，怎么感觉基本没有更新了，别啊兄弟们，这么好的项目

### ISSUE THREAD

**Issue by liubgithub** [alibaba/rax#2423]
Please describe the problem you meet.

**Comment by wssgcg1213** [comment]
多谢关心 ：）

暂时还在😄，因为内部已经主流使用 react 了，这个项目目前以bugfix为主，你不妨关注一下我们团队的另一个项目  alibaba/ice

**Comment by xmsz-stu** [comment]
> 多谢关心 ：）
> 
> 暂时还在😄，因为内部已经主流使用 react 了，这个项目目前以bugfix为主，你不妨关注一下我们团队的另一个项目 alibaba/ice

ice社区好像也没啥动静，你们现在内部用什么开发跨端小程序？
