### ISSUE TITLE
rax-theme-* 的 npm 没有发布 build 目录

### ISSUE THREAD

**Issue by imsobear** [alibaba/rax#243]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

导致站点上扫描二维码不生效：

![image](https://cloud.githubusercontent.com/assets/2505411/25605467/876ce29c-2f3d-11e7-8779-ee2b47ad8125.png)

**Comment by wssgcg1213** [comment]
https://github.com/alibaba/rax/blob/master/packages/rax-theme-zhihu/package.json 
提一个PR给 theme 包的所有 package.json 加一个 `prepublish: “npm run build”`
