### ISSUE TITLE
在weex环境下使用 universal-jsonp 请求头中无 referrer

### ISSUE THREAD

**Issue by iamgqb** [alibaba/rax#251]
在weex下通过 ```universal-jsonp``` 来请求 jsonp 时，并未在请求头中发现 referrer

的确是这样的吗？有方法能带上referrer么

下面是通过charles抓包的截图

![image](https://cloud.githubusercontent.com/assets/2213424/25778745/f3f1bec4-3339-11e7-9961-951a80049a7b.png)

**Comment by yuanyan** [comment]
native不同与web，你完全可以自定义referrer字段
