### ISSUE TITLE
render 找不到 container 时错误日志优化

### ISSUE THREAD

**Issue by imsobear** [alibaba/rax#257]
![image](https://cloud.githubusercontent.com/assets/2505411/25885110/344e5288-3589-11e7-8adf-55f60ba5ce99.png)

**Comment by yuanyan** [comment]
什么情况下会出现取不到？

**Comment by imsobear** [comment]
今天帮一个同学排查这个问题，调试了一会后才发现把 script 标签放在 head 里了，取不到 body
