### ISSUE TITLE
内部组件对外提供propTypes

### ISSUE THREAD

**Issue by kingback** [alibaba/rax#289]
内部组件比如 `View`，`Text`，`TextInput`，目前没有对外暴露 `propTypes` 对象，在对这些内部组件做一些扩展功能的时候，可能会使用到，比如

```
class SearchInput extends Component {
  static propTypes = {
    ...TextInput.propTypes,
   onDelect: PropTypes.func,
  //...
  };
}
```

另外 `ReactNative` 是可以取到的，这样在移植组件的时候可以更加无缝

**Comment by yuanyan** [comment]
@kingback 下一个版本会加上

**Comment by yuanyan** [comment]
https://github.com/alibaba/rax/commit/b39c6bd02c3ca5d2102385e4ab431965fac8f172 已经加上static propTypes 确保不会报错
