### ISSUE TITLE
Element 模块中 new Element 的问题

### ISSUE THREAD

**Issue by YiKeYaTu** [alibaba/rax#299]
这里的 Element 是一个箭头函数，但是箭头函数是不能作为构造函数来 new 的。虽然编译到 lib 后成了普通的 function 没有啥问题，但是这样写还是感觉不太好= =。

**Comment by yuanyan** [comment]
@YiKeYaTu 指的是哪个文件？

**Comment by YiKeYaTu** [comment]
https://github.com/alibaba/rax/blob/master/packages/rax/src/element.js
这里

**Comment by yuanyan** [comment]
已修改，感谢反馈：https://github.com/alibaba/rax/commit/3260ecf5f1e5ba33db33ceb1f7c2f7d4bacc5e38
