### ISSUE TITLE
可以和其它的数据框架结合使用吗？

### ISSUE THREAD

**Issue by 791060555** [alibaba/rax#300]
怎么样和当前流行数据框架使用，如果dva,mobx

**Comment by stri** [comment]
我正在用`mobx`，需要改下`mobx`的源码，从两块需要改下：
* 是依赖的包，如`mobx-react`里的`require('react')`；
* 是`ObservableArray.prototype`的原生数组方法名得改下，`weex`环境会报错的(不能修改原生方法)

其它还好，页面是跑起来了。

**Comment by CodeFalling** [comment]
@stri `ObservableArray` 并不是原生对象，为什么 `ObservableArray.prototype.concat` 会是原生方法

**Comment by CodeFalling** [comment]
提了一个 PR：https://github.com/mobxjs/mobx/pull/1163

**Comment by tangkunyin** [comment]
共同关注下这块
