### ISSUE TITLE
[rax-multirow] 问题标题

### ISSUE THREAD

**Issue by magele758** [alibaba/rax#301]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?
     多行的如果为奇数个的时候，每行分布不均匀，例如为5个的时候，指定一行cell个数为3，那最后一行的变成2个了
  - What is the expected behavior?
     指定每一行是多少最好就是多少个
  - Which versions of Rax, and which browser / OS are affected by this issue?
     latest
  - Did this work in previous versions of Rax?
     no

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.https://alibaba.github.io/rax/playground/d84f0405-a086-4755-9369-3f69e1c3b3b1

**Comment by meterler** [comment]
我也遇到了这个问题，当个数不能被整除有剩余的时候，显示异常

**Comment by yacheng** [comment]
0.4.10 版本已经修复
