### ISSUE TITLE
[rax-touchable] 点击延时

### ISSUE THREAD

**Issue by buaaljy** [alibaba/rax#321]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Enhancement

2. Describe your issue:

 touchable 组件在web下点击延时

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen.

**Comment by yuanyan** [comment]
HTML中加上以下代码试试：

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

点击延迟问题详细可以参考：https://github.com/ftlabs/fastclick
