### ISSUE TITLE
Rax 文档整理与规范

### ISSUE THREAD

**Issue by Lxxyx** [alibaba/rax#324]
最近一直在做 Rax 的代码提示功能，原理是通过解析文档，生成类型定义文件。
做的过程中发现文档总有一些地方会有细微差别，且可预见的是，随着时间的更迭，组件的增加，这个将很难进行下去。

另外写文档与维护也是一件十分繁琐的事情，经常会出现代码改动了，但是文档没有同步的问题。
所以希望能找出一种妥善的方式，尽可能的降低文档的维护成本，且可读性高。

### 期望实现的目标

1. 可读性
    - 人可读
    - 机器可读 
2. 规范性
    - 统一
3. 可维护性高，维护成本低

### 具体实践方式

核心：**通过propTypes属性与JSDoc，去定义props和生成文档**

优点如下：

1. 可读性高：propTypes的可读性对于人或者机器来说，都是非常优秀的，对于后期的文档生成及类型定义文件生成有天然优势
2. 规范性：propTypes是统一的，不会有乱写属性的存在
3. 可维护性高，维护成本低：遵循就近原则，如果组件需要更改 props，再去不同的目录下，修改文档的对应属性及说明会比较繁琐，很容易忘记，而 propTypes 则可以直接在当前文件修改
4. 提前检测错误，降低线上事故发生的可能性：当启用 propTypes 验证时，在开发阶段传入不正确的 props，或者是传入多余的 props，均会报错，从而实现部分静态类型的功能
5. 后续拓展性强：比如想实现某个 props 已经废弃的提示，只需拓展一下即可，比如 `PropTypes.func.isDeprecated`
6. 适用范围广：不仅适用于 Rax，也同时适用于Rax的周边组件，开发出相应的文档生成 cli（已有 [react-docgen](https://github.com/reactjs/react-docgen)），只要开发者书写 propTypes，即可保证生成相应准确的文档与代码提示文件。

缺点如下：

1. 改造成本略高 （通用组件的 propTypes 我已加上，PR： [补全通用组件的PropTypes ](https://github.com/alibaba/rax/pull/323)）
2. 需要工程师熟悉 propTypes 的写法（这个应该写过 React 的同学都知道）

### 文件结构

    .
    ├── README.md // 文档，用于存放组件介绍文档，如标题，仓库地址等
    ├── package.json
    ├── demo
        └── demo.js  // demo演示文件
    └── src
        ├── __tests__
        └── index.js  // 模块入口文件
        
### readme结构与Demo

详见gist: [Text](https://gist.githubusercontent.com/Lxxyx/07d038b5e507ca593af5f14bd5a95e89/raw/3a9df32c4709d665fb50ef2068bb9f558d22835c/text.md)

### 点、线、面

- 点：Rax写代码时没有代码提示
- 线：Rax的文档规范，Rax的文档生成与代码提示等
- 面：Rax周边组件文档的接入，开发者体验的提升，Rax社区生态的建设

感谢 @yacheng  在交流时，对我想法的支持与指导，思考整个方案时，从原来的一个点向面转变，对自己的思维能力也是一个大的提升。

### 欢迎交流

该方案从目前 Rax 的现状与遇到的一些痛点出发，同时参考与借鉴了 Ant-Design 和 React Native 的文档结构与网站生成方式。

上面是个人关于 Rax 文档的全部想法，如果有不足之处，欢迎指正与讨论。
后续也会投入更多时间，尝试实现一些之前想过的关于Rax的idea.

**Comment by wssgcg1213** [comment]
定义props之后, 这些数据最好先抽象出来, 存成一种JSON, 再从json导出文档, 未来可扩展性会更好   可以参考ICE和Fusion 最近在做的 propsSchema

**Comment by Lxxyx** [comment]
@wssgcg1213  嗯嗯，是的。有了 propsSchema 的话，可扩展性会好很多。
