### ISSUE TITLE
[Question, License] I couldn't help but notice that facebook is mentioned in the license.

### ISSUE THREAD

**Issue by japrogramer** [alibaba/rax#327]
- Question
Recently  'Facebook BSD+Patents License'  has come into fire by the Apache Foundation and by the open source community in general https://github.com/facebook/react/issues/10191.
So my question is, Is this project also under the umbrella of 'Facebook BSD+Patents License'?
 ... I don't see a PATENTS file, which is a good sign but im still unsure about the following ...
Why is facebook mentioned in the license? what code comes from a facebook project?

**Comment by Creemli** [comment]
It must have the patents License.

**Comment by wssgcg1213** [comment]
see https://twitter.com/caoyuanyan/status/899520999242186752  no answers yet

**Comment by wssgcg1213** [comment]
@yacheng Rax 开源部分, 是不是需要 LICENSE, 具体哪一种协议  maybe需要讨论一下
