### ISSUE TITLE
rax-dom 支持 unstable_renderSubtreeIntoContainer?

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#335]
![image](https://user-images.githubusercontent.com/3922719/30521927-96f3ec26-9b8d-11e7-9774-b4c7522fa5ad.png)

为了兼容 React, Rax 和 RaxDOM 必须有完全一致的 API, 虽然 `unstable_renderSubtreeIntoContainer` 名称上是不稳定, 但是大量社区中的 Modal 组件`最佳实践`使用了该方法, 包括  reactjs/react-modal  

https://github.com/reactjs/react-modal/blob/93256e92b5452aa2242b2f75f7b9068d297c8750/src/components/Modal.js#L11

So, feature request for `RaxDOM.unstable_renderSubtreeIntoContainer`

**Comment by yuanyan** [comment]
先简单实现了一个：https://github.com/alibaba/rax/commit/ffd1515047a327ee109a1d4d6f2c30309baae539

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/30574144-b6c7f142-9cbd-11e7-8f34-cd199caef725.png)

Meybe rax need to support for same reason;  but can hold until component usage reported

**Comment by wssgcg1213** [comment]
it seems works well

**Comment by wssgcg1213** [comment]
fully supported
