### ISSUE TITLE
I need router msg

### ISSUE THREAD

**Issue by vipplayerdev** [alibaba/rax#337]
rax have the router by itself? and then,how can i use the router. Its there any example?

**Comment by yuanyan** [comment]
You could try https://github.com/kriasoft/universal-router .

**Comment by yangyiru** [comment]
有针对rax本身的router的例子吗？求解？

**Comment by qifenshu** [comment]
@yuanyan thanks for ur help.  the same question like yangyiru, dynamic routing is base demand what we want, is there any solution right now?  @yangyiru  rax without model example,  ,u can write it in componet class,maybe like https://github.com/alibaba/rax/blob/master/examples/redux/index.js ,I have not found the connect function like react-redux, but we can try by us. 

I am a chinese,I like rax, the reason I write with English is just want the issue will help more people.
