### ISSUE TITLE
typo at rax/vdom/composite L139

### ISSUE THREAD

**Issue by ayqy** [alibaba/rax#340]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug

2. Describe your issue:

  - What is the current behavior?
  - What is the expected behavior?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
```javascript
performInSandbox(() => {
  if (instance.componentWillMount) {
    if (process.env.NODE_ENV !== 'production') {
      measureLifeCycle(() => {
        instance.componentWillMount();
// 'componentDidMount' should be 'componentWillMount'
      }, this._mountID, 'componentDidMount');
    } else {
      instance.componentWillMount();
    }
  }
}, instance, errorCallback);
```
<https://github.com/alibaba/rax/blob/master/packages/rax/src/vdom/composite.js#L139>

**Comment by yuanyan** [comment]
Thanks, fixed.
