### ISSUE TITLE
最新版本rax-cli创建的程序，在weex playground中不展示

### ISSUE THREAD

**Issue by zhaopeifei** [alibaba/rax#345]
node是6.8.0版本。使用rax-cli 0.4.13版本，weex playground是1.6版本。
使用rax-cli初始化项目，可以通过二维码扫码在电脑浏览器、手机浏览器中看到创建的demo，但是在weex playground中扫码下方第二个二维码，可以扫描出来，可以下载js文件，但是什么都显示不出来。

**Comment by jackqqxu** [comment]
据说经常没人维护，果然是的；rax init xxx，第一次跑，浏览器提示报错2个：
（1）Failed to load resource: the server responded with a status of 404 () unpkg.com/web-rax-framework@0.4.20-beta/dist/framework.web.js 访问了下，提示：Cannot find package web-rax-framework@0.4.20-beta

（2）Uncaught ReferenceError: define is not defined
    at index.bundle.js:2
