### ISSUE TITLE
input onChange 与 React 表现不一致

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#347]
Rax 与原生一致, 但是 API 不兼容

**Comment by yuanyan** [comment]
期望的表现是什么？

**Comment by wssgcg1213** [comment]
https://github.com/developit/preact-compat/blob/master/src/index.js#L352  

input onChange triggered when DOM oninput event is triggered

**Comment by buaaljy** [comment]
受控模式下，onInput 中文输入法 是有问题的。

**Comment by buaaljy** [comment]
```javascript
render() {
  return (
    <TextInput onInput={(e) => {
      this.setState({
         value: e.target.value || '',
      });
    }}  value={this.state.value} />
  );
}
```
中文输入法有bug

**Comment by tarnishablec** [comment]
> ```js
> render() {
>   return (
>     <TextInput onInput={(e) => {
>       this.setState({
>          value: e.target.value || '',
>       });
>     }}  value={this.state.value} />
>   );
> }
> ```
> 
> 中文输入法有bug

IOS系统内问题依旧存在

**Comment by xmsz** [comment]
any update? @yuanyan 
iOS下，如果加了onChange事件，输入中文就卡爆了，但是使用原生或者安卓就不会
