### ISSUE TITLE
add hnpwa implementation

### ISSUE THREAD

**Issue by tycho01** [alibaba/rax#352]
1. How would you tag this issue?
  - [x] Tip

Congratulations on open-sourcing this; I imagine many people would be quite curious about Rax as an alternative to React.

To answer that question for the community, I think it would be useful if Rax were to provide an implementation for [HNPWA](https://hnpwa.com/), the "spiritual successor to TodoMVC".

I'm not sure if this is the right place for this suggestion, but I'm quite curious as to how this compares to the existing React/Preact implementations there in terms of performance myself, so I'd appreciate it if this were considered. :)

**Comment by yuanyan** [comment]
@tycho01 Good tip for rax, we will do it.
