### ISSUE TITLE
rax 到底是如何嵌入到 weexpack 创建的android项目的

### ISSUE THREAD

**Issue by dotnet123** [alibaba/rax#354]
我用weexpack 创建android项目已经可以运行,
麻烦高人指导一下Rax是如何嵌入进去的,有点急, 谢谢.

**Comment by qifenshu** [comment]
文档不足，同样疑惑。建议直接WEEX。

**Comment by yuanyan** [comment]
@dotnet123 Rax已经内置在weex了，按Rax CLI提示会打包出一个js包，用weex扫一扫就可以跑

**Comment by dotnet123** [comment]
我用git上一个例子https://github.com/xkli/WXSample
用.vue或.we生成的js都可以运行,可是用rax就是不显示,运行不成功.
麻烦看下我的步骤哪里有问题? 谢谢
1)
![tim 20170925212126](https://user-images.githubusercontent.com/21954452/30810592-2e5c4684-a238-11e7-976b-b3e8329d7eef.png)
2)
![tim 20170925212237](https://user-images.githubusercontent.com/21954452/30810604-34f50ddc-a238-11e7-85e6-7bedcb7c2e55.png)
3)
![tim 20170925212342](https://user-images.githubusercontent.com/21954452/30810614-3c41ff8c-a238-11e7-91f4-9cd1964c8804.png)
