### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by wssgcg1213** [alibaba/rax#360]
in browser-driver: removeChild  

```js
removeChild: function removeChild(node, parent) {
    parent = parent || node.parentNode;
    // Maybe has been removed when remove child
    parent.removeChild(node);
},
```

用了 prism-js, 会对 dom 做有状态的处理   

rax 的 vdom -> dom 节点是1对1的, 但是如果dom被处理之后, vdom 不会得到更新, 这个时候 `parent` 对象在DOM上已经不是 `node` 的父层节点了  导致报错  

![image](https://user-images.githubusercontent.com/3922719/30893894-204bd586-a306-11e7-9c1f-3e91bf21a789.png)

**Comment by wssgcg1213** [comment]
suggestions:
```js
if (parent.contains(node)) {
  parent.removeChild(node);
}
```

**Comment by yuanyan** [comment]
这的确是一种情况，看下是不是有更好的策略

**Comment by wssgcg1213** [comment]
有几种策略 
1. 监听 dom mutation event, 对应 dom 移除之后更新 vdom 树, 相当于一个 vdom 和 dom 的双线绑定, 兼容性和性能都不是很好  
2. 这里应该是一个内存泄露的点, 即 dom 被从页面移除但是还保持引用, 我试下 WeakMap 能不能做到..
