### ISSUE TITLE
微信群二维码已过期

### ISSUE THREAD

**Issue by kevilen** [alibaba/rax#409]
如题，微信群二维码已过期；

**Comment by yuanyan** [comment]
你是哪里看到的微信群二维码？github首页有dingding群二维码可以扫一扫

**Comment by findM** [comment]
https://alibaba.github.io/rax/guide/getting-started 这个页面最下方的微信二维码 已经过期了

**Comment by wssgcg1213** [comment]
建议使用钉钉二维码
