### ISSUE TITLE
【Rax - Native】rax目前如何实现与native交互（调用native代码）？

### ISSUE THREAD

**Issue by learhm** [alibaba/rax#418]
Weex官网上说，目前weex 实例变量只在 Vue 框架中暴露了，还不支持在 Rax 框架中使用。
请问，现在该如何实现使用rax调用native端的代码？

**Comment by findM** [comment]
同问

**Comment by wssgcg1213** [comment]
rax 的 native 实现是在 weex 中支持的, 可以参考这个文档对 weex 进行扩展 https://weex.incubator.apache.org/cn/guide/extend-ios.html

这里展示了添加组件和添加方法两类功能  

暴露方法用的 `WX_EXPORT_METHOD` 或者对应的 SYNC 宏, 

在 rax 中用 `require` 方法引用  

```js
const foo = require('@weex-module/fooooo');
```

组件的话如果注册的 view 叫 <foooo>, 直接在 Rax 里面写 `<foooo></foooo>` 就好了, 不需要引入

**Comment by wssgcg1213** [comment]
注册组件 `[WXSDKEngine registerComponent:@"mycomponent" withClass:[WXMyComponent class]]`

**Comment by learhm** [comment]
非常感谢！ @wssgcg1213

**Comment by RaniHu** [comment]
调试的时候客户端那边写了module，调用myModule模块的时候require('@weex-module/myModule');但 提示reportJSException >>>> instanceId:1, exception function:createInstance, exception:Exception: Error: Requiring unknown module "path"

**Comment by AllenBird** [comment]
weex-loader 封装了
__weex_require__('@weex-module/xxx“)
