### ISSUE TITLE
在rax项目下运行npm run start出错，请大神帮忙指导解决

### ISSUE THREAD

**Issue by tgy3300** [alibaba/rax#420]
**在项目下运行：npm run start，出现如何错误**
----------------------------------------------------------------------------
Error: listen EADDRINUSE :::9999
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at Server.listen (F:\weex\hello-world\node_modules\webpack-dev-server\lib\Se
rver.js:570:41)
    at start (F:\weex\hello-world\node_modules\rax-scripts\lib\scripts\start.js:
27:10)
    at Object.<anonymous> (F:\weex\hello-world\node_modules\rax-scripts\lib\scri
pts\start.js:43:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@0.0.0 start: `rax-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-world@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-02-10T0
1_57_13_501Z-debug.log

----------------------------------------------------------------------------
**C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-02-10T0
1_57_13_501Z-debug.log 日志如下：**

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v6.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hello-world@0.0.0~prestart: hello-world@0.0.0
6 info lifecycle hello-world@0.0.0~start: hello-world@0.0.0
7 verbose lifecycle hello-world@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hello-world@0.0.0~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\weex\hello-world\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\nodejs\;D:\phpStudy\php\php-7.0.12-nts;C:\ProgramData\ComposerSetup\bin;D:\Program Files\VisualSVN Server\bin;D:\Program Files\TortoiseSVN\bin;C:\Users\Administrator\AppData\Roaming\npm;C:\Users\Administrator\AppData\Roaming\Composer\vendor\bin;C:\Users\Administrator\AppData\Local\atom\bin
9 verbose lifecycle hello-world@0.0.0~start: CWD: F:\weex\hello-world
10 silly lifecycle hello-world@0.0.0~start: Args: [ '/d /s /c', 'rax-scripts start' ]
11 silly lifecycle hello-world@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle hello-world@0.0.0~start: Failed to exec start script
13 verbose stack Error: hello-world@0.0.0 start: `rax-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid hello-world@0.0.0
15 verbose cwd F:\weex\hello-world
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v6.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error hello-world@0.0.0 start: `rax-scripts start`
22 error Exit status 1
23 error Failed at the hello-world@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tgy3300** [comment]
这是什么错误导致的呢？

**Comment by wssgcg1213** [comment]
9999 端口已经被占用
