### ISSUE TITLE
index.bundle.min.js 太大，在Weex环境中如何优化

### ISSUE THREAD

**Issue by snice** [alibaba/rax#425]
## 问题
Weex官方文档有这么一句：
`Vue.js 和 Rax 都已经集成进了 Weex SDK，你不需要再额外引入。`
但是用rax-cli编译出来的index.bundle.min.js至少50KB，好像是包含了rax。

## 请问如何解决？

**Comment by chenqing** [comment]
@yuanyan

**Comment by yacheng** [comment]
Vue 使用的都是 Weex 原生提供的标签，Rax 则都在上层实现上包了一层，为了对标 react，所以 Rax 肯定会比 Vue 稍大。另外可以排查一下是否自己的项目 bundle 中有打进 Rax，Weex SDK 集成的版本不是最新的，项目 bundle 也可以自己打最新的 Rax 到自己的业务
