### ISSUE TITLE
初始化工程报错

### ISSUE THREAD

**Issue by cxjwin** [alibaba/rax#453]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

按照 https://alibaba.github.io/rax/guide/getting-started 文档进行安装
在 npm run start 的时候遇到如图错误

电脑系统: macOS 10.13.4
node 版本: v9.5.0

报错如图: 
![23_16_03__04_20_2018](https://user-images.githubusercontent.com/1673736/39090585-4d836d7c-4615-11e8-9176-31c4b04a522a.jpg)

**Comment by cxjwin** [comment]
参考 https://github.com/alibaba/rax/issues/443, 0.6.0版本的有问题呀, 什么时候给修复呢?

**Comment by WangXiaoxi** [comment]
遇到了同样的问题。  0.6.0 与 0.6.1 在运行 `yarn run start` 时都会报错。
使用 0.5.4 可以正常运行

**Comment by top-soft** [comment]
同样的问题！！！起初我还以为是node或者npm版本的问题，换了8.x和10.0.0 都是同样的错误。还没开始心都凉了半截了~~

**Comment by yuanyan** [comment]
@cxjwin @WangXiaoxi @top-soft rax-cli@0.6.3 已经修复该问题。
