### ISSUE TITLE
npm 中部分组件版本仍然是 0.6.0，而不是 0.6.1

### ISSUE THREAD

**Issue by savoygu** [alibaba/rax#459]
有些组件的版本是 `0.6.0`，而不是 `0.6.1`，而在 templates 目录中的示例代码（比如：[template-taobao](https://github.com/alibaba/rax/blob/master/templates/template-taobao/package.json)）却依赖的是 `0.6.1 `版本的（比如：[rax-multirow](https://www.npmjs.com/package/rax-multirow)），在 npm 中并不存在对应的 `0.6.1` 版本的组件，导致示例代码无法正常运行。
![image](https://user-images.githubusercontent.com/9302866/39559997-f6efa028-4ecc-11e8-8d4f-e72ca516bf3e.png)

**Comment by yuanyan** [comment]
问题已经修复

**Comment by yuanyan** [comment]
当前最新的版本是 v0.6.3
