### ISSUE TITLE
刚升级了0.6.3，创建项目后，启动报错

### ISSUE THREAD

**Issue by jndxfjz** [alibaba/rax#461]
![image](https://user-images.githubusercontent.com/7391920/39803797-bc1a9110-53a4-11e8-9f03-a9bcf400fb36.png)

**Comment by cloudswindow** [comment]
一样报错，求解

**Comment by jndxfjz** [comment]
@aadd1989 我能说我不会参考吗？刚开始接触，根据官方提供的方法连环境都没搭建起来！！！

**Comment by yuanyan** [comment]
在紧急修复中...

**Comment by yuanyan** [comment]
@aadd1989 @jndxfjz @cloudswindow 是因为包里一个错误的yarn.lock文件被publish了导致的，最新的 rax-cli@0.6.3-1 已经修复该问题

**Comment by aadd1989** [comment]
👍
