### ISSUE TITLE
Component render方法 return this.props.children的时候iOS端会多渲染出WXTextView

### ISSUE THREAD

**Issue by khzliu** [alibaba/rax#468]
在用rax-redux的时候，由于rax-redux的的render函数返回this.props.children，造成view上下各出现一个view

` render() {
    return this.props.children;
  }
`
![image](https://user-images.githubusercontent.com/2516775/40176554-56a86396-5a0e-11e8-9b21-4482e94a902f.png)

![image](https://user-images.githubusercontent.com/2516775/40176577-681ae3e2-5a0e-11e8-8da2-809af37bcbf1.png)

测试代码：
`
 render(<Provider store={store}> <View style={{
    height: '100%',
    flex: 1,
    flexDrection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1fffff',
  }}/> </Provider>);`

撇开rax-redux, 自定义组件如果在组件的render方法里返回this.props.children的时候也会多出一个WXTextView
`render(
return(<Veiw>{this.props.children}</View>);
);
`

现在修改rax-redux组件的源码Provider.js可以解决这个问题：
`render() {
    return this.props.contents ? this.props.contents : null;
  }
`
用法：
`render(<Provider store={store} contents={[<App />]} />);`

不知道是不是bug，还是用法的问题。

**Comment by yuanyan** [comment]
这个TextView是Children里有空格文本吗？

**Comment by khzliu** [comment]
@yuanyan 刚才试了试，果然是空格原因，组件前后各有一个空格才会多出来这个WXTextView
![image](https://user-images.githubusercontent.com/2516775/41291636-ce0f8468-6e82-11e8-89fe-cbf0279366ac.png)
