### ISSUE TITLE
大括号布尔类型没有被置为 null

### ISSUE THREAD

**Issue by jianghai** [alibaba/rax#487]
```jsx
<Text>hello {false}</Text>
```
output

hello false

这种大括号实际上是拆分成多个 child 节点的，不属于直接的字符串拼接，而且 React 也做了 null 处理，习惯 React 写法的人容易踩中这个坑

**Comment by wssgcg1213** [comment]
![image](https://user-images.githubusercontent.com/3922719/42449124-10249908-83b2-11e8-9f63-83ac3d4e149f.png)

as you said, JSX 确实有这个特性 , 我们得评估下修改这个地方可能会导致的问题
