### ISSUE TITLE
TabBarItem icon 不支持自定义的fontFamily

### ISSUE THREAD

**Issue by pinke** [alibaba/rax#492]
https://github.com/alibaba/rax/blob/master/packages/rax-tabbar/src/TabBarItem.js
TabBarItem icon 不支持自定义的fontFamily
这里的fontfamily写死 iconfont

**Comment by szpebble** [comment]
const awesomeFontUrl = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.ttf';

<TabBar.Item title="主页" selected={true} icon={{ uri: awesomeFontUrl, codePoint: '\uf015' }} iconStyle={{ fontSize: 48 }} >.............</TabBar.Item>
