### ISSUE TITLE
[rax-xslider] 如何使用

### ISSUE THREAD

**Issue by WangXiaoxi** [alibaba/rax#496]
1. How would you tag this issue?
  - Feature request

2. Describe your issue:
  请问如何在项目中使用 rax-xslider，
如 Playground 中 
https://jsplayground.taobao.org/raxplayground/8fefa412-5161-42b8-8a3d-a0b473f270ef 
所示的

**Comment by WangXiaoxi** [comment]
在  Playground 项目上看到了 @yacheng  的示例工程，其中使用到 `import Slider from '@ali/rax-xslider'`,
但是目前在 packages 里只有 `rax-slider`, 而没有 `rax-xslider`，请问如何才能使用 `rax-xslider`?
不胜感激 @yuanyan

**Comment by huxiaoqi567** [comment]
@WangXiaoxi rax-xslider已经提pr了 https://github.com/alibaba/rax/pull/581

**Comment by huxiaoqi567** [comment]
https://alibaba.github.io/rax/component/xslider 文档

**Comment by WangXiaoxi** [comment]
@huxiaoqi567 感谢
