### ISSUE TITLE
weex rax framework 调试环境搭建问题

### ISSUE THREAD

**Issue by g770728y** [alibaba/rax#498]
1. How would you tag this issue?

  - Question

2. Describe your issue:
rax新手，macos系统，在按教程https://alibaba.github.io/rax/guide/weex-rax-debug搭建时，第3步：

> 如下修改**html5**/frameworks/index.js 文件
    import * as Weex from './legacy/index'
    import Rax from 'weex-rax-framework'
    export default {
      Rax,
      Weex
    }

如果没有理解错，这里应该修改clone下来的incubator-weex
但incubator-weex目录里，有ios&android目录，但就是没有html5目录（文档中的原话是“修改”，所以照理说应该有一个html5/frameworks/index.js让我修改，而不是我自己创建？）
请问应该怎么做呢？

**Comment by yuanyan** [comment]
rax是内置在weex里的，只需要启动weex调试环境就可以调试rax
