### ISSUE TITLE
代码中混合使用了es6的import和commonjs的module.exports

### ISSUE THREAD

**Issue by kingback** [alibaba/rax#506]
RT，如：<https://github.com/alibaba/rax/blob/master/packages/universal-panresponder/src/index.js#L435>

这种代码风格在

```
{
  loader: 'babel-loader',
  presets: [
    ['env', { modules: false }]
  ]
}
```

下会导致报错，官方也不推荐这两种风格混合使用，相关issue：

<https://github.com/almende/vis/issues/2934>
<https://github.com/webpack/webpack/issues/4039#issuecomment-281136701>
<https://github.com/webpack/webpack/issues/3491>
<https://stackoverflow.com/questions/42449999/webpack-import-module-exports-in-the-same-module-caused-error>

**Comment by wssgcg1213** [comment]
抱歉带来困扰，确实不应该混用 ESM/CommonJS 两种模块导出规范。  

如果方便的话可以提交 PR 帮助我们修复这些问题
