### ISSUE TITLE
rax 项目 0.6.x 无法 start

### ISSUE THREAD

**Issue by postbird** [alibaba/rax#511]
1. How would you tag this issue?

  - Question
 
2. Describe your issue:

分别试了 `rax-cl@0.6.5` / `rax-cli@0.6.3` / `rax-cli@0.6.4` ，（安装的组件和 rax-script 分别都是对应的版本）。

构建项目之后运行 `yarn start` ，webpack building modules 的时候报错如下：

![https://segmentfault.com/img/bVbeJTK?w=545&h=221](https://segmentfault.com/img/bVbeJTK?w=545&h=221)

```javascript
ERROR in ./src/index.js
Module build failed: SyntaxError: E:/Aprojects/node_projects/rax/20180802/demo1/demo3-1/src/index.js: Unexpected token (4:7)

  2 | import App from './App';
  3 |
> 4 | render(<App />);
    |        ^
  5 |
```

- node 版本：0.9.0 
- npm 版本：6.2.0

其他没进行任何操作，也没有增加或者减少代码。

PS：看了其他的 issue，换成 `rax-cli@0.5.4` 之后正常运行。

**Comment by yuanyan** [comment]
通过Yarn安装依赖试试

**Comment by yuanyan** [comment]
看下你 yarn 的版本

**Comment by postbird** [comment]
@yuanyan yarn 版本 1.9.2 ，即使使用 `npm run start` 还是会报错，而 `0.5.4` 怎么运行都没有问题。

**Comment by Lxxyx** [comment]
一样的问题，更换 0.5.4后正常

**Comment by kraaas** [comment]
翻了下代码，发现是`rax-scripts`中使用了 [LoaderOptionsPlugin](https://webpack.js.org/plugins/loader-options-plugin/)导致的，`v0.6.4-6`中已修复，所以我的临时方案是选择`rax-scripts`版本的时候选择`v0.6.4-6`: 
![image](https://user-images.githubusercontent.com/11005827/43824076-943be79a-9b23-11e8-83ca-a7286f4ea4fd.png)

**Comment by postbird** [comment]
@kraaas @yuanyan 使用 `0.6.4-6` 之后能够 start，但是页面报了下面的错误，不知道是否是我网络的问题。

![image](https://user-images.githubusercontent.com/16200574/43874127-93d6c498-9bbc-11e8-844c-8e78530b74a4.png)


而我将 `web-rax-framework@0.6.5` 改成 `web-rax-framework@0.6.4` 之后，就能够正常使用了

**Comment by kraaas** [comment]
@postbird 嗯，这个也要改。应该是发布版本有问题导致这些错误
