### ISSUE TITLE
[rax-textinput] IOS上H5页面点击【完成】收起键盘再唤起键盘很不灵敏

### ISSUE THREAD

**Issue by DionyDing** [alibaba/rax#525]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - 在IOS的浏览器或支付宝等H5场景使用<TextInput />,点击键盘的【完成】按钮收起键盘再唤起很不灵敏，需较大力按下才会唤起，而点击空白处收起键盘则再唤起很灵敏，无须大力按，轻击即可唤起键盘
  - 希望点击键盘的【完成】再唤起键盘与点击空白处收起键盘再唤起一样灵敏
  - 使用最新的0.6.4版本rax，IOS11.4.1，iPhone8，支付宝场景及浏览器场景都会出现，但手淘H5与weex场景均正常
  - 之前版本rax未尝试过

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://codepen.io/D_d/pen/djEzBG) on CodePen

除手淘H5场景下，使用IOS手机打开使用TextInput的页面，点击输入框唤起键盘，再点击键盘的【完成】就会出现这个问题，但点击空白处收起键盘再唤起就不会。
使用支付宝打开会，手淘H5及weex均不会，试了下UC浏览器也会出现。

**Comment by wssgcg1213** [comment]
抱歉, 这应该是客户端行为, Rax 对这种问题暂时没有办法
