### ISSUE TITLE
[Enhancement] Support fragment 

### ISSUE THREAD

**Issue by rccoder** [alibaba/rax#540]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Enhancement

2. Describe your issue:

 2.1 What is the current behavior?

Now Rax support return array in `render` function，In React 16.2，react support `Fragment` Tag to replace `array return`. 

https://reactjs.org/docs/fragments.html

2.2 What is the expected behavior?

Support Rax Fragment Tag.

**Comment by yuanyan** [comment]
v1.0 will support fragment
