### ISSUE TITLE
[rax-button] onPress doesn't work on Android

### ISSUE THREAD

**Issue by Hydraz320** [alibaba/rax#542]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:

  - What is the current behavior?
在onPress中调用了传入的方法(点赞功能)，在iOS上正常，在安卓上没用。
  - What is the expected behavior?
支持安卓
  - Which versions of Rax, and which browser / OS are affected by this issue?
    "rax": "0.x.x",
    "rax-button": "^0.6.4",
试了两台安卓机都这样。
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.
      <Button
        onPress={(e) => {
          handleLike(id);
        }}
      >
        <View style={.........}>
          <Icon style={.....} fontFamily="iconfont" source={...........} />
          <Text>{.........}</Text>
        </View>
      </Button>

**Comment by wssgcg1213** [comment]
可以使用 rax-view 的 onClick 代替
