### ISSUE TITLE
What's the downside of Rax comparing to React?

### ISSUE THREAD

**Issue by irrigator** [alibaba/rax#61]
Everything looks perfect for Rax. However, is it 100% compatible with React? What's the downside of using it instead of React?

**Comment by proyb6** [comment]
You want 100%, Infernojs is well as the author you know is now going to be part of React Team.

**Comment by FateRiddle** [comment]
And why do I want to use Rax, except it is smaller and faster in a mysterious way( especially consider React fiber is on the way)? At least Inferno tells us why it is faster.

**Comment by yuanyan** [comment]
@irrigator The difference document is here: https://github.com/alibaba/rax/blob/master/docs/difference-with-react.md

**Comment by yuanyan** [comment]
@FateRiddle We redesign the react, the `driver` concept in rax let our application could cross-container run.

**Comment by andyhu** [comment]
Here comes another one.
https://github.com/alibaba/rax/issues/63
It's said that rax only supports browsers with webkit as core

**Comment by yuanyan** [comment]
Yes，Rax is most design for mobile device. @andyu

**Comment by jiyinyiyong** [comment]
@andyhu I think it's "in a browser it's Webkit only". However Rax runs on top of Weex too, which runs on Android and iOS in a way kind of similar to React Native.

Need @yuanyan to confirm on the details~
