### ISSUE TITLE
Contributing: master vs not master branch

### ISSUE THREAD

**Issue by timoxley** [alibaba/rax#62]
**There appears to be conflicting/confusing guidelines on how to go about submitting a pull request**

According to your [Pull Request Guidelines in CONTRIBUTING.md](https://github.com/alibaba/rax/blob/07e20908e4e17b182873db0997729cb6c03ab690/.github/CONTRIBUTING.md#pull-request-guidelines):

> **Do not submit PRs against the master branch.**

But then in your [PULL_REQUEST_TEMPLATE.md](https://github.com/alibaba/rax/blob/07e20908e4e17b182873db0997729cb6c03ab690/.github/PULL_REQUEST_TEMPLATE.md):

> Fork the repo and **create your branch from master**.

The above two statements appear to contradict each other.

----

The [Pull Request Guidelines](https://github.com/alibaba/rax/blob/07e20908e4e17b182873db0997729cb6c03ab690/.github/CONTRIBUTING.md#pull-request-guidelines) also say:

> The master branch is basically just a snapshot of the latest stable release

This suggests to me that `master` only updates when there's a release and development occurs on some other branch. But which branch?

> Checkout a topic branch from the relevant branch, e.g. dev, and merge back against that branch.

I looked for a `dev` branch but none existed. Based on the listed branches it is not immediately clear on which branch core development is occurring, as they are all behind master:

![image](https://cloud.githubusercontent.com/assets/43438/21919840/52c4c41a-d998-11e6-9116-f0ee229299e7.png)

I believe that one, or both, of these contributing documents contains out-of-date, or inaccurate information.

---

In addition:

> The master branch is basically just a snapshot of the latest stable release

This github workflow is atypical. In my experience, the most common workflow on github is to develop on the `master` branch, and use one (or more) of the following tools for releases:

* git tags
* [github releases](https://github.com/alibaba/rax/releases)
* Release branches e.g. branches for `v1`, `v2`, etc

I suggest picking one or more of these and using that instead.

If you do choose to develop on a branch other than `master`, then it would be good to configure the [default branch for the github repo](https://help.github.com/articles/setting-the-default-branch/) to be the development branch for the next release. This will help funnel contributors to the right location.

**Comment by yujiangshui** [comment]
Thanks for your advice. We'll fix it ASAP.

**Comment by imsobear** [comment]
- Modify the guidelines as: 

  > The master branch is release branch. All development should be done in dedicated branches. ~~Do not submit PRs against the master branch.~~
  > Checkout a topic branch from  master branch, and merge back against master branch. ~~Checkout a topic branch from the relevant branch, e.g. dev, and merge back against that branch~~

- Publish tag like v0.0.1 when release  version 

Is this OK? @timoxley 

cc @yuanyan

**Comment by timoxley** [comment]
> Publish tag like v0.0.1 when release version

Sounds good to me. 

> The master branch is release branch.

I interpreted this to mean the master branch only contains code that has "already been" released, rather than "going to be" released. Past releases v.s. future releases. Someone else might interpret it differently however. 

I'd also delete the "The master branch is basically just a snapshot of the latest stable release" statement. This makes it sound like `master` will only ever contain the code for the most recent (past) release.

Perhaps something like this is more explicit:

> Only code that's ready for release should be committed to the master branch.

I'd also add the word *new* into the following:

> Checkout **new** a topic branch from master branch, and merge back against master branch.

**Comment by yujiangshui** [comment]
@timoxley I have update the guidelines and new release workflow will apply from now. If you don't have another advice I will close this issue. Thanks again!
