### ISSUE TITLE
[rax-player] 视频播放bug

### ISSUE THREAD

**Issue by Copyes** [alibaba/rax#625]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?
  - Bug
rax-player组件内部的switch方法的状态控制有问题。
```js
// 第一次点击播放按钮后，switchStatus被设置为true，然后播放结束后再点按钮，switchStatus始终是true，就不会执行else里面的逻辑
switch = () => {
    let video = this.refs.video;
    if (this.switchStatus) { 
      video && video.pause();
    } else {
      video && video.play();
    }
    this.switchStatus = !this.switchStatus;
    this.setState({
      pause: this.switchStatus
    });
  }
```
这样就对了。
```js
switch = () => {
    let video = this.refs.video;
    let switchStatus = this.state.pause;
    if (!switchStatus) { 
      video && video.pause();
    } else {
      video && video.play();
    }
    this.setState({
      pause: !switchStatus
    });
  }
```

2. Describe your issue:

  - What is the current behavior?
当视频播放完毕的时候，出现播放按钮后，点击播放按钮，不能播放视频了。
  - What is the expected behavior?
当视频播放完毕的时候，出现播放按钮后，点击播放按钮后继续从头开始播放视频。
  - Which versions of Rax, and which browser / OS are affected by this issue?
Rax版本是0.6.5,  rax-player是0.6.5版本。
  - Did this work in previous versions of Rax?
不能
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.官网的Player例子就直接能复现

**Comment by yacheng** [comment]
fix in this pr https://github.com/alibaba/rax/pull/774
