### ISSUE TITLE
universal-toast多次点击会多次弹出

### ISSUE THREAD

**Issue by liangklfangl** [alibaba/rax#649]
如果点击一个按钮希望弹出一个Toast，当我们快速点击多次的时候会弹出多次Toast，官网例子可见。
http://rax.alibaba-inc.com/playground/16e6f0ed-1c78-446f-82c0-00a662e58633 。 请问这个为啥不清除前一个Toast呢？是出于什么考虑。有没有方法实现快速点击多次只弹出一次的情况?

**Comment by yuanyan** [comment]
这应该是 Toast 的机制设计，目前也没有机制可以清除

**Comment by Chanran** [comment]
debounce包一下toast可以解决。
```
export const debounceToast = debounce (function (msg, callback) {
  Toast.show(msg, Toast.SHORT_DELAY);
  callback()
}, 2000, { leading: true, trailing: false });
```
@liangklfangl
