### ISSUE TITLE
Routing?

### ISSUE THREAD

**Issue by jaspersorrio** [alibaba/rax#65]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [x] Question
  - [ ] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

2. Describe your issue:

  - What is the current behavior?
Rax is a view engine.
  - What is the expected behavior?
Is this compatible with react router?
  - Which versions of Rax, and which browser / OS are affected by this issue?
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://jsfiddle.net/yuanyan/ygjr55fh/) on jsFiddle
.

**Comment by yuanyan** [comment]
We recommend use universal-router: https://github.com/kriasoft/universal-router in rax project.

**Comment by imsobear** [comment]
Maybe could closed this issue :)

**Comment by liuruizhe728** [comment]
> We recommend use universal-router: https://github.com/kriasoft/universal-router in rax project.

开发weex中用rax，用universal-router如何后退页面
