### ISSUE TITLE
[atag swiper] 滑动图片之后没有触发change事件

### ISSUE THREAD

**Issue by ygmpkk** [alibaba/rax#660]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug

```
<swiper :change='handleChange'>
      <swiper-item v-for='img in images'>
          <image :src='img' />
      </swiper-item>
</swiper>
```

```
methods: {
    handleChange(e) {
        // does not working.
        console.log(e.detail.current)
    }
}
```

  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
定义change回调函数
  - What is the expected behavior?
滑动图片之后没有触发change函数
  - Which versions of Rax, and which browser / OS are affected by this issue?
淘宝小程序SFC框架，miniapp-framework 0.1.33
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by wssgcg1213** [comment]
监听事件是 @change
