### ISSUE TITLE
使用rax-xslider时报错

### ISSUE THREAD

**Issue by xiaxiangfeng** [alibaba/rax#662]
ref.js:25 Uncaught (in promise) Error: You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of Rax loaded.

**Comment by yardfarmer** [comment]
You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of Rax loaded

当使用 upx cmd 模块异步加载时提示

**Comment by yuanyan** [comment]
典型的加载了多个rax导致的
