### ISSUE TITLE
How does Rax compare to Preact? 

### ISSUE THREAD

**Issue by flosse** [alibaba/rax#67]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [x] Question

2. Describe your issue:
I'd be interested in a comparison with [Preact](https://github.com/developit/preact)

**Comment by yuanyan** [comment]
Rax is cross-container, not only browser or node.js, we also run rax on weex container. @flosse

**Comment by mrjjwright** [comment]
Is there documentation for how to run on Weex?

**Comment by yuanyan** [comment]
@mrjjwright See getting started: https://github.com/alibaba/rax/blob/master/docs/getting-started.md

**Comment by mrjjwright** [comment]
I get `define is not required` in Chrome and page doesn't load but looks great in Weex Playground

**Comment by imsobear** [comment]
@mrjjwright Is problem solved? ref https://github.com/alibaba/rax/pull/69

**Comment by clarus** [comment]
How does Rax compare to Preact in terms of size and speed?

**Comment by henryluki** [comment]
Can Rax works with Redux or React-router?

**Comment by boiawang** [comment]
@henryluki Redux please see [rax-redux](https://github.com/alibaba/rax/blob/master/packages/rax-redux) and Router see #65

**Comment by jpwesselink** [comment]
@clarus as of writing:

```
Rax#renderToString x 197 ops/sec ±7.25% (60 runs sampled)
React#renderToString x 113 ops/sec ±7.02% (65 runs sampled)
Preact#renderToString x 700 ops/sec ±4.97% (75 runs sampled)
Vue#renderToString x 391 ops/sec ±9.81% (65 runs sampled)
Fastest is Preact#renderToString
```
Please see: https://github.com/taobaofed/server-side-rendering-comparison

**Comment by clarus** [comment]
@jpwesselink Thanks for the link!
