### ISSUE TITLE
rax-scrollview 组件报错，

### ISSUE THREAD

**Issue by khzliu** [alibaba/rax#679]
在weex页面，的scrollTo方法中，没有判断contentContainer.ref的类型，直接用该参数，会报错误。错误日志如下：

`642: 2018-10-24 18:14:48.593 YouPin <Weex>[exception]bundleJSType:Rax
instanceId:27 bundleUrl:http://10.231.94.136:8889/js/index.bundle.js errorCode:-9400 functionName: exception:[WX_KEY_EXCEPTION_WXBRIDGE] [undefined:151:45] TypeError: null is not an object (evaluating 'contentContainer.ref')

native-bundle-main.js:1:163101
forEach@[native code]
receiveTasks@native-bundle-main.js:1:162671
native-bundle-main.js:1:255299 userInfo:{
	jsMainBundleStringContentLength = 6005941,
	jsMainBundleStringContentMd5 = 8f3824b0cb7cc62a24d405383a160ab3
} jsfmVersion:0.24.4 sdkVersion:0.18.0 appVersion:2.5.0 osVersion:12.0 platform:iOS deviceModel:iPhone10,2

If you want to know more, please open weex MNT`

**Comment by yuanyan** [comment]
如果已经销毁了 scrollview 还去调用 scrollTo 是会报错的
