### ISSUE TITLE
小程序onerror捕获异常不工作

### ISSUE THREAD

**Issue by ygmpkk** [alibaba/rax#692]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question
  - Bug
淘宝小程序`onerror`和`addEventListener('error', callback)`方法无法捕获错误
  - Discussion
  - Feature request
  - Tip
  - Enhancement
  - Performance

2. Describe your issue:

  - What is the current behavior?
console.log(\_\_LOCAL\_\_); // 一个不存在的变量
  - What is the expected behavior?
onerror捕获这个异常错误
  - Which versions of Rax, and which browser / OS are affected by this issue?
手淘
  - Did this work in previous versions of Rax?
miniapp-0.1.27

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by yuanyan** [comment]
非rax问题
