### ISSUE TITLE
how to use hover with universal-stylesheet package.

### ISSUE THREAD

**Issue by aranajhonny** [alibaba/rax#72]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [x] Question
  - [ ] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

2. Describe your issue:

Is there any way to do this, none of the examples has this. 

![captura de pantalla 2017-01-13 a las 22 16 36](https://cloud.githubusercontent.com/assets/9091881/21951536/29cf80ae-d9de-11e6-973a-4614ca7ce6c9.png)

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://jsfiddle.net/yuanyan/ygjr55fh/) on jsFiddle
.

**Comment by boiawang** [comment]
Pseudo class is not support not yet. please use `onMouseMove` replace `hover`

**Comment by aranajhonny** [comment]
okay, are you planning to do so in the near future?

**Comment by boiawang** [comment]
Not yet, we do not recommend putting behavior in the `StyleSheet`.
