### ISSUE TITLE
Project on web init failed with define is not defined error

### ISSUE THREAD

**Issue by fakefish** [alibaba/rax#73]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [ ] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

2. Describe your issue:

  - What is the current behavior?
    After `rax init hello` and `npm run start`, open browser with the address which terminal shows, just like `http://10.254.1.155:8080`, browser shows blank page, and the console shows two error about the `define` function.

![image](https://cloud.githubusercontent.com/assets/1334025/21953451/6ef35572-da72-11e6-9ac5-e34fcd473ee0.png)

  - What is the expected behavior?
There should be some text on the page.
  - Which versions of Rax, and which browser / OS are affected by this issue?
```
rax-cli: 0.1.2
rax: 0.1.2
node: 4.7.2
npm: 3.7.3
OS: macOSS Sierra 10.12.2
browser: chrome 55.0
```
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://jsfiddle.net/yuanyan/ygjr55fh/) on jsFiddle
.

**Comment by boiawang** [comment]
fixed #69
