### ISSUE TITLE
[rax-xslider] 安卓上滑动没有效果

### ISSUE THREAD

**Issue by fzliang** [alibaba/rax#751]
在安卓上滑动没有效果

手机系统为MIUI

修改以下代码，将对安卓的特殊处理取消，就能滑动了

修改 DefaultView.js文件
```js
let wrapProps = Detection.isEnableSliderAndroid ? {} : vertical ? {onVerticalPan: this.onPan} : {onHorizontalPan: this.onPan};

let wrapProps = vertical ? {onVerticalPan: this.onPan} : {onHorizontalPan: this.onPan};
```

**Comment by huxiaoqi567** [comment]
需要使用<PanView>来代替普通的View， 可以看下对应的实现，是为了解决按照下划不动的问题。https://github.com/alibaba/rax/blob/master/components/rax-xslider/src/index.js#L12

**Comment by huxiaoqi567** [comment]
@fzliang https://github.com/alibaba/rax/blob/master/components/rax-xslider/src/mods/PanView.js
