### ISSUE TITLE
【rax-xslider】组件横滑与页面横滑冲突，横滑会滑动到下一个页面(横滑翻页)

### ISSUE THREAD

**Issue by hongweitonghua** [alibaba/rax#752]
问题：组件横滑与页面滑动冲突，多个组件的小卡片横滑会滑动到下一个页面。
期望：rax-xslider组件 希望在滑动时，能够切换组件卡片，而不是横滑翻页。

**Comment by yacheng** [comment]
参考使用 demo https://jsplayground.taobao.org/raxplayground/e1475efb-cb88-443b-9f51-388434a90352
