### ISSUE TITLE
Add a "description" field in package.json

### ISSUE THREAD

**Issue by mvila** [alibaba/rax#78]
To appear on [npm addict](https://npmaddict.com) and other npm packages discovery solutions, you should consider adding a `description` field in `package.json`.

**Comment by yuanyan** [comment]
Thanks, will added. @mvila

**Comment by yuanyan** [comment]
@mvila We checked all packages, all have `description` field in package.json.

**Comment by mvila** [comment]
@yuanyan Sorry my mistake, there is a `description` field for the `rax` package but since your project is composed of several packages the `package.json` file at the root of the Git repository is (obviously) not the right one. I improved [npm addict](https://npmaddict.com/) to take this situation into account and `rax` is now correctly listed.
