### ISSUE TITLE
mp-loader 写复杂对象编译会报错

### ISSUE THREAD

**Issue by boiawang** [alibaba/rax#795]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  在 mp 语法里写以下语法形式编译会报错

```html
<view dataSource="{{ [{
  a: 1
}, {
  a: 2
}] }}"></view>
```

```html
<view a="{{
  b: '${1 + 2}'
}}"></view>
```

**Comment by boiawang** [comment]
@wssgcg1213

**Comment by wssgcg1213** [comment]
fixed
