### ISSUE TITLE
TouchableBounce component is undefined

### ISSUE THREAD

**Issue by kagawagao** [alibaba/rax#82]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [ ] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

2. Describe your issue:

  - What is the current behavior?
The `TouchableBounce` in `Game2048.js` is `undefined`, it also cannot be found in `rax-components` 
  - What is the expected behavior?
A real component exist or remove it.
  - Which versions of Rax, and which browser / OS are affected by this issue?
`examples` in branch `master`
  - Did this work in previous versions of Rax?

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://jsfiddle.net/yuanyan/ygjr55fh/) on jsFiddle.
Just play the `game 2048`

**Comment by yuanyan** [comment]
Exported  `TouchableBounce ` in `rax-components`.
