### ISSUE TITLE
useEffect在component快速create->destroy时报错

### ISSUE THREAD

**Issue by WaiSiuKei** [alibaba/rax#852]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:

  - What is the current behavior?

useEffect在component快速create->destroy时报错，场景是https://github.com/WaiSiuKei/grid ，每一个cell都是一个component, 滚出viewport后destory，快速滚动就有问题

  - What is the expected behavior?

https://github.com/alibaba/rax/blob/master/packages/rax/src/hooks.js#L81 
useEffect应该考虑component已经不在的情况

  - Which versions of Rax, and which browser / OS are affected by this issue?

n/a

  - Did this work in previous versions of Rax?

n/a

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
n/a
.

**Comment by yuanyan** [comment]
最新的master上的版本没有复现你的问题

**Comment by WaiSiuKei** [comment]
1.0.0-beta.13已经没有这个问题了https://jsfiddle.net/wgzq8mja/
