### ISSUE TITLE
rax-redux 作为 lib 不应该直接依赖 rax 框架

### ISSUE THREAD

**Issue by devrsi0n** [alibaba/rax#854]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Bug

2. Describe your issue:
  
  rax-redux 作为 lib 不应该直接依赖 rax 框架的吧？这个问题导致项目有 `Error: You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of Rax loaded.`  报错。

![image](https://user-images.githubusercontent.com/7880675/50626854-a5daad80-0f6b-11e9-866c-ea4654c05cb9.png)

**Comment by yuanyan** [comment]
考虑放到 devDeps

**Comment by wssgcg1213** [comment]
Anyone who can raise a PR to help?

**Comment by yuanyan** [comment]
rax-redux@0.6.6 fixed

**Comment by chengqiang1992** [comment]
> ## Help us to manage our issues by answering the following:
> 1. How would you tag this issue?
> 
> * Bug
> 
> 1. Describe your issue:
> 
> rax-redux 作为 lib 不应该直接依赖 rax 框架的吧？这个问题导致项目有 `Error: You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of Rax loaded.` 报错。
> 
> ![image](https://user-images.githubusercontent.com/7880675/50626854-a5daad80-0f6b-11e9-866c-ea4654c05cb9.png)

请问您是怎么集成 rax-redux到项目里边的，我没看到对应的文档
