### ISSUE TITLE
rax是不是可以接入ant-design-mobile这类库？

### ISSUE THREAD

**Issue by weixinjie** [alibaba/rax#857]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:
Rax是否支持接入像ant-design-mobile类似的生态，如果支持，具体应该怎么操作呢？

**Comment by yuanyan** [comment]
rax 本身是没有问题的，因为 rax 在下层，ant-design-mobile 在上层，通常把 react 替换换为 rax 就可以

**Comment by xmsz** [comment]
有实现的DEMO吗
现在直接安装的话，是额外需要安装react吗？
如果使用build.json里的alias字段能否解决问题？

```
These dependencies were not found:

* react in ./node_modules/@ant-design/icons/es/utils.js, ./node_modules/@ant-design/icons/es/components/Context.js and 459 others
* react-dom in ./node_modules/antd/es/modal/confirm.js, ./node_modules/antd/es/typography/util.js and 8 others

To install them, you can run: npm install --save react react-dom
```

**Comment by BoboCactus** [comment]
> 有实现的DEMO吗 现在直接安装的话，是额外需要安装react吗？ 如果使用build.json里的alias字段能否解决问题？
> 
> ```
> These dependencies were not found:
> 
> * react in ./node_modules/@ant-design/icons/es/utils.js, ./node_modules/@ant-design/icons/es/components/Context.js and 459 others
> * react-dom in ./node_modules/antd/es/modal/confirm.js, ./node_modules/antd/es/typography/util.js and 8 others
> 
> To install them, you can run: npm install --save react react-dom
> ```



你这个解决了吗？怎么解决的？我遇到的问题跟你一样

**Comment by c690554125** [comment]
手动引入需要的组件或者使用babel-plugin-import即可。
