### ISSUE TITLE
Preact size and benchmarks

### ISSUE THREAD

**Issue by jpwesselink** [alibaba/rax#86]
Would be nice to see Preact's size and benchmark as well. 

https://github.com/taobaofed/server-side-rendering-comparison/issues/1

**Comment by LeiZeng** [comment]
Interesting, so the only benefit is just compatibility to Weex.

**Comment by yuanyan** [comment]
@LeiZeng Rax is part of weex project, the most import thing is native renderer, not only performance.

**Comment by jpwesselink** [comment]
Reason why I mentioned this is because of completeness: benchmark repo contains benchmarks which are not in this repo's README
