### ISSUE TITLE
devtools调试工具支持

### ISSUE THREAD

**Issue by yuchonghua** [alibaba/rax#951]
期待有一个[React Chrome Dev Tools 调试工具](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en),类似 [nerv-devtools](https://nervjs.github.io/docs/guides/devtools.html)调试工具，这样可以大大提升我们的开发效率，感谢

**Comment by wssgcg1213** [comment]
react-devtool 应该是可以使用的, rax 对其做了兼容  可以试一下

**Comment by zelllez** [comment]
@wssgcg1213 你好请问rax的hook怎么调试？$r._hooks之外有没有别的可视化
