### ISSUE TITLE
 rax-scripts的一些问题

### ISSUE THREAD

**Issue by dkypooh** [alibaba/rax#954]
## rax-scripts 问题
1. rax-scripts help 命令行显示不全
2. rax-scripts start 和 rax-srcript build 不能指定目录和文件运行

**Comment by chenjun1011** [comment]
1. rax-scripts help 命令行显示不全

 0.x 版本确实缺失了 ，正在beta的 1.x 版本会有这块的展示

2. entry 当前是不支持指定的，默认是 src/index.js

0.x 版本理论上不会再做功能的迭代，可以考虑自定义 webpack 配置

**Comment by yuchonghua** [comment]
@dkypooh  自己写一个webpack配置把，其实也不难
