### ISSUE TITLE
README 里的 driver-dom@1.0.0-beta.4 不能用yarn安装

### ISSUE THREAD

**Issue by WaiSiuKei** [alibaba/rax#959]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - Question

2. Describe your issue:
<img width="563" alt="screen shot 2019-03-01 at 10 18 22 am" src="https://user-images.githubusercontent.com/12220022/53612021-93978b80-3c0b-11e9-92d6-6460837865b3.png">
而且https://unpkg.com/driver-dom@1.0.0-beta.4/dist/driver-dom.js也不存在
<img width="605" alt="screen shot 2019-03-01 at 10 21 26 am" src="https://user-images.githubusercontent.com/12220022/53612077-d35e7300-3c0b-11e9-8f1b-93ef9e4c8d41.png">

3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](http://codepen.io/taobaofed/pen/oByQGb) on CodePen
.

**Comment by wssgcg1213** [comment]
1.0.0-beta.4 这个版本没有发布, 请使用 beta.6 或者最新的 beta 版本
