### ISSUE TITLE
想咨询下几个问题

### ISSUE THREAD

**Issue by xuya227939** [alibaba/rax#965]
1、weex脚手架如何接入rax? 通过weex init 启动的项目是跟vue绑定的，例如：weex run ios or weex run android。
2、百度、谷歌、高德地图开放的SDK怎么接入rax?
3、rax1.0.0商业化成本相对于稳定版如何？
4、rax相关的文档只有官网吗？通过rax脚手架搭建的项目，怎么在ios或android上进行发布？

**Comment by yuchonghua** [comment]
同问 2、3

@xuya227939  1、4 很容易解决，自己动手写个cli就可以拉

**Comment by yuchonghua** [comment]
问题1、

因为最终rax打包得到的是Weex的Jsbundle，只需要把打包的Jsbundle放到对应的weex的安卓或者ios项目中，就可以了

**Comment by xuya227939** [comment]
@yuchonghua  团队决定放弃rax，理由如下：
1、对外文档太少，对社区支持不够。
2、稳定版0.6对外可用性太差，商业化使用风险太大。
3、遇到坑了，只能提issue，看issue反馈也不太及时，钉钉群申请两次，没人审批。

**Comment by yuchonghua** [comment]
个人角度，还是觉得rax不错的
不过目前商用可能确实不是很适合
不过目前，我有项目在用rax，其实rax是在文档差了一些，不过熟悉react的话，基本使用rax是没有任何压力的

**Comment by xuya227939** [comment]
@yuchonghua 看元彦、亚城在主弄rax1.0，同样期待rax能起来。

**Comment by yuchonghua** [comment]
我弄个手机架给你用如何，我这几天抽个时间弄个手机架，然后发布给你用一下

/ping @xuya227939

**Comment by yuanyan** [comment]
rax 重点是跨容器的解决方案， weex 是容器之一，在内部 rax 也支持了小程序的容器，今年 rax 重点会重新审视 web 体系，提供在 web 链路上最佳实践。weex 目前是一个偏维护状态，但会随着 weex 社区这块的发展随时改变策略。

**Comment by xuya227939** [comment]
@yuanyan 期待rax今年的更新，感谢你的回复。
