### ISSUE TITLE
Button 'disabled' property doesn't works

### ISSUE THREAD

**Issue by keuller** [alibaba/rax#97]
## Help us to manage our issues by answering the following:

1. How would you tag this issue?

  - [ ] Question
  - [X] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

2. Describe your issue:

  - What is the current behavior? 
  Button HTML does not respect "disabled" property.
  - What is the expected behavior?
  Button HTML component must be disabled when "disabled" property is false or enabled when it is true.
  - Which versions of Rax, and which browser / OS are affected by this issue?
 Rax 0.1.5, Chrome 55.0 on OSX
  - Did this work in previous versions of Rax?
 No, I've tried Rax 0.1.4.
3. If your issue is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [Bug Report Template](https://jsfiddle.net/yuanyan/ygjr55fh/) on jsFiddle

I can't put Rax to work on jsFiddle, so I copy my snippet code that does not works.

```
  render() {
        let hasRows = (this.state.contacts.length > 0)
        return (
            <div className="row">
                <p>&nbsp;</p>
                <button className="btn btn-warning" 
                              disabled={hasRows} onClick={this.onLoad}>Load</button>
                <button className="btn btn-primary" 
                              disabled={!hasRows} onClick={this.onClear}>Clear</button>                
                <div>
                    <Table data={this.state.contacts}></Table>
                </div>
            </div>
        )
    }
```

When I run this code always the two buttons are disabled. I've tried to put true and false directly on disabled property, but it does not works as well. The same snippet code work with React and Preact.

**Comment by yuanyan** [comment]
Thanks for report this bug, will fix soon.

**Comment by yuanyan** [comment]
@keuller rax@0.1.6 fixed this bug.
