### ISSUE TITLE
使用listview时，报 Uncaught Error: Multiple version of Rax used in project.

### ISSUE THREAD

**Issue by hahaay1** [alibaba/rax#977]
我就按照教程，装了一个rax-cli, 然后创建的工程，然后copy的demo代码，为啥报这个错？
百思不得解

**Comment by yuanyan** [comment]
1. rax-listview 依赖的还是 0.x 的rax版本，rax-cli 已经升级到最新的 rax 1.0，所以报多版本的错误
2. copy 的 demo 是哪里的 demo？站点吗？

**Comment by hahaay1** [comment]
> 1. rax-listview 依赖的还是 0.x 的rax版本，rax-cli 已经升级到最新的 rax 1.0，所以报多版本的错误
   换成rax@0.6.6版本后，
   
  报这个错： index.js:329 Uncaught TypeError: Cannot read property 'hydrate' of undefined
    at Object.beforeRender (index.js:329)


> 2. copy 的 demo 是哪里的 demo？站点吗？> https://alibaba.github.io/rax/component/list-view

有没有反馈群啊，github反馈太慢了

**Comment by yuchonghua** [comment]
这一些[rax-xxxx](https://github.com/alibaba/rax/issues/1015)列组件什么时候可以正常使用啊？？？？

**Comment by yuchonghua** [comment]
这一些[rax-xxxx](https://github.com/alibaba/rax/issues/1015)列组件什么时候可以正常使用啊？？？？
@yuanyan

**Comment by yuanyan** [comment]
@yacheng 看下rax-xxx 1.0版本的时间

**Comment by yacheng** [comment]
本周内核心组件会发布 beta 版本，发布组件包括 rax-text、rax-slider、rax-picture、rax-parallax、rax-modal、rax-textinput、rax-video、rax-link、rax-countdown、rax-view、rax-image、rax-recyclerview、rax-scrollview

**Comment by yuchonghua** [comment]
ssr 问题, https://github.com/alibaba/rax/issues/1015 https://github.com/alibaba/rax/issues/889

**Comment by yuchonghua** [comment]
大家都很期待 [rax-xxx 1.0](https://github.com/alibaba/rax/issues/1015)
