### ISSUE TITLE
index.d.ts里缺少render定义

### ISSUE THREAD

**Issue by w2moon** [alibaba/rax#994]
以前的0.6.7版里有，1.0.0以后的都没有
![image](https://user-images.githubusercontent.com/1404305/54801583-7bfb7200-4ca2-11e9-8909-d28d8d76073c.png)

.

**Comment by yuchonghua** [comment]
同问

**Comment by yuanyan** [comment]
https://github.com/alibaba/rax/blob/master/packages/rax/src/index.d.ts @yuchonghua 可以看下问题在哪？

**Comment by yuchonghua** [comment]
我估计问题是在index.d.ts没有render这个方法的声明，因为React的包是不包含 render 方法的，而rax是包括render方法的，rax的index.d.ts没有发现导出了render声明
